services:
  postgres:
    image: postgres:16.13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "${DATABASE_NAME:-patchbase}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD:-postgres}"
    ports:
      - 5432:5432

  mailpit:
    image: axllent/mailpit:v1.27
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  postgres_data:
