// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: advisory_references.sql

package sql

import (
	"context"

	"go.patchbase.net/server/internal/utils"
)

const deleteAdvisoryReferencesByStreamIDs = `-- name: DeleteAdvisoryReferencesByStreamIDs :exec
DELETE FROM advisory_references
WHERE advisory_id IN (
    SELECT DISTINCT advisory_id FROM advisory_product_streams
    WHERE product_stream_id = ANY($1::text[])
)
`

func (q *Queries) DeleteAdvisoryReferencesByStreamIDs(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteAdvisoryReferencesByStreamIDs, dollar_1)
	return err
}

const insertAdvisoryReference = `-- name: InsertAdvisoryReference :exec
INSERT INTO advisory_references (
    id, advisory_id, ref_type, ref_value, severity_vendor, severity_cvss, title, url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (id) DO UPDATE SET
    advisory_id = EXCLUDED.advisory_id,
    ref_type = EXCLUDED.ref_type,
    ref_value = EXCLUDED.ref_value,
    severity_vendor = EXCLUDED.severity_vendor,
    severity_cvss = EXCLUDED.severity_cvss,
    title = EXCLUDED.title,
    url = EXCLUDED.url
`

type InsertAdvisoryReferenceParams struct {
	ID             string
	AdvisoryID     string
	RefType        string
	RefValue       string
	SeverityVendor utils.Option[string]
	SeverityCvss   *float64
	Title          utils.Option[string]
	Url            utils.Option[string]
}

func (q *Queries) InsertAdvisoryReference(ctx context.Context, arg InsertAdvisoryReferenceParams) error {
	_, err := q.db.Exec(ctx, insertAdvisoryReference,
		arg.ID,
		arg.AdvisoryID,
		arg.RefType,
		arg.RefValue,
		arg.SeverityVendor,
		arg.SeverityCvss,
		arg.Title,
		arg.Url,
	)
	return err
}
