// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: advisory_product_streams.sql

package sql

import (
	"context"
)

const deleteAdvisoryProductStreamsByStreamIDs = `-- name: DeleteAdvisoryProductStreamsByStreamIDs :exec
DELETE FROM advisory_product_streams
WHERE product_stream_id = ANY($1::text[])
`

func (q *Queries) DeleteAdvisoryProductStreamsByStreamIDs(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteAdvisoryProductStreamsByStreamIDs, dollar_1)
	return err
}

const insertAdvisoryProductStream = `-- name: InsertAdvisoryProductStream :exec
INSERT INTO advisory_product_streams (
    advisory_id, product_stream_id
) VALUES (
    $1, $2
)
ON CONFLICT (advisory_id, product_stream_id) DO NOTHING
`

type InsertAdvisoryProductStreamParams struct {
	AdvisoryID      string
	ProductStreamID string
}

func (q *Queries) InsertAdvisoryProductStream(ctx context.Context, arg InsertAdvisoryProductStreamParams) error {
	_, err := q.db.Exec(ctx, insertAdvisoryProductStream, arg.AdvisoryID, arg.ProductStreamID)
	return err
}

const listAdvisoryProductStreamsByStreamIDs = `-- name: ListAdvisoryProductStreamsByStreamIDs :many
SELECT advisory_id, product_stream_id FROM advisory_product_streams
WHERE product_stream_id = ANY($1::text[])
`

func (q *Queries) ListAdvisoryProductStreamsByStreamIDs(ctx context.Context, dollar_1 []string) ([]AdvisoryProductStream, error) {
	rows, err := q.db.Query(ctx, listAdvisoryProductStreamsByStreamIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdvisoryProductStream
	for rows.Next() {
		var i AdvisoryProductStream
		if err := rows.Scan(&i.AdvisoryID, &i.ProductStreamID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
