// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: advisories.sql

package sql

import (
	"context"

	"go.patchbase.net/server/internal/utils"
)

const deleteAdvisoriesWithoutStreams = `-- name: DeleteAdvisoriesWithoutStreams :exec
DELETE FROM advisories
WHERE id NOT IN (
    SELECT DISTINCT advisory_id FROM advisory_product_streams
)
`

func (q *Queries) DeleteAdvisoriesWithoutStreams(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAdvisoriesWithoutStreams)
	return err
}

const listAdvisoriesByStreamIDs = `-- name: ListAdvisoriesByStreamIDs :many
SELECT DISTINCT a.id, a.source_system, a.raw_source_id, a.source_url, a.vendor, a.advisory_type, a.severity, a.summary, a.description, a.published_at, a.updated_at, a.evidence_tier, a.is_security FROM advisories a
JOIN advisory_product_streams aps ON aps.advisory_id = a.id
WHERE aps.product_stream_id = ANY($1::text[])
`

func (q *Queries) ListAdvisoriesByStreamIDs(ctx context.Context, dollar_1 []string) ([]Advisory, error) {
	rows, err := q.db.Query(ctx, listAdvisoriesByStreamIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Advisory
	for rows.Next() {
		var i Advisory
		if err := rows.Scan(
			&i.ID,
			&i.SourceSystem,
			&i.RawSourceID,
			&i.SourceUrl,
			&i.Vendor,
			&i.AdvisoryType,
			&i.Severity,
			&i.Summary,
			&i.Description,
			&i.PublishedAt,
			&i.UpdatedAt,
			&i.EvidenceTier,
			&i.IsSecurity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAdvisories = `-- name: ListRecentAdvisories :many
SELECT id, source_system, raw_source_id, source_url, vendor, advisory_type, severity, summary, description, published_at, updated_at, evidence_tier, is_security FROM advisories
ORDER BY published_at DESC
LIMIT 5
`

func (q *Queries) ListRecentAdvisories(ctx context.Context) ([]Advisory, error) {
	rows, err := q.db.Query(ctx, listRecentAdvisories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Advisory
	for rows.Next() {
		var i Advisory
		if err := rows.Scan(
			&i.ID,
			&i.SourceSystem,
			&i.RawSourceID,
			&i.SourceUrl,
			&i.Vendor,
			&i.AdvisoryType,
			&i.Severity,
			&i.Summary,
			&i.Description,
			&i.PublishedAt,
			&i.UpdatedAt,
			&i.EvidenceTier,
			&i.IsSecurity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAdvisory = `-- name: UpsertAdvisory :exec
INSERT INTO advisories (
    id, source_system, raw_source_id, source_url, vendor, advisory_type, severity, summary, description, published_at, updated_at, evidence_tier, is_security
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
ON CONFLICT (id) DO UPDATE SET
    source_system = EXCLUDED.source_system,
    raw_source_id = EXCLUDED.raw_source_id,
    source_url = EXCLUDED.source_url,
    vendor = EXCLUDED.vendor,
    advisory_type = EXCLUDED.advisory_type,
    severity = EXCLUDED.severity,
    summary = EXCLUDED.summary,
    description = EXCLUDED.description,
    published_at = EXCLUDED.published_at,
    updated_at = EXCLUDED.updated_at,
    evidence_tier = EXCLUDED.evidence_tier,
    is_security = EXCLUDED.is_security
`

type UpsertAdvisoryParams struct {
	ID           string
	SourceSystem string
	RawSourceID  string
	SourceUrl    utils.Option[string]
	Vendor       string
	AdvisoryType string
	Severity     utils.Option[string]
	Summary      utils.Option[string]
	Description  utils.Option[string]
	PublishedAt  utils.Option[string]
	UpdatedAt    utils.Option[string]
	EvidenceTier string
	IsSecurity   bool
}

func (q *Queries) UpsertAdvisory(ctx context.Context, arg UpsertAdvisoryParams) error {
	_, err := q.db.Exec(ctx, upsertAdvisory,
		arg.ID,
		arg.SourceSystem,
		arg.RawSourceID,
		arg.SourceUrl,
		arg.Vendor,
		arg.AdvisoryType,
		arg.Severity,
		arg.Summary,
		arg.Description,
		arg.PublishedAt,
		arg.UpdatedAt,
		arg.EvidenceTier,
		arg.IsSecurity,
	)
	return err
}
