// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: affected_package_rules.sql

package sql

import (
	"context"

	"go.patchbase.net/server/internal/utils"
)

const deleteAffectedPackageRulesByStreamIDs = `-- name: DeleteAffectedPackageRulesByStreamIDs :exec
DELETE FROM affected_package_rules
WHERE product_stream_id = ANY($1::text[])
`

func (q *Queries) DeleteAffectedPackageRulesByStreamIDs(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteAffectedPackageRulesByStreamIDs, dollar_1)
	return err
}

const insertAffectedPackageRule = `-- name: InsertAffectedPackageRule :exec
INSERT INTO affected_package_rules (
    id, advisory_id, product_stream_id, package_name, source_rpm, arch, epoch_constraint, version_constraint, release_constraint, rpm_evr_rule, context, evidence_tier
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
ON CONFLICT (id) DO UPDATE SET
    advisory_id = EXCLUDED.advisory_id,
    product_stream_id = EXCLUDED.product_stream_id,
    package_name = EXCLUDED.package_name,
    source_rpm = EXCLUDED.source_rpm,
    arch = EXCLUDED.arch,
    epoch_constraint = EXCLUDED.epoch_constraint,
    version_constraint = EXCLUDED.version_constraint,
    release_constraint = EXCLUDED.release_constraint,
    rpm_evr_rule = EXCLUDED.rpm_evr_rule,
    context = EXCLUDED.context,
    evidence_tier = EXCLUDED.evidence_tier
`

type InsertAffectedPackageRuleParams struct {
	ID                string
	AdvisoryID        string
	ProductStreamID   string
	PackageName       string
	SourceRpm         utils.Option[string]
	Arch              utils.Option[string]
	EpochConstraint   utils.Option[string]
	VersionConstraint utils.Option[string]
	ReleaseConstraint utils.Option[string]
	RpmEvrRule        utils.Option[string]
	Context           string
	EvidenceTier      string
}

func (q *Queries) InsertAffectedPackageRule(ctx context.Context, arg InsertAffectedPackageRuleParams) error {
	_, err := q.db.Exec(ctx, insertAffectedPackageRule,
		arg.ID,
		arg.AdvisoryID,
		arg.ProductStreamID,
		arg.PackageName,
		arg.SourceRpm,
		arg.Arch,
		arg.EpochConstraint,
		arg.VersionConstraint,
		arg.ReleaseConstraint,
		arg.RpmEvrRule,
		arg.Context,
		arg.EvidenceTier,
	)
	return err
}

const listAffectedPackageRulesByStreamIDs = `-- name: ListAffectedPackageRulesByStreamIDs :many
SELECT id, advisory_id, product_stream_id, package_name, source_rpm, arch, epoch_constraint, version_constraint, release_constraint, rpm_evr_rule, context, evidence_tier FROM affected_package_rules
WHERE product_stream_id = ANY($1::text[])
`

func (q *Queries) ListAffectedPackageRulesByStreamIDs(ctx context.Context, dollar_1 []string) ([]AffectedPackageRule, error) {
	rows, err := q.db.Query(ctx, listAffectedPackageRulesByStreamIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AffectedPackageRule
	for rows.Next() {
		var i AffectedPackageRule
		if err := rows.Scan(
			&i.ID,
			&i.AdvisoryID,
			&i.ProductStreamID,
			&i.PackageName,
			&i.SourceRpm,
			&i.Arch,
			&i.EpochConstraint,
			&i.VersionConstraint,
			&i.ReleaseConstraint,
			&i.RpmEvrRule,
			&i.Context,
			&i.EvidenceTier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
