// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_log.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"go.patchbase.net/server/internal/utils"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*) FROM audit_log
`

func (q *Queries) CountAuditLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuditLogsFiltered = `-- name: CountAuditLogsFiltered :one
SELECT COUNT(*) FROM audit_log
WHERE
    ($1::text IS NULL OR action = $1::text)
    AND ($2::text IS NULL OR actor_id = $2::text)
    AND ($3::timestamptz IS NULL OR created_at >= $3::timestamptz)
    AND ($4::timestamptz IS NULL OR created_at <= $4::timestamptz)
`

type CountAuditLogsFilteredParams struct {
	Action  utils.Option[string]
	ActorID utils.Option[string]
	From    pgtype.Timestamptz
	To      pgtype.Timestamptz
}

func (q *Queries) CountAuditLogsFiltered(ctx context.Context, arg CountAuditLogsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogsFiltered,
		arg.Action,
		arg.ActorID,
		arg.From,
		arg.To,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (
    id,
    actor_id,
    actor_email,
    action,
    target_type,
    target_id,
    metadata,
    ip_address,
    user_agent
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type InsertAuditLogParams struct {
	ID         string
	ActorID    utils.Option[string]
	ActorEmail string
	Action     string
	TargetType string
	TargetID   utils.Option[string]
	Metadata   []byte
	IpAddress  utils.Option[string]
	UserAgent  utils.Option[string]
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ID,
		arg.ActorID,
		arg.ActorEmail,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, actor_id, actor_email, action, target_type, target_id, metadata, ip_address, user_agent, created_at
FROM audit_log
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorEmail,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsFiltered = `-- name: ListAuditLogsFiltered :many
SELECT id, actor_id, actor_email, action, target_type, target_id, metadata, ip_address, user_agent, created_at
FROM audit_log
WHERE
    ($1::text IS NULL OR action = $1::text)
    AND ($2::text IS NULL OR actor_id = $2::text)
    AND ($3::timestamptz IS NULL OR created_at >= $3::timestamptz)
    AND ($4::timestamptz IS NULL OR created_at <= $4::timestamptz)
ORDER BY created_at DESC, id DESC
LIMIT $6 OFFSET $5
`

type ListAuditLogsFilteredParams struct {
	Action  utils.Option[string]
	ActorID utils.Option[string]
	From    pgtype.Timestamptz
	To      pgtype.Timestamptz
	Offset  int32
	Limit   int32
}

func (q *Queries) ListAuditLogsFiltered(ctx context.Context, arg ListAuditLogsFilteredParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsFiltered,
		arg.Action,
		arg.ActorID,
		arg.From,
		arg.To,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorEmail,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
