// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: decision_records.sql

package sql

import (
	"context"

	"go.patchbase.net/server/internal/utils"
)

const deleteDecisionRecordsBySnapshot = `-- name: DeleteDecisionRecordsBySnapshot :exec
DELETE FROM decision_records
WHERE snapshot_id = $1
`

func (q *Queries) DeleteDecisionRecordsBySnapshot(ctx context.Context, snapshotID string) error {
	_, err := q.db.Exec(ctx, deleteDecisionRecordsBySnapshot, snapshotID)
	return err
}

const insertDecisionRecord = `-- name: InsertDecisionRecord :exec
INSERT INTO decision_records (
    id, host_id, snapshot_id, advisory_id, installed_package_id, product_stream_id, package_name, installed_nevra, fixed_nevra, status, action, severity, evidence_tier, reason_code, reason_text, computed_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
`

type InsertDecisionRecordParams struct {
	ID                 string
	HostID             string
	SnapshotID         string
	AdvisoryID         string
	InstalledPackageID utils.Option[string]
	ProductStreamID    utils.Option[string]
	PackageName        string
	InstalledNevra     utils.Option[string]
	FixedNevra         utils.Option[string]
	Status             string
	Action             string
	Severity           utils.Option[string]
	EvidenceTier       string
	ReasonCode         string
	ReasonText         utils.Option[string]
	ComputedAt         string
}

func (q *Queries) InsertDecisionRecord(ctx context.Context, arg InsertDecisionRecordParams) error {
	_, err := q.db.Exec(ctx, insertDecisionRecord,
		arg.ID,
		arg.HostID,
		arg.SnapshotID,
		arg.AdvisoryID,
		arg.InstalledPackageID,
		arg.ProductStreamID,
		arg.PackageName,
		arg.InstalledNevra,
		arg.FixedNevra,
		arg.Status,
		arg.Action,
		arg.Severity,
		arg.EvidenceTier,
		arg.ReasonCode,
		arg.ReasonText,
		arg.ComputedAt,
	)
	return err
}

const listDecisionPageRowsBySnapshot = `-- name: ListDecisionPageRowsBySnapshot :many
SELECT
    dr.id,
    dr.host_id,
    dr.snapshot_id,
    dr.advisory_id,
    dr.installed_package_id,
    dr.product_stream_id,
    dr.package_name,
    dr.installed_nevra,
    dr.fixed_nevra,
    dr.status,
    dr.action,
    COALESCE(
        NULLIF(dr.severity, ''),
        NULLIF(a.severity, ''),
        (
            SELECT CASE MAX(
                CASE
                    WHEN lower(ar.severity_vendor) = 'critical' THEN 4
                    WHEN lower(ar.severity_vendor) IN ('important', 'high') THEN 3
                    WHEN lower(ar.severity_vendor) IN ('moderate', 'medium') THEN 2
                    WHEN lower(ar.severity_vendor) = 'low' THEN 1
                    ELSE 0
                END
            )
                WHEN 4 THEN 'critical'
                WHEN 3 THEN 'important'
                WHEN 2 THEN 'moderate'
                WHEN 1 THEN 'low'
                ELSE NULL
            END
            FROM advisory_references ar
            WHERE ar.advisory_id = dr.advisory_id
        )
    ) AS severity,
    dr.evidence_tier,
    dr.reason_code,
    dr.reason_text,
    dr.computed_at,
    a.summary AS advisory_summary,
    a.is_security AS advisory_is_security,
    a.source_url AS advisory_source_url,
    a.advisory_type AS advisory_type,
    a.source_system AS advisory_source_system,
    a.updated_at AS advisory_updated_at,
    COALESCE(
        (SELECT json_agg(json_build_object('id', ref_value, 'url', COALESCE(url, '')))
         FROM advisory_references
         WHERE advisory_id = dr.advisory_id AND ref_type = 'cve'),
        '[]'::json
    ) AS cves
FROM decision_records dr
JOIN advisories a ON a.id = dr.advisory_id
WHERE dr.snapshot_id = $1
`

type ListDecisionPageRowsBySnapshotRow struct {
	ID                   string
	HostID               string
	SnapshotID           string
	AdvisoryID           string
	InstalledPackageID   utils.Option[string]
	ProductStreamID      utils.Option[string]
	PackageName          string
	InstalledNevra       utils.Option[string]
	FixedNevra           utils.Option[string]
	Status               string
	Action               string
	Severity             interface{}
	EvidenceTier         string
	ReasonCode           string
	ReasonText           utils.Option[string]
	ComputedAt           string
	AdvisorySummary      utils.Option[string]
	AdvisoryIsSecurity   bool
	AdvisorySourceUrl    utils.Option[string]
	AdvisoryType         string
	AdvisorySourceSystem string
	AdvisoryUpdatedAt    utils.Option[string]
	Cves                 interface{}
}

func (q *Queries) ListDecisionPageRowsBySnapshot(ctx context.Context, snapshotID string) ([]ListDecisionPageRowsBySnapshotRow, error) {
	rows, err := q.db.Query(ctx, listDecisionPageRowsBySnapshot, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDecisionPageRowsBySnapshotRow
	for rows.Next() {
		var i ListDecisionPageRowsBySnapshotRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.SnapshotID,
			&i.AdvisoryID,
			&i.InstalledPackageID,
			&i.ProductStreamID,
			&i.PackageName,
			&i.InstalledNevra,
			&i.FixedNevra,
			&i.Status,
			&i.Action,
			&i.Severity,
			&i.EvidenceTier,
			&i.ReasonCode,
			&i.ReasonText,
			&i.ComputedAt,
			&i.AdvisorySummary,
			&i.AdvisoryIsSecurity,
			&i.AdvisorySourceUrl,
			&i.AdvisoryType,
			&i.AdvisorySourceSystem,
			&i.AdvisoryUpdatedAt,
			&i.Cves,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
