// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fixed_packages.sql

package sql

import (
	"context"

	"go.patchbase.net/server/internal/utils"
)

const deleteFixedPackagesByStreamIDs = `-- name: DeleteFixedPackagesByStreamIDs :exec
DELETE FROM fixed_packages
WHERE product_stream_id = ANY($1::text[])
`

func (q *Queries) DeleteFixedPackagesByStreamIDs(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteFixedPackagesByStreamIDs, dollar_1)
	return err
}

const insertFixedPackage = `-- name: InsertFixedPackage :exec
INSERT INTO fixed_packages (
    id, advisory_id, product_stream_id, package_name, epoch, version, release, arch, nevra, source_rpm, repo_family, evidence_tier
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
ON CONFLICT (id) DO UPDATE SET
    advisory_id = EXCLUDED.advisory_id,
    product_stream_id = EXCLUDED.product_stream_id,
    package_name = EXCLUDED.package_name,
    epoch = EXCLUDED.epoch,
    version = EXCLUDED.version,
    release = EXCLUDED.release,
    arch = EXCLUDED.arch,
    nevra = EXCLUDED.nevra,
    source_rpm = EXCLUDED.source_rpm,
    repo_family = EXCLUDED.repo_family,
    evidence_tier = EXCLUDED.evidence_tier
`

type InsertFixedPackageParams struct {
	ID              string
	AdvisoryID      string
	ProductStreamID string
	PackageName     string
	Epoch           int32
	Version         string
	Release         string
	Arch            utils.Option[string]
	Nevra           string
	SourceRpm       utils.Option[string]
	RepoFamily      utils.Option[string]
	EvidenceTier    string
}

func (q *Queries) InsertFixedPackage(ctx context.Context, arg InsertFixedPackageParams) error {
	_, err := q.db.Exec(ctx, insertFixedPackage,
		arg.ID,
		arg.AdvisoryID,
		arg.ProductStreamID,
		arg.PackageName,
		arg.Epoch,
		arg.Version,
		arg.Release,
		arg.Arch,
		arg.Nevra,
		arg.SourceRpm,
		arg.RepoFamily,
		arg.EvidenceTier,
	)
	return err
}

const listFixedPackagesByStreamIDs = `-- name: ListFixedPackagesByStreamIDs :many
SELECT id, advisory_id, product_stream_id, package_name, epoch, version, release, arch, nevra, source_rpm, repo_family, evidence_tier FROM fixed_packages
WHERE product_stream_id = ANY($1::text[])
`

func (q *Queries) ListFixedPackagesByStreamIDs(ctx context.Context, dollar_1 []string) ([]FixedPackage, error) {
	rows, err := q.db.Query(ctx, listFixedPackagesByStreamIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FixedPackage
	for rows.Next() {
		var i FixedPackage
		if err := rows.Scan(
			&i.ID,
			&i.AdvisoryID,
			&i.ProductStreamID,
			&i.PackageName,
			&i.Epoch,
			&i.Version,
			&i.Release,
			&i.Arch,
			&i.Nevra,
			&i.SourceRpm,
			&i.RepoFamily,
			&i.EvidenceTier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
