// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: host_ssh_pull_jobs.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"go.patchbase.net/server/internal/utils"
)

const insertHostSSHPullJob = `-- name: InsertHostSSHPullJob :one
INSERT INTO host_ssh_pull_jobs (
    id,
    host_id,
    status,
    started_at
)
VALUES (
    $1, $2, $3, $4
)
RETURNING id, host_id, status, started_at, completed_at, error
`

type InsertHostSSHPullJobParams struct {
	ID        string
	HostID    string
	Status    string
	StartedAt pgtype.Timestamptz
}

func (q *Queries) InsertHostSSHPullJob(ctx context.Context, arg InsertHostSSHPullJobParams) (HostSshPullJob, error) {
	row := q.db.QueryRow(ctx, insertHostSSHPullJob,
		arg.ID,
		arg.HostID,
		arg.Status,
		arg.StartedAt,
	)
	var i HostSshPullJob
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
	)
	return i, err
}

const listHostSSHPullJobsByHostID = `-- name: ListHostSSHPullJobsByHostID :many
SELECT id, host_id, status, started_at, completed_at, error
FROM host_ssh_pull_jobs
WHERE host_id = $1
ORDER BY started_at DESC
LIMIT $2
`

type ListHostSSHPullJobsByHostIDParams struct {
	HostID string
	Limit  int32
}

func (q *Queries) ListHostSSHPullJobsByHostID(ctx context.Context, arg ListHostSSHPullJobsByHostIDParams) ([]HostSshPullJob, error) {
	rows, err := q.db.Query(ctx, listHostSSHPullJobsByHostID, arg.HostID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HostSshPullJob
	for rows.Next() {
		var i HostSshPullJob
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHostSSHPullJob = `-- name: UpdateHostSSHPullJob :one
UPDATE host_ssh_pull_jobs
SET
    status = $2,
    completed_at = $3,
    error = $4
WHERE id = $1
RETURNING id, host_id, status, started_at, completed_at, error
`

type UpdateHostSSHPullJobParams struct {
	ID          string
	Status      string
	CompletedAt pgtype.Timestamptz
	Error       utils.Option[string]
}

func (q *Queries) UpdateHostSSHPullJob(ctx context.Context, arg UpdateHostSSHPullJobParams) (HostSshPullJob, error) {
	row := q.db.QueryRow(ctx, updateHostSSHPullJob,
		arg.ID,
		arg.Status,
		arg.CompletedAt,
		arg.Error,
	)
	var i HostSshPullJob
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
	)
	return i, err
}
