// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: host_access_tokens.sql

package sql

import (
	"context"
)

const deleteHostAccessTokensByHostID = `-- name: DeleteHostAccessTokensByHostID :exec
DELETE FROM host_access_tokens
WHERE host_id = $1
`

func (q *Queries) DeleteHostAccessTokensByHostID(ctx context.Context, hostID string) error {
	_, err := q.db.Exec(ctx, deleteHostAccessTokensByHostID, hostID)
	return err
}

const getActiveHostAccessTokenByHash = `-- name: GetActiveHostAccessTokenByHash :one
SELECT id, host_id, token_hash, created_at, revoked_at, last_used_at
FROM host_access_tokens
WHERE token_hash = $1
  AND revoked_at IS NULL
LIMIT 1
`

func (q *Queries) GetActiveHostAccessTokenByHash(ctx context.Context, tokenHash string) (HostAccessToken, error) {
	row := q.db.QueryRow(ctx, getActiveHostAccessTokenByHash, tokenHash)
	var i HostAccessToken
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const insertHostAccessToken = `-- name: InsertHostAccessToken :one
INSERT INTO host_access_tokens (
    id,
    host_id,
    token_hash
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, host_id, token_hash, created_at, revoked_at, last_used_at
`

type InsertHostAccessTokenParams struct {
	ID        string
	HostID    string
	TokenHash string
}

func (q *Queries) InsertHostAccessToken(ctx context.Context, arg InsertHostAccessTokenParams) (HostAccessToken, error) {
	row := q.db.QueryRow(ctx, insertHostAccessToken, arg.ID, arg.HostID, arg.TokenHash)
	var i HostAccessToken
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const touchHostAccessTokenLastUsed = `-- name: TouchHostAccessTokenLastUsed :exec
UPDATE host_access_tokens
SET last_used_at = now()
WHERE id = $1
`

func (q *Queries) TouchHostAccessTokenLastUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchHostAccessTokenLastUsed, id)
	return err
}
