// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: host_snapshots.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteHostCurrentStateByHostID = `-- name: DeleteHostCurrentStateByHostID :exec
DELETE FROM host_current_state
WHERE host_id = $1
`

func (q *Queries) DeleteHostCurrentStateByHostID(ctx context.Context, hostID string) error {
	_, err := q.db.Exec(ctx, deleteHostCurrentStateByHostID, hostID)
	return err
}

const deleteHostSnapshotsByHostID = `-- name: DeleteHostSnapshotsByHostID :exec
DELETE FROM host_snapshots
WHERE host_id = $1
`

func (q *Queries) DeleteHostSnapshotsByHostID(ctx context.Context, hostID string) error {
	_, err := q.db.Exec(ctx, deleteHostSnapshotsByHostID, hostID)
	return err
}

const getHostSnapshot = `-- name: GetHostSnapshot :one
SELECT id, host_id, collected_at, received_at, payload, running_kernel_nevra, boot_time, has_process_data, created_at FROM host_snapshots
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetHostSnapshot(ctx context.Context, id string) (HostSnapshot, error) {
	row := q.db.QueryRow(ctx, getHostSnapshot, id)
	var i HostSnapshot
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.CollectedAt,
		&i.ReceivedAt,
		&i.Payload,
		&i.RunningKernelNevra,
		&i.BootTime,
		&i.HasProcessData,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestHostSnapshotByHostID = `-- name: GetLatestHostSnapshotByHostID :one
SELECT id, host_id, collected_at, received_at, payload, running_kernel_nevra, boot_time, has_process_data, created_at
FROM host_snapshots
WHERE host_id = $1
ORDER BY collected_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestHostSnapshotByHostID(ctx context.Context, hostID string) (HostSnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestHostSnapshotByHostID, hostID)
	var i HostSnapshot
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.CollectedAt,
		&i.ReceivedAt,
		&i.Payload,
		&i.RunningKernelNevra,
		&i.BootTime,
		&i.HasProcessData,
		&i.CreatedAt,
	)
	return i, err
}

const insertHostSnapshot = `-- name: InsertHostSnapshot :one
INSERT INTO host_snapshots (
    id,
    host_id,
    collected_at,
    payload,
    running_kernel_nevra,
    boot_time,
    has_process_data
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, host_id, collected_at, received_at, payload, running_kernel_nevra, boot_time, has_process_data, created_at
`

type InsertHostSnapshotParams struct {
	ID                 string
	HostID             string
	CollectedAt        pgtype.Timestamptz
	Payload            []byte
	RunningKernelNevra string
	BootTime           pgtype.Timestamptz
	HasProcessData     bool
}

func (q *Queries) InsertHostSnapshot(ctx context.Context, arg InsertHostSnapshotParams) (HostSnapshot, error) {
	row := q.db.QueryRow(ctx, insertHostSnapshot,
		arg.ID,
		arg.HostID,
		arg.CollectedAt,
		arg.Payload,
		arg.RunningKernelNevra,
		arg.BootTime,
		arg.HasProcessData,
	)
	var i HostSnapshot
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.CollectedAt,
		&i.ReceivedAt,
		&i.Payload,
		&i.RunningKernelNevra,
		&i.BootTime,
		&i.HasProcessData,
		&i.CreatedAt,
	)
	return i, err
}

const upsertHostCurrentState = `-- name: UpsertHostCurrentState :exec
INSERT INTO host_current_state (
    host_id,
    snapshot_id,
    overall_action,
    critical_count,
    important_count,
    moderate_count,
    actionable_count,
    available_updates,
    needs_reboot,
    needs_restart,
    no_fix,
    unknown,
    updated_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    now()
)
ON CONFLICT (host_id) DO UPDATE SET
    snapshot_id = EXCLUDED.snapshot_id,
    overall_action = EXCLUDED.overall_action,
    critical_count = EXCLUDED.critical_count,
    important_count = EXCLUDED.important_count,
    moderate_count = EXCLUDED.moderate_count,
    actionable_count = EXCLUDED.actionable_count,
    available_updates = EXCLUDED.available_updates,
    needs_reboot = EXCLUDED.needs_reboot,
    needs_restart = EXCLUDED.needs_restart,
    no_fix = EXCLUDED.no_fix,
    unknown = EXCLUDED.unknown,
    updated_at = now()
`

type UpsertHostCurrentStateParams struct {
	HostID           string
	SnapshotID       string
	OverallAction    string
	CriticalCount    int32
	ImportantCount   int32
	ModerateCount    int32
	ActionableCount  int32
	AvailableUpdates int32
	NeedsReboot      int32
	NeedsRestart     int32
	NoFix            int32
	Unknown          int32
}

func (q *Queries) UpsertHostCurrentState(ctx context.Context, arg UpsertHostCurrentStateParams) error {
	_, err := q.db.Exec(ctx, upsertHostCurrentState,
		arg.HostID,
		arg.SnapshotID,
		arg.OverallAction,
		arg.CriticalCount,
		arg.ImportantCount,
		arg.ModerateCount,
		arg.ActionableCount,
		arg.AvailableUpdates,
		arg.NeedsReboot,
		arg.NeedsRestart,
		arg.NoFix,
		arg.Unknown,
	)
	return err
}
