// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hosts.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"go.patchbase.net/server/internal/utils"
)

const approveHostByID = `-- name: ApproveHostByID :one
UPDATE hosts
SET
    approval_status = 'approved',
    approved_at = now()
WHERE id = $1
RETURNING id, onboarding_mode, approval_status, approved_at, display_name, machine_id, hostname, ip_address, os_family, os_name, os_major, os_version, architecture, status, last_seen_at, last_advisory_check_at, first_seen_at, last_snapshot_id, created_at, updated_at, advisory_scope_key
`

func (q *Queries) ApproveHostByID(ctx context.Context, id string) (Host, error) {
	row := q.db.QueryRow(ctx, approveHostByID, id)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.OnboardingMode,
		&i.ApprovalStatus,
		&i.ApprovedAt,
		&i.DisplayName,
		&i.MachineID,
		&i.Hostname,
		&i.IpAddress,
		&i.OsFamily,
		&i.OsName,
		&i.OsMajor,
		&i.OsVersion,
		&i.Architecture,
		&i.Status,
		&i.LastSeenAt,
		&i.LastAdvisoryCheckAt,
		&i.FirstSeenAt,
		&i.LastSnapshotID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AdvisoryScopeKey,
	)
	return i, err
}

const clearHostLastSnapshotByID = `-- name: ClearHostLastSnapshotByID :exec
UPDATE hosts
SET last_snapshot_id = NULL
WHERE id = $1
`

func (q *Queries) ClearHostLastSnapshotByID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, clearHostLastSnapshotByID, id)
	return err
}

const deleteHostByID = `-- name: DeleteHostByID :one
DELETE FROM hosts
WHERE id = $1
RETURNING id, onboarding_mode, approval_status, approved_at, display_name, machine_id, hostname, ip_address, os_family, os_name, os_major, os_version, architecture, status, last_seen_at, last_advisory_check_at, first_seen_at, last_snapshot_id, created_at, updated_at, advisory_scope_key
`

func (q *Queries) DeleteHostByID(ctx context.Context, id string) (Host, error) {
	row := q.db.QueryRow(ctx, deleteHostByID, id)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.OnboardingMode,
		&i.ApprovalStatus,
		&i.ApprovedAt,
		&i.DisplayName,
		&i.MachineID,
		&i.Hostname,
		&i.IpAddress,
		&i.OsFamily,
		&i.OsName,
		&i.OsMajor,
		&i.OsVersion,
		&i.Architecture,
		&i.Status,
		&i.LastSeenAt,
		&i.LastAdvisoryCheckAt,
		&i.FirstSeenAt,
		&i.LastSnapshotID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AdvisoryScopeKey,
	)
	return i, err
}

const getDashboardOverview = `-- name: GetDashboardOverview :one
SELECT
    (SELECT COUNT(*) FROM hosts) AS total_hosts,
    (SELECT COUNT(*) FROM hosts h JOIN host_current_state hcs ON h.id = hcs.host_id WHERE hcs.overall_action <> 'none') AS need_attention,
    (SELECT COUNT(*) FROM hosts h JOIN host_current_state hcs ON h.id = hcs.host_id WHERE hcs.needs_reboot > 0) AS reboot_queue,
    (SELECT COUNT(*) FROM hosts h JOIN host_current_state hcs ON h.id = hcs.host_id WHERE hcs.overall_action = 'investigate') AS unknown_investigate,
    (SELECT COUNT(*) FROM advisories) AS total_advisories,
    (SELECT COUNT(*) FROM product_streams) AS total_streams
`

type GetDashboardOverviewRow struct {
	TotalHosts         int64
	NeedAttention      int64
	RebootQueue        int64
	UnknownInvestigate int64
	TotalAdvisories    int64
	TotalStreams       int64
}

func (q *Queries) GetDashboardOverview(ctx context.Context) (GetDashboardOverviewRow, error) {
	row := q.db.QueryRow(ctx, getDashboardOverview)
	var i GetDashboardOverviewRow
	err := row.Scan(
		&i.TotalHosts,
		&i.NeedAttention,
		&i.RebootQueue,
		&i.UnknownInvestigate,
		&i.TotalAdvisories,
		&i.TotalStreams,
	)
	return i, err
}

const getHostByID = `-- name: GetHostByID :one
SELECT id, onboarding_mode, approval_status, approved_at, display_name, machine_id, hostname, ip_address, os_family, os_name, os_major, os_version, architecture, status, last_seen_at, last_advisory_check_at, first_seen_at, last_snapshot_id, created_at, updated_at, advisory_scope_key
FROM hosts
WHERE id = $1
`

func (q *Queries) GetHostByID(ctx context.Context, id string) (Host, error) {
	row := q.db.QueryRow(ctx, getHostByID, id)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.OnboardingMode,
		&i.ApprovalStatus,
		&i.ApprovedAt,
		&i.DisplayName,
		&i.MachineID,
		&i.Hostname,
		&i.IpAddress,
		&i.OsFamily,
		&i.OsName,
		&i.OsMajor,
		&i.OsVersion,
		&i.Architecture,
		&i.Status,
		&i.LastSeenAt,
		&i.LastAdvisoryCheckAt,
		&i.FirstSeenAt,
		&i.LastSnapshotID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AdvisoryScopeKey,
	)
	return i, err
}

const getHostWithStateByID = `-- name: GetHostWithStateByID :one
SELECT
    h.id, h.onboarding_mode, h.approval_status, h.approved_at, h.display_name, h.machine_id, h.hostname, h.ip_address, h.os_family, h.os_name, h.os_major, h.os_version, h.architecture, h.status, h.last_seen_at, h.last_advisory_check_at, h.first_seen_at, h.last_snapshot_id, h.created_at, h.updated_at, h.advisory_scope_key,
    hp.pull_last_run_at,
    hp.pull_last_run_status,
    hp.pull_last_run_error,
    COALESCE(hcs.overall_action, 'none') AS overall_action,
    COALESCE(hcs.critical_count, 0) AS critical_count,
    COALESCE(hcs.important_count, 0) AS important_count,
    COALESCE(hcs.moderate_count, 0) AS moderate_count,
    COALESCE(hcs.actionable_count, 0) AS actionable_count,
    COALESCE(hcs.available_updates, 0) AS available_updates,
    COALESCE(hcs.needs_reboot, 0) AS needs_reboot,
    COALESCE(hcs.needs_restart, 0) AS needs_restart,
    COALESCE(hcs.no_fix, 0) AS no_fix,
    COALESCE(hcs.unknown, 0) AS unknown,
    hcs.updated_at AS state_updated_at
FROM hosts h
LEFT JOIN host_ssh_pull hp ON hp.host_id = h.id
LEFT JOIN host_current_state hcs ON hcs.host_id = h.id
WHERE h.id = $1
`

type GetHostWithStateByIDRow struct {
	Host              Host
	PullLastRunAt     pgtype.Timestamptz
	PullLastRunStatus utils.Option[string]
	PullLastRunError  utils.Option[string]
	OverallAction     string
	CriticalCount     int32
	ImportantCount    int32
	ModerateCount     int32
	ActionableCount   int32
	AvailableUpdates  int32
	NeedsReboot       int32
	NeedsRestart      int32
	NoFix             int32
	Unknown           int32
	StateUpdatedAt    pgtype.Timestamptz
}

func (q *Queries) GetHostWithStateByID(ctx context.Context, id string) (GetHostWithStateByIDRow, error) {
	row := q.db.QueryRow(ctx, getHostWithStateByID, id)
	var i GetHostWithStateByIDRow
	err := row.Scan(
		&i.Host.ID,
		&i.Host.OnboardingMode,
		&i.Host.ApprovalStatus,
		&i.Host.ApprovedAt,
		&i.Host.DisplayName,
		&i.Host.MachineID,
		&i.Host.Hostname,
		&i.Host.IpAddress,
		&i.Host.OsFamily,
		&i.Host.OsName,
		&i.Host.OsMajor,
		&i.Host.OsVersion,
		&i.Host.Architecture,
		&i.Host.Status,
		&i.Host.LastSeenAt,
		&i.Host.LastAdvisoryCheckAt,
		&i.Host.FirstSeenAt,
		&i.Host.LastSnapshotID,
		&i.Host.CreatedAt,
		&i.Host.UpdatedAt,
		&i.Host.AdvisoryScopeKey,
		&i.PullLastRunAt,
		&i.PullLastRunStatus,
		&i.PullLastRunError,
		&i.OverallAction,
		&i.CriticalCount,
		&i.ImportantCount,
		&i.ModerateCount,
		&i.ActionableCount,
		&i.AvailableUpdates,
		&i.NeedsReboot,
		&i.NeedsRestart,
		&i.NoFix,
		&i.Unknown,
		&i.StateUpdatedAt,
	)
	return i, err
}

const getSSHPullConfigByHostID = `-- name: GetSSHPullConfigByHostID :one
SELECT host_id, pull_ssh_user, pull_frequency_minutes, pull_public_key, pull_private_key, pull_last_run_at, pull_last_run_status, pull_last_run_error, onboarded, pull_hostname
FROM host_ssh_pull
WHERE host_id = $1
`

func (q *Queries) GetSSHPullConfigByHostID(ctx context.Context, hostID string) (HostSshPull, error) {
	row := q.db.QueryRow(ctx, getSSHPullConfigByHostID, hostID)
	var i HostSshPull
	err := row.Scan(
		&i.HostID,
		&i.PullSshUser,
		&i.PullFrequencyMinutes,
		&i.PullPublicKey,
		&i.PullPrivateKey,
		&i.PullLastRunAt,
		&i.PullLastRunStatus,
		&i.PullLastRunError,
		&i.Onboarded,
		&i.PullHostname,
	)
	return i, err
}

const insertAgentHost = `-- name: InsertAgentHost :one
INSERT INTO hosts (
    id,
    onboarding_mode,
    approval_status,
    display_name,
    machine_id,
    hostname,
    ip_address,
    os_name,
    os_version,
    architecture,
    status
)
VALUES (
    $1,
    'agent',
    'waiting_approval',
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    'active'
)
RETURNING id, onboarding_mode, approval_status, approved_at, display_name, machine_id, hostname, ip_address, os_family, os_name, os_major, os_version, architecture, status, last_seen_at, last_advisory_check_at, first_seen_at, last_snapshot_id, created_at, updated_at, advisory_scope_key
`

type InsertAgentHostParams struct {
	ID           string
	DisplayName  utils.Option[string]
	MachineID    utils.Option[string]
	Hostname     utils.Option[string]
	IpAddress    utils.Option[string]
	OsName       string
	OsVersion    string
	Architecture string
}

func (q *Queries) InsertAgentHost(ctx context.Context, arg InsertAgentHostParams) (Host, error) {
	row := q.db.QueryRow(ctx, insertAgentHost,
		arg.ID,
		arg.DisplayName,
		arg.MachineID,
		arg.Hostname,
		arg.IpAddress,
		arg.OsName,
		arg.OsVersion,
		arg.Architecture,
	)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.OnboardingMode,
		&i.ApprovalStatus,
		&i.ApprovedAt,
		&i.DisplayName,
		&i.MachineID,
		&i.Hostname,
		&i.IpAddress,
		&i.OsFamily,
		&i.OsName,
		&i.OsMajor,
		&i.OsVersion,
		&i.Architecture,
		&i.Status,
		&i.LastSeenAt,
		&i.LastAdvisoryCheckAt,
		&i.FirstSeenAt,
		&i.LastSnapshotID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AdvisoryScopeKey,
	)
	return i, err
}

const insertManualHost = `-- name: InsertManualHost :one
INSERT INTO hosts (
    id,
    onboarding_mode,
    approval_status,
    approved_at,
    display_name,
    hostname,
    status
)
VALUES (
    $1,
    'manual',
    'approved',
    now(),
    $2,
    $3,
    'active'
)
RETURNING id, onboarding_mode, approval_status, approved_at, display_name, machine_id, hostname, ip_address, os_family, os_name, os_major, os_version, architecture, status, last_seen_at, last_advisory_check_at, first_seen_at, last_snapshot_id, created_at, updated_at, advisory_scope_key
`

type InsertManualHostParams struct {
	ID          string
	DisplayName utils.Option[string]
	Hostname    utils.Option[string]
}

func (q *Queries) InsertManualHost(ctx context.Context, arg InsertManualHostParams) (Host, error) {
	row := q.db.QueryRow(ctx, insertManualHost, arg.ID, arg.DisplayName, arg.Hostname)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.OnboardingMode,
		&i.ApprovalStatus,
		&i.ApprovedAt,
		&i.DisplayName,
		&i.MachineID,
		&i.Hostname,
		&i.IpAddress,
		&i.OsFamily,
		&i.OsName,
		&i.OsMajor,
		&i.OsVersion,
		&i.Architecture,
		&i.Status,
		&i.LastSeenAt,
		&i.LastAdvisoryCheckAt,
		&i.FirstSeenAt,
		&i.LastSnapshotID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AdvisoryScopeKey,
	)
	return i, err
}

const insertSSHHost = `-- name: InsertSSHHost :one
WITH new_host AS (
    INSERT INTO hosts (
        id,
        onboarding_mode,
        approval_status,
        approved_at,
        display_name,
        hostname,
        ip_address,
        status
    )
    VALUES (
        $1,
        'ssh',
        'approved',
        now(),
        $2,
        $3,
        $4,
        'active'
    )
    RETURNING id, onboarding_mode, approval_status, approved_at, display_name, machine_id, hostname, ip_address, os_family, os_name, os_major, os_version, architecture, status, last_seen_at, last_advisory_check_at, first_seen_at, last_snapshot_id, created_at, updated_at, advisory_scope_key
),
new_ssh_pull AS (
    INSERT INTO host_ssh_pull (
        host_id,
        pull_hostname,
        pull_ssh_user,
        pull_frequency_minutes,
        pull_public_key,
        pull_private_key
    )
    VALUES (
        $1,
        $3,
        $5,
        $6,
        $7,
        $8
    )
    RETURNING host_id, pull_ssh_user, pull_frequency_minutes, pull_public_key, pull_private_key, pull_last_run_at, pull_last_run_status, pull_last_run_error, onboarded, pull_hostname
)
SELECT
    hosts.id, hosts.onboarding_mode, hosts.approval_status, hosts.approved_at, hosts.display_name, hosts.machine_id, hosts.hostname, hosts.ip_address, hosts.os_family, hosts.os_name, hosts.os_major, hosts.os_version, hosts.architecture, hosts.status, hosts.last_seen_at, hosts.last_advisory_check_at, hosts.first_seen_at, hosts.last_snapshot_id, hosts.created_at, hosts.updated_at, hosts.advisory_scope_key,
    nsp.pull_ssh_user,
    nsp.pull_hostname,
    nsp.pull_frequency_minutes,
    nsp.pull_public_key,
    nsp.pull_private_key,
    nsp.pull_last_run_at,
    nsp.pull_last_run_status,
    nsp.pull_last_run_error
FROM new_host hosts
JOIN new_ssh_pull nsp ON nsp.host_id = hosts.id
`

type InsertSSHHostParams struct {
	ID                   string
	DisplayName          utils.Option[string]
	Hostname             utils.Option[string]
	IpAddress            utils.Option[string]
	PullSshUser          utils.Option[string]
	PullFrequencyMinutes *int32
	PullPublicKey        utils.Option[string]
	PullPrivateKey       utils.Option[string]
}

type InsertSSHHostRow struct {
	Host                 Host
	PullSshUser          utils.Option[string]
	PullHostname         string
	PullFrequencyMinutes *int32
	PullPublicKey        utils.Option[string]
	PullPrivateKey       utils.Option[string]
	PullLastRunAt        pgtype.Timestamptz
	PullLastRunStatus    utils.Option[string]
	PullLastRunError     utils.Option[string]
}

func (q *Queries) InsertSSHHost(ctx context.Context, arg InsertSSHHostParams) (InsertSSHHostRow, error) {
	row := q.db.QueryRow(ctx, insertSSHHost,
		arg.ID,
		arg.DisplayName,
		arg.Hostname,
		arg.IpAddress,
		arg.PullSshUser,
		arg.PullFrequencyMinutes,
		arg.PullPublicKey,
		arg.PullPrivateKey,
	)
	var i InsertSSHHostRow
	err := row.Scan(
		&i.Host.ID,
		&i.Host.OnboardingMode,
		&i.Host.ApprovalStatus,
		&i.Host.ApprovedAt,
		&i.Host.DisplayName,
		&i.Host.MachineID,
		&i.Host.Hostname,
		&i.Host.IpAddress,
		&i.Host.OsFamily,
		&i.Host.OsName,
		&i.Host.OsMajor,
		&i.Host.OsVersion,
		&i.Host.Architecture,
		&i.Host.Status,
		&i.Host.LastSeenAt,
		&i.Host.LastAdvisoryCheckAt,
		&i.Host.FirstSeenAt,
		&i.Host.LastSnapshotID,
		&i.Host.CreatedAt,
		&i.Host.UpdatedAt,
		&i.Host.AdvisoryScopeKey,
		&i.PullSshUser,
		&i.PullHostname,
		&i.PullFrequencyMinutes,
		&i.PullPublicKey,
		&i.PullPrivateKey,
		&i.PullLastRunAt,
		&i.PullLastRunStatus,
		&i.PullLastRunError,
	)
	return i, err
}

const listApprovedSSHHosts = `-- name: ListApprovedSSHHosts :many
SELECT
    h.id,
    hp.pull_frequency_minutes
FROM hosts h
JOIN host_ssh_pull hp ON hp.host_id = h.id
WHERE h.onboarding_mode = 'ssh' AND h.approval_status = 'approved' AND hp.onboarded = true
`

type ListApprovedSSHHostsRow struct {
	ID                   string
	PullFrequencyMinutes *int32
}

func (q *Queries) ListApprovedSSHHosts(ctx context.Context) ([]ListApprovedSSHHostsRow, error) {
	rows, err := q.db.Query(ctx, listApprovedSSHHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApprovedSSHHostsRow
	for rows.Next() {
		var i ListApprovedSSHHostsRow
		if err := rows.Scan(&i.ID, &i.PullFrequencyMinutes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostsByAdvisoryScopeKey = `-- name: ListHostsByAdvisoryScopeKey :many
SELECT id, onboarding_mode, approval_status, approved_at, display_name, machine_id, hostname, ip_address, os_family, os_name, os_major, os_version, architecture, status, last_seen_at, last_advisory_check_at, first_seen_at, last_snapshot_id, created_at, updated_at, advisory_scope_key FROM hosts
WHERE advisory_scope_key = $1
`

func (q *Queries) ListHostsByAdvisoryScopeKey(ctx context.Context, advisoryScopeKey utils.Option[string]) ([]Host, error) {
	rows, err := q.db.Query(ctx, listHostsByAdvisoryScopeKey, advisoryScopeKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Host
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.OnboardingMode,
			&i.ApprovalStatus,
			&i.ApprovedAt,
			&i.DisplayName,
			&i.MachineID,
			&i.Hostname,
			&i.IpAddress,
			&i.OsFamily,
			&i.OsName,
			&i.OsMajor,
			&i.OsVersion,
			&i.Architecture,
			&i.Status,
			&i.LastSeenAt,
			&i.LastAdvisoryCheckAt,
			&i.FirstSeenAt,
			&i.LastSnapshotID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AdvisoryScopeKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostsWithState = `-- name: ListHostsWithState :many
SELECT
    h.id, h.onboarding_mode, h.approval_status, h.approved_at, h.display_name, h.machine_id, h.hostname, h.ip_address, h.os_family, h.os_name, h.os_major, h.os_version, h.architecture, h.status, h.last_seen_at, h.last_advisory_check_at, h.first_seen_at, h.last_snapshot_id, h.created_at, h.updated_at, h.advisory_scope_key,
    hp.pull_last_run_at,
    hp.pull_last_run_status,
    hp.pull_last_run_error,
    COALESCE(hcs.overall_action, 'none') AS overall_action,
    COALESCE(hcs.critical_count, 0) AS critical_count,
    COALESCE(hcs.important_count, 0) AS important_count,
    COALESCE(hcs.moderate_count, 0) AS moderate_count,
    COALESCE(hcs.actionable_count, 0) AS actionable_count,
    COALESCE(hcs.available_updates, 0) AS available_updates,
    COALESCE(hcs.needs_reboot, 0) AS needs_reboot,
    COALESCE(hcs.needs_restart, 0) AS needs_restart,
    COALESCE(hcs.no_fix, 0) AS no_fix,
    COALESCE(hcs.unknown, 0) AS unknown,
    hcs.updated_at AS state_updated_at
FROM hosts h
LEFT JOIN host_ssh_pull hp ON hp.host_id = h.id
LEFT JOIN host_current_state hcs ON hcs.host_id = h.id
ORDER BY
    CASE COALESCE(hcs.overall_action, 'none')
        WHEN 'reboot_host' THEN 0
        WHEN 'restart_service' THEN 1
        WHEN 'update_package' THEN 2
        WHEN 'investigate' THEN 3
        ELSE 4
    END,
    h.last_seen_at DESC NULLS LAST,
    h.hostname ASC,
    h.id ASC
`

type ListHostsWithStateRow struct {
	Host              Host
	PullLastRunAt     pgtype.Timestamptz
	PullLastRunStatus utils.Option[string]
	PullLastRunError  utils.Option[string]
	OverallAction     string
	CriticalCount     int32
	ImportantCount    int32
	ModerateCount     int32
	ActionableCount   int32
	AvailableUpdates  int32
	NeedsReboot       int32
	NeedsRestart      int32
	NoFix             int32
	Unknown           int32
	StateUpdatedAt    pgtype.Timestamptz
}

func (q *Queries) ListHostsWithState(ctx context.Context) ([]ListHostsWithStateRow, error) {
	rows, err := q.db.Query(ctx, listHostsWithState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHostsWithStateRow
	for rows.Next() {
		var i ListHostsWithStateRow
		if err := rows.Scan(
			&i.Host.ID,
			&i.Host.OnboardingMode,
			&i.Host.ApprovalStatus,
			&i.Host.ApprovedAt,
			&i.Host.DisplayName,
			&i.Host.MachineID,
			&i.Host.Hostname,
			&i.Host.IpAddress,
			&i.Host.OsFamily,
			&i.Host.OsName,
			&i.Host.OsMajor,
			&i.Host.OsVersion,
			&i.Host.Architecture,
			&i.Host.Status,
			&i.Host.LastSeenAt,
			&i.Host.LastAdvisoryCheckAt,
			&i.Host.FirstSeenAt,
			&i.Host.LastSnapshotID,
			&i.Host.CreatedAt,
			&i.Host.UpdatedAt,
			&i.Host.AdvisoryScopeKey,
			&i.PullLastRunAt,
			&i.PullLastRunStatus,
			&i.PullLastRunError,
			&i.OverallAction,
			&i.CriticalCount,
			&i.ImportantCount,
			&i.ModerateCount,
			&i.ActionableCount,
			&i.AvailableUpdates,
			&i.NeedsReboot,
			&i.NeedsRestart,
			&i.NoFix,
			&i.Unknown,
			&i.StateUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingHosts = `-- name: ListPendingHosts :many
SELECT id, onboarding_mode, approval_status, approved_at, display_name, machine_id, hostname, ip_address, os_family, os_name, os_major, os_version, architecture, status, last_seen_at, last_advisory_check_at, first_seen_at, last_snapshot_id, created_at, updated_at, advisory_scope_key
FROM hosts
WHERE approval_status = 'waiting_approval'
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListPendingHosts(ctx context.Context) ([]Host, error) {
	rows, err := q.db.Query(ctx, listPendingHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Host
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.OnboardingMode,
			&i.ApprovalStatus,
			&i.ApprovedAt,
			&i.DisplayName,
			&i.MachineID,
			&i.Hostname,
			&i.IpAddress,
			&i.OsFamily,
			&i.OsName,
			&i.OsMajor,
			&i.OsVersion,
			&i.Architecture,
			&i.Status,
			&i.LastSeenAt,
			&i.LastAdvisoryCheckAt,
			&i.FirstSeenAt,
			&i.LastSnapshotID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AdvisoryScopeKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSSHPullOnboarded = `-- name: SetSSHPullOnboarded :exec
UPDATE host_ssh_pull
SET onboarded = $2
WHERE host_id = $1
`

type SetSSHPullOnboardedParams struct {
	HostID    string
	Onboarded bool
}

func (q *Queries) SetSSHPullOnboarded(ctx context.Context, arg SetSSHPullOnboardedParams) error {
	_, err := q.db.Exec(ctx, setSSHPullOnboarded, arg.HostID, arg.Onboarded)
	return err
}

const updateHostAdvisoryScopeKey = `-- name: UpdateHostAdvisoryScopeKey :exec
UPDATE hosts
SET advisory_scope_key = $2
WHERE id = $1
`

type UpdateHostAdvisoryScopeKeyParams struct {
	ID               string
	AdvisoryScopeKey utils.Option[string]
}

func (q *Queries) UpdateHostAdvisoryScopeKey(ctx context.Context, arg UpdateHostAdvisoryScopeKeyParams) error {
	_, err := q.db.Exec(ctx, updateHostAdvisoryScopeKey, arg.ID, arg.AdvisoryScopeKey)
	return err
}

const updateHostFromSnapshot = `-- name: UpdateHostFromSnapshot :one
UPDATE hosts
SET
    machine_id = $2,
    hostname = $3,
    ip_address = $4,
    os_family = $5,
    os_name = $6,
    os_major = $7,
    os_version = $8,
    architecture = $9,
    status = 'active',
    last_seen_at = $10,
    last_advisory_check_at = $10,
    last_snapshot_id = $11
WHERE id = $1
RETURNING id, onboarding_mode, approval_status, approved_at, display_name, machine_id, hostname, ip_address, os_family, os_name, os_major, os_version, architecture, status, last_seen_at, last_advisory_check_at, first_seen_at, last_snapshot_id, created_at, updated_at, advisory_scope_key
`

type UpdateHostFromSnapshotParams struct {
	ID             string
	MachineID      utils.Option[string]
	Hostname       utils.Option[string]
	IpAddress      utils.Option[string]
	OsFamily       string
	OsName         string
	OsMajor        int32
	OsVersion      string
	Architecture   string
	LastSeenAt     pgtype.Timestamptz
	LastSnapshotID utils.Option[string]
}

func (q *Queries) UpdateHostFromSnapshot(ctx context.Context, arg UpdateHostFromSnapshotParams) (Host, error) {
	row := q.db.QueryRow(ctx, updateHostFromSnapshot,
		arg.ID,
		arg.MachineID,
		arg.Hostname,
		arg.IpAddress,
		arg.OsFamily,
		arg.OsName,
		arg.OsMajor,
		arg.OsVersion,
		arg.Architecture,
		arg.LastSeenAt,
		arg.LastSnapshotID,
	)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.OnboardingMode,
		&i.ApprovalStatus,
		&i.ApprovedAt,
		&i.DisplayName,
		&i.MachineID,
		&i.Hostname,
		&i.IpAddress,
		&i.OsFamily,
		&i.OsName,
		&i.OsMajor,
		&i.OsVersion,
		&i.Architecture,
		&i.Status,
		&i.LastSeenAt,
		&i.LastAdvisoryCheckAt,
		&i.FirstSeenAt,
		&i.LastSnapshotID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AdvisoryScopeKey,
	)
	return i, err
}

const updateSSHPullRun = `-- name: UpdateSSHPullRun :exec
WITH updated_pull AS (
    UPDATE host_ssh_pull
    SET
        pull_last_run_at = $1,
        pull_last_run_status = $12,
        pull_last_run_error = $13
    WHERE host_id = $11
)
UPDATE hosts
SET
    last_advisory_check_at = $1,
    last_snapshot_id = COALESCE($2, last_snapshot_id),
    machine_id = COALESCE($3, machine_id),
    hostname = COALESCE($4, hostname),
    ip_address = COALESCE($5, ip_address),
    os_family = CASE WHEN $6::text <> '' AND $6::text <> 'unknown' THEN $6 ELSE os_family END,
    os_name = CASE WHEN $7::text <> '' AND $7::text <> 'Unknown' THEN $7 ELSE os_name END,
    os_major = CASE WHEN $8::integer <> 0 THEN $8 ELSE os_major END,
    os_version = CASE WHEN $9::text <> '' AND $9::text <> 'unknown' THEN $9 ELSE os_version END,
    architecture = CASE WHEN $10::text <> '' AND $10::text <> 'unknown' THEN $10 ELSE architecture END,
    last_seen_at = COALESCE($1, last_seen_at)
WHERE id = $11
`

type UpdateSSHPullRunParams struct {
	PullLastRunAt     pgtype.Timestamptz
	LastSnapshotID    utils.Option[string]
	MachineID         utils.Option[string]
	Hostname          utils.Option[string]
	IpAddress         utils.Option[string]
	OsFamily          string
	OsName            string
	OsMajor           int32
	OsVersion         string
	Architecture      string
	ID                string
	PullLastRunStatus utils.Option[string]
	PullLastRunError  utils.Option[string]
}

func (q *Queries) UpdateSSHPullRun(ctx context.Context, arg UpdateSSHPullRunParams) error {
	_, err := q.db.Exec(ctx, updateSSHPullRun,
		arg.PullLastRunAt,
		arg.LastSnapshotID,
		arg.MachineID,
		arg.Hostname,
		arg.IpAddress,
		arg.OsFamily,
		arg.OsName,
		arg.OsMajor,
		arg.OsVersion,
		arg.Architecture,
		arg.ID,
		arg.PullLastRunStatus,
		arg.PullLastRunError,
	)
	return err
}
