// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sql

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
	"go.patchbase.net/server/internal/utils"
)

type RiverJobState string

const (
	RiverJobStateAvailable RiverJobState = "available"
	RiverJobStateCancelled RiverJobState = "cancelled"
	RiverJobStateCompleted RiverJobState = "completed"
	RiverJobStateDiscarded RiverJobState = "discarded"
	RiverJobStatePending   RiverJobState = "pending"
	RiverJobStateRetryable RiverJobState = "retryable"
	RiverJobStateRunning   RiverJobState = "running"
	RiverJobStateScheduled RiverJobState = "scheduled"
)

func (e *RiverJobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiverJobState(s)
	case string:
		*e = RiverJobState(s)
	default:
		return fmt.Errorf("unsupported scan type for RiverJobState: %T", src)
	}
	return nil
}

type NullRiverJobState struct {
	RiverJobState RiverJobState
	Valid         bool // Valid is true if RiverJobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiverJobState) Scan(value interface{}) error {
	if value == nil {
		ns.RiverJobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiverJobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiverJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiverJobState), nil
}

type Advisory struct {
	ID           string
	SourceSystem string
	RawSourceID  string
	SourceUrl    utils.Option[string]
	Vendor       string
	AdvisoryType string
	Severity     utils.Option[string]
	Summary      utils.Option[string]
	Description  utils.Option[string]
	PublishedAt  utils.Option[string]
	UpdatedAt    utils.Option[string]
	EvidenceTier string
	IsSecurity   bool
}

type AdvisoryProductStream struct {
	AdvisoryID      string
	ProductStreamID string
}

type AdvisoryReference struct {
	ID             string
	AdvisoryID     string
	RefType        string
	RefValue       string
	SeverityVendor utils.Option[string]
	SeverityCvss   *float64
	Title          utils.Option[string]
	Url            utils.Option[string]
}

type AdvisoryScope struct {
	ScopeKey      string
	Status        string
	LastSyncAt    pgtype.Timestamptz
	LastSuccessAt pgtype.Timestamptz
	LastError     utils.Option[string]
	AdvisoryCount int32
	Sha256        utils.Option[string]
	SizeBytes     int64
	LocalPath     utils.Option[string]
	NextRefreshAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type AffectedPackageRule struct {
	ID                string
	AdvisoryID        string
	ProductStreamID   string
	PackageName       string
	SourceRpm         utils.Option[string]
	Arch              utils.Option[string]
	EpochConstraint   utils.Option[string]
	VersionConstraint utils.Option[string]
	ReleaseConstraint utils.Option[string]
	RpmEvrRule        utils.Option[string]
	Context           string
	EvidenceTier      string
}

type DecisionRecord struct {
	ID                 string
	HostID             string
	SnapshotID         string
	AdvisoryID         string
	InstalledPackageID utils.Option[string]
	ProductStreamID    utils.Option[string]
	PackageName        string
	InstalledNevra     utils.Option[string]
	FixedNevra         utils.Option[string]
	Status             string
	Action             string
	Severity           utils.Option[string]
	EvidenceTier       string
	ReasonCode         string
	ReasonText         utils.Option[string]
	ComputedAt         string
}

type FixedPackage struct {
	ID              string
	AdvisoryID      string
	ProductStreamID string
	PackageName     string
	Epoch           int32
	Version         string
	Release         string
	Arch            utils.Option[string]
	Nevra           string
	SourceRpm       utils.Option[string]
	RepoFamily      utils.Option[string]
	EvidenceTier    string
}

type GooseDbVersion struct {
	ID        int32
	VersionID int64
	IsApplied bool
	Tstamp    pgtype.Timestamp
}

type Host struct {
	ID                  string
	OnboardingMode      string
	ApprovalStatus      string
	ApprovedAt          pgtype.Timestamptz
	DisplayName         utils.Option[string]
	MachineID           utils.Option[string]
	Hostname            utils.Option[string]
	IpAddress           utils.Option[string]
	OsFamily            string
	OsName              string
	OsMajor             int32
	OsVersion           string
	Architecture        string
	Status              string
	LastSeenAt          pgtype.Timestamptz
	LastAdvisoryCheckAt pgtype.Timestamptz
	FirstSeenAt         pgtype.Timestamptz
	LastSnapshotID      utils.Option[string]
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	AdvisoryScopeKey    utils.Option[string]
}

type HostAccessToken struct {
	ID         string
	HostID     string
	TokenHash  string
	CreatedAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
}

type HostCurrentState struct {
	HostID           string
	SnapshotID       string
	OverallAction    string
	CriticalCount    int32
	ImportantCount   int32
	ModerateCount    int32
	ActionableCount  int32
	AvailableUpdates int32
	NeedsReboot      int32
	NeedsRestart     int32
	NoFix            int32
	Unknown          int32
	UpdatedAt        pgtype.Timestamptz
}

type HostSnapshot struct {
	ID                 string
	HostID             string
	CollectedAt        pgtype.Timestamptz
	ReceivedAt         pgtype.Timestamptz
	Payload            []byte
	RunningKernelNevra string
	BootTime           pgtype.Timestamptz
	HasProcessData     bool
	CreatedAt          pgtype.Timestamptz
}

type HostSshPull struct {
	HostID               string
	PullSshUser          utils.Option[string]
	PullFrequencyMinutes *int32
	PullPublicKey        utils.Option[string]
	PullPrivateKey       utils.Option[string]
	PullLastRunAt        pgtype.Timestamptz
	PullLastRunStatus    utils.Option[string]
	PullLastRunError     utils.Option[string]
	Onboarded            bool
}

type HostSshPullJob struct {
	ID          string
	HostID      string
	Status      string
	StartedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
	Error       utils.Option[string]
}

type ProductStream struct {
	ID            string
	Vendor        string
	DistroFamily  string
	DistroName    string
	MajorVersion  int32
	MinorVersion  utils.Option[string]
	Architecture  utils.Option[string]
	RepoFamily    string
	RepoIDPattern utils.Option[string]
	Cpe           utils.Option[string]
	Status        string
}

type RegistrationToken struct {
	ID              string
	Name            string
	TokenHash       string
	CreatedByUserID string
	CreatedAt       pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
	LastUsedAt      pgtype.Timestamptz
}

type RiverClient struct {
	ID        string
	CreatedAt pgtype.Timestamptz
	Metadata  []byte
	PausedAt  pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type RiverClientQueue struct {
	RiverClientID    string
	Name             string
	CreatedAt        pgtype.Timestamptz
	MaxWorkers       int64
	Metadata         []byte
	NumJobsCompleted int64
	NumJobsRunning   int64
	UpdatedAt        pgtype.Timestamptz
}

type RiverJob struct {
	ID           int64
	State        RiverJobState
	Attempt      int16
	MaxAttempts  int16
	AttemptedAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	FinalizedAt  pgtype.Timestamptz
	ScheduledAt  pgtype.Timestamptz
	Priority     int16
	Args         []byte
	AttemptedBy  []string
	Errors       [][]byte
	Kind         string
	Metadata     []byte
	Queue        string
	Tags         []string
	UniqueKey    []byte
	UniqueStates pgtype.Bits
}

type RiverLeader struct {
	ElectedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	LeaderID  string
	Name      string
}

type RiverMigration struct {
	Line      string
	Version   int64
	CreatedAt pgtype.Timestamptz
}

type RiverQueue struct {
	Name      string
	CreatedAt pgtype.Timestamptz
	Metadata  []byte
	PausedAt  pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Setting struct {
	Key       string
	Value     []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID                    string
	Email                 string
	Name                  string
	PasswordHash          string
	IsAdmin               bool
	PasswordResetRequired bool
	LastLoginAt           pgtype.Timestamptz
	ArchivedAt            pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}
