// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sql

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
	"go.patchbase.net/server/internal/utils"
)

type RiverJobState string

const (
	RiverJobStateAvailable RiverJobState = "available"
	RiverJobStateCancelled RiverJobState = "cancelled"
	RiverJobStateCompleted RiverJobState = "completed"
	RiverJobStateDiscarded RiverJobState = "discarded"
	RiverJobStatePending   RiverJobState = "pending"
	RiverJobStateRetryable RiverJobState = "retryable"
	RiverJobStateRunning   RiverJobState = "running"
	RiverJobStateScheduled RiverJobState = "scheduled"
)

func (e *RiverJobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiverJobState(s)
	case string:
		*e = RiverJobState(s)
	default:
		return fmt.Errorf("unsupported scan type for RiverJobState: %T", src)
	}
	return nil
}

type NullRiverJobState struct {
	RiverJobState RiverJobState
	Valid         bool // Valid is true if RiverJobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiverJobState) Scan(value interface{}) error {
	if value == nil {
		ns.RiverJobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiverJobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiverJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiverJobState), nil
}

type RuntimeStatus string

const (
	RuntimeStatusPending            RuntimeStatus = "pending"
	RuntimeStatusActive             RuntimeStatus = "active"
	RuntimeStatusDisabled           RuntimeStatus = "disabled"
	RuntimeStatusVerificationFailed RuntimeStatus = "verification_failed"
)

func (e *RuntimeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RuntimeStatus(s)
	case string:
		*e = RuntimeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RuntimeStatus: %T", src)
	}
	return nil
}

type NullRuntimeStatus struct {
	RuntimeStatus RuntimeStatus
	Valid         bool // Valid is true if RuntimeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRuntimeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RuntimeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RuntimeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRuntimeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RuntimeStatus), nil
}

type GooseDbVersion struct {
	ID        int32
	VersionID int64
	IsApplied bool
	Tstamp    pgtype.Timestamp
}

type RiverClient struct {
	ID        string
	CreatedAt pgtype.Timestamptz
	Metadata  []byte
	PausedAt  pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type RiverClientQueue struct {
	RiverClientID    string
	Name             string
	CreatedAt        pgtype.Timestamptz
	MaxWorkers       int64
	Metadata         []byte
	NumJobsCompleted int64
	NumJobsRunning   int64
	UpdatedAt        pgtype.Timestamptz
}

type RiverJob struct {
	ID           int64
	State        RiverJobState
	Attempt      int16
	MaxAttempts  int16
	AttemptedAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	FinalizedAt  pgtype.Timestamptz
	ScheduledAt  pgtype.Timestamptz
	Priority     int16
	Args         []byte
	AttemptedBy  []string
	Errors       [][]byte
	Kind         string
	Metadata     []byte
	Queue        string
	Tags         []string
	UniqueKey    []byte
	UniqueStates pgtype.Bits
}

type RiverLeader struct {
	ElectedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	LeaderID  string
	Name      string
}

type RiverMigration struct {
	Line      string
	Version   int64
	CreatedAt pgtype.Timestamptz
}

type RiverQueue struct {
	Name      string
	CreatedAt pgtype.Timestamptz
	Metadata  []byte
	PausedAt  pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Runtime struct {
	ID             string
	Name           string
	ImageRef       string
	Status         RuntimeStatus
	SdkVersion     utils.Option[string]
	Capabilities   []string
	DeclaredLimits []byte
	Metadata       []byte
	Description    utils.Option[string]
	LastVerifiedAt pgtype.Timestamptz
	ArchivedAt     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Setting struct {
	Key       string
	Value     []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID                    string
	Email                 string
	Name                  string
	PasswordHash          string
	IsAdmin               bool
	PasswordResetRequired bool
	LastLoginAt           pgtype.Timestamptz
	ArchivedAt            pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}
