// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_streams.sql

package sql

import (
	"context"

	"go.patchbase.net/server/internal/utils"
)

const deleteProductStreamsByIDs = `-- name: DeleteProductStreamsByIDs :exec
DELETE FROM product_streams
WHERE id = ANY($1::text[])
`

func (q *Queries) DeleteProductStreamsByIDs(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteProductStreamsByIDs, dollar_1)
	return err
}

const listProductStreamIDsByVendorAndVersion = `-- name: ListProductStreamIDsByVendorAndVersion :many
SELECT id FROM product_streams
WHERE vendor = $1 AND major_version = $2
`

type ListProductStreamIDsByVendorAndVersionParams struct {
	Vendor       string
	MajorVersion int32
}

func (q *Queries) ListProductStreamIDsByVendorAndVersion(ctx context.Context, arg ListProductStreamIDsByVendorAndVersionParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listProductStreamIDsByVendorAndVersion, arg.Vendor, arg.MajorVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductStreams = `-- name: ListProductStreams :many
SELECT id, vendor, distro_family, distro_name, major_version, minor_version, architecture, repo_family, repo_id_pattern, cpe, status FROM product_streams
`

func (q *Queries) ListProductStreams(ctx context.Context) ([]ProductStream, error) {
	rows, err := q.db.Query(ctx, listProductStreams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductStream
	for rows.Next() {
		var i ProductStream
		if err := rows.Scan(
			&i.ID,
			&i.Vendor,
			&i.DistroFamily,
			&i.DistroName,
			&i.MajorVersion,
			&i.MinorVersion,
			&i.Architecture,
			&i.RepoFamily,
			&i.RepoIDPattern,
			&i.Cpe,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProductStream = `-- name: UpsertProductStream :exec
INSERT INTO product_streams (
    id, vendor, distro_family, distro_name, major_version, minor_version, architecture, repo_family, repo_id_pattern, cpe, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (id) DO UPDATE SET
    vendor = EXCLUDED.vendor,
    distro_family = EXCLUDED.distro_family,
    distro_name = EXCLUDED.distro_name,
    major_version = EXCLUDED.major_version,
    minor_version = EXCLUDED.minor_version,
    architecture = EXCLUDED.architecture,
    repo_family = EXCLUDED.repo_family,
    repo_id_pattern = EXCLUDED.repo_id_pattern,
    cpe = EXCLUDED.cpe,
    status = EXCLUDED.status
`

type UpsertProductStreamParams struct {
	ID            string
	Vendor        string
	DistroFamily  string
	DistroName    string
	MajorVersion  int32
	MinorVersion  utils.Option[string]
	Architecture  utils.Option[string]
	RepoFamily    string
	RepoIDPattern utils.Option[string]
	Cpe           utils.Option[string]
	Status        string
}

func (q *Queries) UpsertProductStream(ctx context.Context, arg UpsertProductStreamParams) error {
	_, err := q.db.Exec(ctx, upsertProductStream,
		arg.ID,
		arg.Vendor,
		arg.DistroFamily,
		arg.DistroName,
		arg.MajorVersion,
		arg.MinorVersion,
		arg.Architecture,
		arg.RepoFamily,
		arg.RepoIDPattern,
		arg.Cpe,
		arg.Status,
	)
	return err
}
