// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sql

import (
	"context"
)

type Querier interface {
	CompleteInitialSetupForUser(ctx context.Context, arg CompleteInitialSetupForUserParams) (User, error)
	CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (User, error)
	CreateSetting(ctx context.Context, arg CreateSettingParams) (Setting, error)
	CreateSettingIfAbsent(ctx context.Context, arg CreateSettingIfAbsentParams) error
	GetAdminUser(ctx context.Context) (User, error)
	GetSetting(ctx context.Context, key string) (Setting, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) (Setting, error)
}

var _ Querier = (*Queries)(nil)
