// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registration_tokens.sql

package sql

import (
	"context"
)

const getActiveRegistrationTokenByHash = `-- name: GetActiveRegistrationTokenByHash :one
SELECT id, name, token_hash, created_by_user_id, created_at, revoked_at, last_used_at, auto_approve
FROM registration_tokens
WHERE token_hash = $1
  AND revoked_at IS NULL
LIMIT 1
`

func (q *Queries) GetActiveRegistrationTokenByHash(ctx context.Context, tokenHash string) (RegistrationToken, error) {
	row := q.db.QueryRow(ctx, getActiveRegistrationTokenByHash, tokenHash)
	var i RegistrationToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.AutoApprove,
	)
	return i, err
}

const insertRegistrationToken = `-- name: InsertRegistrationToken :one
INSERT INTO registration_tokens (
    id,
    name,
    token_hash,
    created_by_user_id,
    auto_approve
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, name, token_hash, created_by_user_id, created_at, revoked_at, last_used_at, auto_approve
`

type InsertRegistrationTokenParams struct {
	ID              string
	Name            string
	TokenHash       string
	CreatedByUserID string
	AutoApprove     bool
}

func (q *Queries) InsertRegistrationToken(ctx context.Context, arg InsertRegistrationTokenParams) (RegistrationToken, error) {
	row := q.db.QueryRow(ctx, insertRegistrationToken,
		arg.ID,
		arg.Name,
		arg.TokenHash,
		arg.CreatedByUserID,
		arg.AutoApprove,
	)
	var i RegistrationToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.AutoApprove,
	)
	return i, err
}

const listRegistrationTokens = `-- name: ListRegistrationTokens :many
SELECT id, name, token_hash, created_by_user_id, created_at, revoked_at, last_used_at, auto_approve
FROM registration_tokens
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListRegistrationTokens(ctx context.Context) ([]RegistrationToken, error) {
	rows, err := q.db.Query(ctx, listRegistrationTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegistrationToken
	for rows.Next() {
		var i RegistrationToken
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenHash,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.AutoApprove,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRegistrationToken = `-- name: RevokeRegistrationToken :one
UPDATE registration_tokens
SET revoked_at = now()
WHERE id = $1
  AND revoked_at IS NULL
RETURNING id, name, token_hash, created_by_user_id, created_at, revoked_at, last_used_at, auto_approve
`

func (q *Queries) RevokeRegistrationToken(ctx context.Context, id string) (RegistrationToken, error) {
	row := q.db.QueryRow(ctx, revokeRegistrationToken, id)
	var i RegistrationToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.AutoApprove,
	)
	return i, err
}

const touchRegistrationTokenLastUsed = `-- name: TouchRegistrationTokenLastUsed :exec
UPDATE registration_tokens
SET last_used_at = now()
WHERE id = $1
`

func (q *Queries) TouchRegistrationTokenLastUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchRegistrationTokenLastUsed, id)
	return err
}
