// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package sql

import (
	"context"
)

const createSetting = `-- name: CreateSetting :one
INSERT INTO settings (
    key,
    value
)
VALUES (
    $1,
    $2
)
RETURNING
    key,
    value,
    created_at,
    updated_at
`

type CreateSettingParams struct {
	Key   string
	Value []byte
}

func (q *Queries) CreateSetting(ctx context.Context, arg CreateSettingParams) (Setting, error) {
	row := q.db.QueryRow(ctx, createSetting, arg.Key, arg.Value)
	var i Setting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSettingIfAbsent = `-- name: CreateSettingIfAbsent :exec
INSERT INTO settings (
    key,
    value
)
VALUES (
    $1,
    $2
)
ON CONFLICT (key) DO NOTHING
`

type CreateSettingIfAbsentParams struct {
	Key   string
	Value []byte
}

func (q *Queries) CreateSettingIfAbsent(ctx context.Context, arg CreateSettingIfAbsentParams) error {
	_, err := q.db.Exec(ctx, createSettingIfAbsent, arg.Key, arg.Value)
	return err
}

const getSetting = `-- name: GetSetting :one
SELECT
    key,
    value,
    created_at,
    updated_at
FROM settings
WHERE key = $1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (Setting, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var i Setting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSetting = `-- name: UpsertSetting :one
INSERT INTO settings (
    key,
    value
)
VALUES (
    $1,
    $2
)
ON CONFLICT (key)
DO UPDATE SET
    value = EXCLUDED.value
RETURNING
    key,
    value,
    created_at,
    updated_at
`

type UpsertSettingParams struct {
	Key   string
	Value []byte
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) (Setting, error) {
	row := q.db.QueryRow(ctx, upsertSetting, arg.Key, arg.Value)
	var i Setting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
