// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sql

import (
	"context"
)

const completeInitialSetupForUser = `-- name: CompleteInitialSetupForUser :one
UPDATE users
SET
    email = $2,
    name = $3,
    password_hash = $4,
    password_reset_required = FALSE
WHERE id = $1
  AND archived_at IS NULL
RETURNING id, email, name, password_hash, is_admin, password_reset_required, last_login_at, archived_at, created_at, updated_at
`

type CompleteInitialSetupForUserParams struct {
	ID           string
	Email        string
	Name         string
	PasswordHash string
}

func (q *Queries) CompleteInitialSetupForUser(ctx context.Context, arg CompleteInitialSetupForUserParams) (User, error) {
	row := q.db.QueryRow(ctx, completeInitialSetupForUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.PasswordResetRequired,
		&i.LastLoginAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO users (
    id,
    email,
    name,
    password_hash,
    is_admin,
    password_reset_required
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    TRUE,
    TRUE
)
RETURNING id, email, name, password_hash, is_admin, password_reset_required, last_login_at, archived_at, created_at, updated_at
`

type CreateAdminUserParams struct {
	ID           string
	Email        string
	Name         string
	PasswordHash string
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createAdminUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.PasswordResetRequired,
		&i.LastLoginAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminUser = `-- name: GetAdminUser :one
SELECT id, email, name, password_hash, is_admin, password_reset_required, last_login_at, archived_at, created_at, updated_at
FROM users
WHERE is_admin = TRUE
  AND archived_at IS NULL
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetAdminUser(ctx context.Context) (User, error) {
	row := q.db.QueryRow(ctx, getAdminUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.PasswordResetRequired,
		&i.LastLoginAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, is_admin, password_reset_required, last_login_at, archived_at, created_at, updated_at
FROM users
WHERE email = $1
  AND archived_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.PasswordResetRequired,
		&i.LastLoginAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, is_admin, password_reset_required, last_login_at, archived_at, created_at, updated_at
FROM users
WHERE id = $1
  AND archived_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.PasswordResetRequired,
		&i.LastLoginAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserEmail = `-- name: UpdateUserEmail :one
UPDATE users
SET email = $2
WHERE id = $1
  AND archived_at IS NULL
RETURNING id, email, name, password_hash, is_admin, password_reset_required, last_login_at, archived_at, created_at, updated_at
`

type UpdateUserEmailParams struct {
	ID    string
	Email string
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserEmail, arg.ID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.PasswordResetRequired,
		&i.LastLoginAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET
    password_hash = $2,
    password_reset_required = FALSE
WHERE id = $1
  AND archived_at IS NULL
RETURNING id, email, name, password_hash, is_admin, password_reset_required, last_login_at, archived_at, created_at, updated_at
`

type UpdateUserPasswordParams struct {
	ID           string
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.PasswordResetRequired,
		&i.LastLoginAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
