package utils

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"reflect"

	"gopkg.in/yaml.v3"
)

// Option represents an optional value.
// It can either be Some(value) or None.
// This is similar to Rust's Option type.
// It is a generic type that can hold any type T.
// Usage:
//
//	opt := Some(42)
//
//	if opt.IsSome() {
//	   value := opt.Unwrap()
//	  fmt.Println(value) // prints 42
//	} else {
//
//	  fmt.Println("No value")
//	}
//
// opt2 := None[int]()
// fmt.Println(opt2.IsNone()) // prints true
// value2 := opt2.UnwrapOr(42)
// fmt.Println(value2) // prints 42
type Option[T any] struct {
	value   T
	present bool
}

// ValidatorValue is used by go-playground/validator.
func (o Option[T]) ValidatorValue() any {
	if !o.present {
		return nil
	}
	return o.value
}

// Some creates an Option with a value.
func Some[T any](value T) Option[T] {
	return Option[T]{value: value, present: true}
}

// None creates an Option with no value.
func None[T any]() Option[T] {
	var zero T
	return Option[T]{value: zero, present: false}
}

// FromPtr creates an Option from a pointer.
// If the pointer is nil, it returns None.
// Otherwise, it returns Some with the dereferenced value.
func FromPtr[T any](p *T) Option[T] {
	if p == nil {
		return None[T]()
	}
	return Some(*p)
}

// Equal checks if two Option values are equal.
// Two Option values are equal if they are both None or if they are both Some and their contained values are equal.
// Example:
// opt1 := Some(42)
// opt2 := Some(42)
// areEqual := Equal(opt1, opt2) // areEqual is true
// opt3 := None[int]()
// opt4 := None[int]()
// areEqual2 := Equal(opt3, opt4) // areEqual2 is true
// opt5 := Some(42)
// opt6 := Some(43)
// areEqual3 := Equal(opt5, opt6) // areEqual3 is false
func Equal[T comparable](a, b Option[T]) bool {
	if a.present != b.present {
		return false
	}
	if !a.present {
		return true
	}
	return a.value == b.value
}

// IsZero returns true if the Option is None.
// Used for zero value checks.
func (o Option[T]) IsZero() bool {
	return o.IsNone()
}

// IsPresent returns true if the Option is Some.
func (o Option[T]) IsPresent() bool {
	return o.present
}

// IsNone returns true if the Option is None.
func (o Option[T]) IsNone() bool {
	return !o.present
}

// IsNoneOrDefault returns true if the Option is None or if the contained value is the zero value for its type.
func (o Option[T]) IsNoneOrDefault() bool {
	if !o.present {
		return true
	}
	return reflect.ValueOf(&o.value).Elem().IsZero()
}

// Get returns the contained value and a boolean indicating presence.
// If the Option is None, the boolean will be false and the value will be the zero value of T.
// Example:
// opt := Some(42)
// value, ok := opt.Get() // value is 42, ok is true
// opt2 := None[int]()
// value2, ok2 := opt2.Get() // value2 is 0, ok2 is false
// fmt.Println(value, ok)   // prints: 42 true
// fmt.Println(value2, ok2) // prints: 0 false
// Note: Unlike Unwrap, Get does not panic on None.
// This makes it safer to use when the presence of a value is uncertain.
// It is recommended to use Get when you want to handle both cases without panicking.
func (o Option[T]) Get() (T, bool) {
	return o.value, o.present
}

func (o *Option[T]) Scan(src any) error {
	if src == nil {
		return nil
	}
	v := &o.value

	scanner, ok := (any)(v).(sql.Scanner)
	if ok {
		err := scanner.Scan(src)
		if err != nil {
			return err
		}
		o.present = true
		return nil
	}
	// Database value comes as int64. actual int type is generated by sqlc from the DB. This should be safe.
	switch any(o.value).(type) {
	case int32:
		if val, ok := src.(int64); ok {
			o.value = any(int32(val)).(T) // nolint: gosec
			o.present = true
			return nil
		}
	case int16:
		if val, ok := src.(int64); ok {
			o.value = any(int16(val)).(T) // nolint: gosec
			o.present = true
			return nil
		}
		if val, ok := src.(int32); ok {
			o.value = any(int16(val)).(T) // nolint: gosec
			o.present = true
			return nil
		}
	case int8:
		if val, ok := src.(int64); ok {
			o.value = any(int8(val)).(T) // nolint: gosec
			o.present = true
			return nil
		}
		if val, ok := src.(int32); ok {
			o.value = any(int8(val)).(T) // nolint: gosec
			o.present = true
			return nil
		}
		if val, ok := src.(int16); ok {
			o.value = any(int8(val)).(T) // nolint: gosec
			o.present = true
			return nil
		}
	}
	if reflect.TypeOf(src) == reflect.TypeOf(o.value) {
		o.value = src.(T)
		o.present = true
		return nil
	}
	return fmt.Errorf("unable to scan value of type %T into Option[%T]", src, o.value)
}

func (o Option[T]) Value() (driver.Value, error) {
	if !o.present {
		return nil, nil
	}
	valuer, ok := (any)(&o.value).(driver.Valuer)
	if ok {
		return valuer.Value()
	}
	return o.value, nil
}

// Unwrap returns the contained value, panicking if None.
// Example:
// opt := Some(42)
// value := opt.Unwrap() // value is 42
// opt2 := None[int]()
// value2 := opt2.Unwrap() // panics
// fmt.Println(value) // prints: 42
// Note: Use Unwrap only when you are certain that the Option is Some.
func (o Option[T]) Unwrap() T {
	if !o.present {
		panic("called Unwrap on a None value")
	}
	return o.value
}

// UnwrapOr returns the contained value or a default.
func (o Option[T]) UnwrapOr(defaultValue T) T {
	if o.present {
		return o.value
	}
	return defaultValue
}

// UnwrapOrElse calls f if the value is None.
func (o Option[T]) UnwrapOrElse(f func() T) T {
	if o.present {
		return o.value
	}
	return f()
}

// UnwrapOrZero returns the contained value or the zero value of T.
func (o Option[T]) UnwrapOrZero() T {
	var zero T
	if o.present {
		return o.value
	}
	return zero
}

// Or returns first present value.
// Example:
// opt1 := None[int]()
// opt2 := Some(42)
// result := opt1.Or(opt2) // result is Some(42)
func (o Option[T]) Or(other Option[T]) Option[T] {
	if o.present {
		return o
	}
	return other
}

// OrElse calls f if the value is None.
// otherwise returns o.
func (o Option[T]) OrElse(f func() Option[T]) Option[T] {
	if o.present {
		return o
	}
	return f()
}

// And returns None if the Option is None.
// Otherwise returns other.
func (o Option[T]) And(other Option[T]) Option[T] {
	if o.present {
		return other
	}
	return None[T]()
}

// Ptr returns a pointer to the contained value.
// If the Option is None, it returns nil.
func (o Option[T]) Ptr() *T {
	if !o.present {
		return nil
	}
	return &o.value
}

// String returns a string representation of the Option.
// If the Option is Some, it returns "Some(value)".
// If the Option is None, it returns "None".
func (o Option[T]) String() string {
	if o.present {
		return fmt.Sprintf("Some(%v)", o.value)
	}
	return "None"
}

// Map applies a function to the contained value (if any),
// and returns a new Option containing the result.
func (o Option[T]) Map[U any](f func(T) U) Option[U] {
	if o.present {
		return Some(f(o.value))
	}
	return None[U]()
}

func (o Option[T]) FlatMap[U any](f func(T) Option[U]) Option[U] {
	if o.present {
		return f(o.value)
	}
	return None[U]()
}

// Filter returns None if the option is None, otherwise calls predicate with the wrapped value
// and returns the Option if the predicate returns true, or None if it returns false.
func (o Option[T]) Filter(predicate func(T) bool) Option[T] {
	if o.present && predicate(o.value) {
		return o
	}
	return None[T]()
}

// IsSomeAnd returns true if the option is a Some and the value inside of it matches a predicate.
func (o Option[T]) IsSomeAnd(f func(T) bool) bool {
	return o.present && f(o.value)
}

// CollectValues collects all present values from a slice of Option[T] into a slice of T.
func CollectValues[T any](opts []Option[T]) []T {
	var values []T
	for _, opt := range opts {
		if opt.present {
			values = append(values, opt.value)
		}
	}
	return values
}

func CoalesceOpt[T any](opts ...Option[T]) Option[T] {
	for _, opt := range opts {
		if opt.present {
			return opt
		}
	}
	return None[T]()
}

func NonZeroOption[T comparable](value T) Option[T] {
	var zero T
	if value == zero {
		return None[T]()
	}
	return Some(value)
}

// JSON/YAML marshaling and unmarshaling
func (o Option[T]) MarshalJSON() ([]byte, error) {
	if !o.present {
		return []byte("null"), nil
	}
	return json.Marshal(o.value)
}

func (o *Option[T]) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		*o = None[T]()
		return nil
	}

	var v T
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}

	*o = Some(v)
	return nil
}

func (o Option[T]) MarshalYAML() (any, error) {
	if !o.present {
		// Encodes as YAML null
		return nil, nil
	}
	// Encodes as the underlying scalar/sequence/map depending on T
	return o.value, nil
}

func (o *Option[T]) UnmarshalYAML(node *yaml.Node) error {
	// If the node is explicit null: "null", "~", or empty with !!null tag
	if node.Kind == yaml.ScalarNode && (node.Tag == "!!null" || node.Value == "" || node.Value == "null" || node.Value == "~") {
		*o = None[T]()
		return nil
	}

	var v T
	if err := node.Decode(&v); err != nil {
		return err
	}
	*o = Some(v)
	return nil
}
