// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: patchbase/agent/common.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OsFamily int32

const (
	OsFamily_OS_FAMILY_UNSPECIFIED OsFamily = 0
	OsFamily_OS_FAMILY_RPM         OsFamily = 1
	OsFamily_OS_FAMILY_APT         OsFamily = 2
)

// Enum value maps for OsFamily.
var (
	OsFamily_name = map[int32]string{
		0: "OS_FAMILY_UNSPECIFIED",
		1: "OS_FAMILY_RPM",
		2: "OS_FAMILY_APT",
	}
	OsFamily_value = map[string]int32{
		"OS_FAMILY_UNSPECIFIED": 0,
		"OS_FAMILY_RPM":         1,
		"OS_FAMILY_APT":         2,
	}
)

func (x OsFamily) Enum() *OsFamily {
	p := new(OsFamily)
	*p = x
	return p
}

func (x OsFamily) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OsFamily) Descriptor() protoreflect.EnumDescriptor {
	return file_patchbase_agent_common_proto_enumTypes[0].Descriptor()
}

func (OsFamily) Type() protoreflect.EnumType {
	return &file_patchbase_agent_common_proto_enumTypes[0]
}

func (x OsFamily) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OsFamily.Descriptor instead.
func (OsFamily) EnumDescriptor() ([]byte, []int) {
	return file_patchbase_agent_common_proto_rawDescGZIP(), []int{0}
}

type Architecture int32

const (
	Architecture_ARCHITECTURE_UNSPECIFIED Architecture = 0
	Architecture_ARCHITECTURE_X86_64      Architecture = 1
	Architecture_ARCHITECTURE_AARCH64     Architecture = 2
	Architecture_ARCHITECTURE_RISCV64     Architecture = 3
)

// Enum value maps for Architecture.
var (
	Architecture_name = map[int32]string{
		0: "ARCHITECTURE_UNSPECIFIED",
		1: "ARCHITECTURE_X86_64",
		2: "ARCHITECTURE_AARCH64",
		3: "ARCHITECTURE_RISCV64",
	}
	Architecture_value = map[string]int32{
		"ARCHITECTURE_UNSPECIFIED": 0,
		"ARCHITECTURE_X86_64":      1,
		"ARCHITECTURE_AARCH64":     2,
		"ARCHITECTURE_RISCV64":     3,
	}
)

func (x Architecture) Enum() *Architecture {
	p := new(Architecture)
	*p = x
	return p
}

func (x Architecture) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Architecture) Descriptor() protoreflect.EnumDescriptor {
	return file_patchbase_agent_common_proto_enumTypes[1].Descriptor()
}

func (Architecture) Type() protoreflect.EnumType {
	return &file_patchbase_agent_common_proto_enumTypes[1]
}

func (x Architecture) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Architecture.Descriptor instead.
func (Architecture) EnumDescriptor() ([]byte, []int) {
	return file_patchbase_agent_common_proto_rawDescGZIP(), []int{1}
}

type VirtualizationRole int32

const (
	VirtualizationRole_VIRTUALIZATION_ROLE_UNSPECIFIED VirtualizationRole = 0
	VirtualizationRole_VIRTUALIZATION_ROLE_BARE_METAL  VirtualizationRole = 1
	VirtualizationRole_VIRTUALIZATION_ROLE_VM          VirtualizationRole = 2
	VirtualizationRole_VIRTUALIZATION_ROLE_CONTAINER   VirtualizationRole = 3
	VirtualizationRole_VIRTUALIZATION_ROLE_UNKNOWN     VirtualizationRole = 4
)

// Enum value maps for VirtualizationRole.
var (
	VirtualizationRole_name = map[int32]string{
		0: "VIRTUALIZATION_ROLE_UNSPECIFIED",
		1: "VIRTUALIZATION_ROLE_BARE_METAL",
		2: "VIRTUALIZATION_ROLE_VM",
		3: "VIRTUALIZATION_ROLE_CONTAINER",
		4: "VIRTUALIZATION_ROLE_UNKNOWN",
	}
	VirtualizationRole_value = map[string]int32{
		"VIRTUALIZATION_ROLE_UNSPECIFIED": 0,
		"VIRTUALIZATION_ROLE_BARE_METAL":  1,
		"VIRTUALIZATION_ROLE_VM":          2,
		"VIRTUALIZATION_ROLE_CONTAINER":   3,
		"VIRTUALIZATION_ROLE_UNKNOWN":     4,
	}
)

func (x VirtualizationRole) Enum() *VirtualizationRole {
	p := new(VirtualizationRole)
	*p = x
	return p
}

func (x VirtualizationRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VirtualizationRole) Descriptor() protoreflect.EnumDescriptor {
	return file_patchbase_agent_common_proto_enumTypes[2].Descriptor()
}

func (VirtualizationRole) Type() protoreflect.EnumType {
	return &file_patchbase_agent_common_proto_enumTypes[2]
}

func (x VirtualizationRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VirtualizationRole.Descriptor instead.
func (VirtualizationRole) EnumDescriptor() ([]byte, []int) {
	return file_patchbase_agent_common_proto_rawDescGZIP(), []int{2}
}

type APIError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIError) Reset() {
	*x = APIError{}
	mi := &file_patchbase_agent_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIError) ProtoMessage() {}

func (x *APIError) ProtoReflect() protoreflect.Message {
	mi := &file_patchbase_agent_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIError.ProtoReflect.Descriptor instead.
func (*APIError) Descriptor() ([]byte, []int) {
	return file_patchbase_agent_common_proto_rawDescGZIP(), []int{0}
}

func (x *APIError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *APIError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_patchbase_agent_common_proto protoreflect.FileDescriptor

const file_patchbase_agent_common_proto_rawDesc = "" +
	"\n" +
	"\x1cpatchbase/agent/common.proto\x12\x0fpatchbase.agent\"E\n" +
	"\bAPIError\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessageJ\x04\b\x01\x10\x02R\x05error*K\n" +
	"\bOsFamily\x12\x19\n" +
	"\x15OS_FAMILY_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rOS_FAMILY_RPM\x10\x01\x12\x11\n" +
	"\rOS_FAMILY_APT\x10\x02*y\n" +
	"\fArchitecture\x12\x1c\n" +
	"\x18ARCHITECTURE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ARCHITECTURE_X86_64\x10\x01\x12\x18\n" +
	"\x14ARCHITECTURE_AARCH64\x10\x02\x12\x18\n" +
	"\x14ARCHITECTURE_RISCV64\x10\x03*\xbd\x01\n" +
	"\x12VirtualizationRole\x12#\n" +
	"\x1fVIRTUALIZATION_ROLE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eVIRTUALIZATION_ROLE_BARE_METAL\x10\x01\x12\x1a\n" +
	"\x16VIRTUALIZATION_ROLE_VM\x10\x02\x12!\n" +
	"\x1dVIRTUALIZATION_ROLE_CONTAINER\x10\x03\x12\x1f\n" +
	"\x1bVIRTUALIZATION_ROLE_UNKNOWN\x10\x04B\x1eZ\x1cgo.patchbase.net/proto/agentb\x06proto3"

var (
	file_patchbase_agent_common_proto_rawDescOnce sync.Once
	file_patchbase_agent_common_proto_rawDescData []byte
)

func file_patchbase_agent_common_proto_rawDescGZIP() []byte {
	file_patchbase_agent_common_proto_rawDescOnce.Do(func() {
		file_patchbase_agent_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_patchbase_agent_common_proto_rawDesc), len(file_patchbase_agent_common_proto_rawDesc)))
	})
	return file_patchbase_agent_common_proto_rawDescData
}

var file_patchbase_agent_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_patchbase_agent_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_patchbase_agent_common_proto_goTypes = []any{
	(OsFamily)(0),           // 0: patchbase.agent.OsFamily
	(Architecture)(0),       // 1: patchbase.agent.Architecture
	(VirtualizationRole)(0), // 2: patchbase.agent.VirtualizationRole
	(*APIError)(nil),        // 3: patchbase.agent.APIError
}
var file_patchbase_agent_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_patchbase_agent_common_proto_init() }
func file_patchbase_agent_common_proto_init() {
	if File_patchbase_agent_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_patchbase_agent_common_proto_rawDesc), len(file_patchbase_agent_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_patchbase_agent_common_proto_goTypes,
		DependencyIndexes: file_patchbase_agent_common_proto_depIdxs,
		EnumInfos:         file_patchbase_agent_common_proto_enumTypes,
		MessageInfos:      file_patchbase_agent_common_proto_msgTypes,
	}.Build()
	File_patchbase_agent_common_proto = out.File
	file_patchbase_agent_common_proto_goTypes = nil
	file_patchbase_agent_common_proto_depIdxs = nil
}
