// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: patchbase/agent/host.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Host struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	MachineId                   string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	Hostname                    string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	OsFamily                    OsFamily               `protobuf:"varint,3,opt,name=os_family,json=osFamily,proto3,enum=patchbase.agent.OsFamily" json:"os_family,omitempty"`
	OsName                      string                 `protobuf:"bytes,4,opt,name=os_name,json=osName,proto3" json:"os_name,omitempty"`
	OsVersion                   string                 `protobuf:"bytes,5,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	OsMajor                     int32                  `protobuf:"varint,6,opt,name=os_major,json=osMajor,proto3" json:"os_major,omitempty"`
	Architecture                Architecture           `protobuf:"varint,7,opt,name=architecture,proto3,enum=patchbase.agent.Architecture" json:"architecture,omitempty"`
	AvailablePackageUpdateCount int32                  `protobuf:"varint,8,opt,name=available_package_update_count,json=availablePackageUpdateCount,proto3" json:"available_package_update_count,omitempty"`
	AgentVersion                string                 `protobuf:"bytes,9,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	BootTime                    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=boot_time,json=bootTime,proto3" json:"boot_time,omitempty"`
	UptimeSeconds               int64                  `protobuf:"varint,11,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	VirtualizationRole          VirtualizationRole     `protobuf:"varint,12,opt,name=virtualization_role,json=virtualizationRole,proto3,enum=patchbase.agent.VirtualizationRole" json:"virtualization_role,omitempty"`
	EnvironmentTags             []string               `protobuf:"bytes,13,rep,name=environment_tags,json=environmentTags,proto3" json:"environment_tags,omitempty"`
	IpAddresses                 []string               `protobuf:"bytes,14,rep,name=ip_addresses,json=ipAddresses,proto3" json:"ip_addresses,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Host) Reset() {
	*x = Host{}
	mi := &file_patchbase_agent_host_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_patchbase_agent_host_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_patchbase_agent_host_proto_rawDescGZIP(), []int{0}
}

func (x *Host) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *Host) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Host) GetOsFamily() OsFamily {
	if x != nil {
		return x.OsFamily
	}
	return OsFamily_OS_FAMILY_UNSPECIFIED
}

func (x *Host) GetOsName() string {
	if x != nil {
		return x.OsName
	}
	return ""
}

func (x *Host) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *Host) GetOsMajor() int32 {
	if x != nil {
		return x.OsMajor
	}
	return 0
}

func (x *Host) GetArchitecture() Architecture {
	if x != nil {
		return x.Architecture
	}
	return Architecture_ARCHITECTURE_UNSPECIFIED
}

func (x *Host) GetAvailablePackageUpdateCount() int32 {
	if x != nil {
		return x.AvailablePackageUpdateCount
	}
	return 0
}

func (x *Host) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Host) GetBootTime() *timestamppb.Timestamp {
	if x != nil {
		return x.BootTime
	}
	return nil
}

func (x *Host) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *Host) GetVirtualizationRole() VirtualizationRole {
	if x != nil {
		return x.VirtualizationRole
	}
	return VirtualizationRole_VIRTUALIZATION_ROLE_UNSPECIFIED
}

func (x *Host) GetEnvironmentTags() []string {
	if x != nil {
		return x.EnvironmentTags
	}
	return nil
}

func (x *Host) GetIpAddresses() []string {
	if x != nil {
		return x.IpAddresses
	}
	return nil
}

var File_patchbase_agent_host_proto protoreflect.FileDescriptor

const file_patchbase_agent_host_proto_rawDesc = "" +
	"\n" +
	"\x1apatchbase/agent/host.proto\x12\x0fpatchbase.agent\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cpatchbase/agent/common.proto\"\xfd\x04\n" +
	"\x04Host\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x126\n" +
	"\tos_family\x18\x03 \x01(\x0e2\x19.patchbase.agent.OsFamilyR\bosFamily\x12\x17\n" +
	"\aos_name\x18\x04 \x01(\tR\x06osName\x12\x1d\n" +
	"\n" +
	"os_version\x18\x05 \x01(\tR\tosVersion\x12\x19\n" +
	"\bos_major\x18\x06 \x01(\x05R\aosMajor\x12A\n" +
	"\farchitecture\x18\a \x01(\x0e2\x1d.patchbase.agent.ArchitectureR\farchitecture\x12C\n" +
	"\x1eavailable_package_update_count\x18\b \x01(\x05R\x1bavailablePackageUpdateCount\x12#\n" +
	"\ragent_version\x18\t \x01(\tR\fagentVersion\x127\n" +
	"\tboot_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bbootTime\x12%\n" +
	"\x0euptime_seconds\x18\v \x01(\x03R\ruptimeSeconds\x12T\n" +
	"\x13virtualization_role\x18\f \x01(\x0e2#.patchbase.agent.VirtualizationRoleR\x12virtualizationRole\x12)\n" +
	"\x10environment_tags\x18\r \x03(\tR\x0fenvironmentTags\x12!\n" +
	"\fip_addresses\x18\x0e \x03(\tR\vipAddressesB\x1eZ\x1cgo.patchbase.net/proto/agentb\x06proto3"

var (
	file_patchbase_agent_host_proto_rawDescOnce sync.Once
	file_patchbase_agent_host_proto_rawDescData []byte
)

func file_patchbase_agent_host_proto_rawDescGZIP() []byte {
	file_patchbase_agent_host_proto_rawDescOnce.Do(func() {
		file_patchbase_agent_host_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_patchbase_agent_host_proto_rawDesc), len(file_patchbase_agent_host_proto_rawDesc)))
	})
	return file_patchbase_agent_host_proto_rawDescData
}

var file_patchbase_agent_host_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_patchbase_agent_host_proto_goTypes = []any{
	(*Host)(nil),                  // 0: patchbase.agent.Host
	(OsFamily)(0),                 // 1: patchbase.agent.OsFamily
	(Architecture)(0),             // 2: patchbase.agent.Architecture
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(VirtualizationRole)(0),       // 4: patchbase.agent.VirtualizationRole
}
var file_patchbase_agent_host_proto_depIdxs = []int32{
	1, // 0: patchbase.agent.Host.os_family:type_name -> patchbase.agent.OsFamily
	2, // 1: patchbase.agent.Host.architecture:type_name -> patchbase.agent.Architecture
	3, // 2: patchbase.agent.Host.boot_time:type_name -> google.protobuf.Timestamp
	4, // 3: patchbase.agent.Host.virtualization_role:type_name -> patchbase.agent.VirtualizationRole
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_patchbase_agent_host_proto_init() }
func file_patchbase_agent_host_proto_init() {
	if File_patchbase_agent_host_proto != nil {
		return
	}
	file_patchbase_agent_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_patchbase_agent_host_proto_rawDesc), len(file_patchbase_agent_host_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_patchbase_agent_host_proto_goTypes,
		DependencyIndexes: file_patchbase_agent_host_proto_depIdxs,
		MessageInfos:      file_patchbase_agent_host_proto_msgTypes,
	}.Build()
	File_patchbase_agent_host_proto = out.File
	file_patchbase_agent_host_proto_goTypes = nil
	file_patchbase_agent_host_proto_depIdxs = nil
}
