// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: patchbase/agent/host.proto

package agent

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Host with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Host) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Host with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in HostMultiError, or nil if none found.
func (m *Host) ValidateAll() error {
	return m.validate(true)
}

func (m *Host) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for MachineId

	// no validation rules for Hostname

	// no validation rules for OsFamily

	// no validation rules for OsName

	// no validation rules for OsVersion

	// no validation rules for OsMajor

	// no validation rules for Architecture

	// no validation rules for AvailablePackageUpdateCount

	// no validation rules for AgentVersion

	if all {
		switch v := interface{}(m.GetBootTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, HostValidationError{
					field:  "BootTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, HostValidationError{
					field:  "BootTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBootTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return HostValidationError{
				field:  "BootTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for UptimeSeconds

	// no validation rules for VirtualizationRole

	if len(errors) > 0 {
		return HostMultiError(errors)
	}

	return nil
}

// HostMultiError is an error wrapping multiple validation errors returned by
// Host.ValidateAll() if the designated constraints aren't met.
type HostMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HostMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HostMultiError) AllErrors() []error { return m }

// HostValidationError is the validation error returned by Host.Validate if the
// designated constraints aren't met.
type HostValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HostValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HostValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HostValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HostValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HostValidationError) ErrorName() string { return "HostValidationError" }

// Error satisfies the builtin error interface
func (e HostValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHost.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HostValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HostValidationError{}

// Validate checks the field values on RegisterHostMetadata with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RegisterHostMetadata) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterHostMetadata with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RegisterHostMetadataMultiError, or nil if none found.
func (m *RegisterHostMetadata) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterHostMetadata) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for IpAddress

	// no validation rules for OsName

	// no validation rules for OsVersion

	// no validation rules for Architecture

	if len(errors) > 0 {
		return RegisterHostMetadataMultiError(errors)
	}

	return nil
}

// RegisterHostMetadataMultiError is an error wrapping multiple validation
// errors returned by RegisterHostMetadata.ValidateAll() if the designated
// constraints aren't met.
type RegisterHostMetadataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterHostMetadataMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterHostMetadataMultiError) AllErrors() []error { return m }

// RegisterHostMetadataValidationError is the validation error returned by
// RegisterHostMetadata.Validate if the designated constraints aren't met.
type RegisterHostMetadataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterHostMetadataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterHostMetadataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterHostMetadataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterHostMetadataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterHostMetadataValidationError) ErrorName() string {
	return "RegisterHostMetadataValidationError"
}

// Error satisfies the builtin error interface
func (e RegisterHostMetadataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterHostMetadata.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterHostMetadataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterHostMetadataValidationError{}

// Validate checks the field values on RegisterHostRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RegisterHostRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterHostRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RegisterHostRequestMultiError, or nil if none found.
func (m *RegisterHostRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterHostRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetRegistrationToken()); l < 1 || l > 255 {
		err := RegisterHostRequestValidationError{
			field:  "RegistrationToken",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetHostname()); l < 1 || l > 255 {
		err := RegisterHostRequestValidationError{
			field:  "Hostname",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetMachineId()); l < 1 || l > 128 {
		err := RegisterHostRequestValidationError{
			field:  "MachineId",
			reason: "value length must be between 1 and 128 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetMetadata() == nil {
		err := RegisterHostRequestValidationError{
			field:  "Metadata",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetMetadata()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RegisterHostRequestValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RegisterHostRequestValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMetadata()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RegisterHostRequestValidationError{
				field:  "Metadata",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RegisterHostRequestMultiError(errors)
	}

	return nil
}

// RegisterHostRequestMultiError is an error wrapping multiple validation
// errors returned by RegisterHostRequest.ValidateAll() if the designated
// constraints aren't met.
type RegisterHostRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterHostRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterHostRequestMultiError) AllErrors() []error { return m }

// RegisterHostRequestValidationError is the validation error returned by
// RegisterHostRequest.Validate if the designated constraints aren't met.
type RegisterHostRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterHostRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterHostRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterHostRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterHostRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterHostRequestValidationError) ErrorName() string {
	return "RegisterHostRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RegisterHostRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterHostRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterHostRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterHostRequestValidationError{}

// Validate checks the field values on RegisterHostResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RegisterHostResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterHostResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RegisterHostResponseMultiError, or nil if none found.
func (m *RegisterHostResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterHostResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for HostId

	// no validation rules for HostAccessToken

	// no validation rules for ApprovalStatus

	if len(errors) > 0 {
		return RegisterHostResponseMultiError(errors)
	}

	return nil
}

// RegisterHostResponseMultiError is an error wrapping multiple validation
// errors returned by RegisterHostResponse.ValidateAll() if the designated
// constraints aren't met.
type RegisterHostResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterHostResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterHostResponseMultiError) AllErrors() []error { return m }

// RegisterHostResponseValidationError is the validation error returned by
// RegisterHostResponse.Validate if the designated constraints aren't met.
type RegisterHostResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterHostResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterHostResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterHostResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterHostResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterHostResponseValidationError) ErrorName() string {
	return "RegisterHostResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RegisterHostResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterHostResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterHostResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterHostResponseValidationError{}
