// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: patchbase/agent/host.proto

package agent

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Host struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	MachineId                   string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	Hostname                    string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	OsFamily                    OsFamily               `protobuf:"varint,3,opt,name=os_family,json=osFamily,proto3,enum=patchbase.agent.OsFamily" json:"os_family,omitempty"`
	OsName                      string                 `protobuf:"bytes,4,opt,name=os_name,json=osName,proto3" json:"os_name,omitempty"`
	OsVersion                   string                 `protobuf:"bytes,5,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	OsMajor                     int32                  `protobuf:"varint,6,opt,name=os_major,json=osMajor,proto3" json:"os_major,omitempty"`
	Architecture                Architecture           `protobuf:"varint,7,opt,name=architecture,proto3,enum=patchbase.agent.Architecture" json:"architecture,omitempty"`
	AvailablePackageUpdateCount int32                  `protobuf:"varint,8,opt,name=available_package_update_count,json=availablePackageUpdateCount,proto3" json:"available_package_update_count,omitempty"`
	AgentVersion                string                 `protobuf:"bytes,9,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	BootTime                    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=boot_time,json=bootTime,proto3" json:"boot_time,omitempty"`
	UptimeSeconds               int64                  `protobuf:"varint,11,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	VirtualizationRole          VirtualizationRole     `protobuf:"varint,12,opt,name=virtualization_role,json=virtualizationRole,proto3,enum=patchbase.agent.VirtualizationRole" json:"virtualization_role,omitempty"`
	EnvironmentTags             []string               `protobuf:"bytes,13,rep,name=environment_tags,json=environmentTags,proto3" json:"environment_tags,omitempty"`
	IpAddresses                 []string               `protobuf:"bytes,14,rep,name=ip_addresses,json=ipAddresses,proto3" json:"ip_addresses,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Host) Reset() {
	*x = Host{}
	mi := &file_patchbase_agent_host_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_patchbase_agent_host_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_patchbase_agent_host_proto_rawDescGZIP(), []int{0}
}

func (x *Host) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *Host) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Host) GetOsFamily() OsFamily {
	if x != nil {
		return x.OsFamily
	}
	return OsFamily_OS_FAMILY_UNSPECIFIED
}

func (x *Host) GetOsName() string {
	if x != nil {
		return x.OsName
	}
	return ""
}

func (x *Host) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *Host) GetOsMajor() int32 {
	if x != nil {
		return x.OsMajor
	}
	return 0
}

func (x *Host) GetArchitecture() Architecture {
	if x != nil {
		return x.Architecture
	}
	return Architecture_ARCHITECTURE_UNSPECIFIED
}

func (x *Host) GetAvailablePackageUpdateCount() int32 {
	if x != nil {
		return x.AvailablePackageUpdateCount
	}
	return 0
}

func (x *Host) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Host) GetBootTime() *timestamppb.Timestamp {
	if x != nil {
		return x.BootTime
	}
	return nil
}

func (x *Host) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *Host) GetVirtualizationRole() VirtualizationRole {
	if x != nil {
		return x.VirtualizationRole
	}
	return VirtualizationRole_VIRTUALIZATION_ROLE_UNSPECIFIED
}

func (x *Host) GetEnvironmentTags() []string {
	if x != nil {
		return x.EnvironmentTags
	}
	return nil
}

func (x *Host) GetIpAddresses() []string {
	if x != nil {
		return x.IpAddresses
	}
	return nil
}

type RegisterHostMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpAddress     string                 `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	OsName        string                 `protobuf:"bytes,2,opt,name=os_name,json=osName,proto3" json:"os_name,omitempty"`
	OsVersion     string                 `protobuf:"bytes,3,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	Architecture  string                 `protobuf:"bytes,4,opt,name=architecture,proto3" json:"architecture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterHostMetadata) Reset() {
	*x = RegisterHostMetadata{}
	mi := &file_patchbase_agent_host_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterHostMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterHostMetadata) ProtoMessage() {}

func (x *RegisterHostMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_patchbase_agent_host_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterHostMetadata.ProtoReflect.Descriptor instead.
func (*RegisterHostMetadata) Descriptor() ([]byte, []int) {
	return file_patchbase_agent_host_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterHostMetadata) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RegisterHostMetadata) GetOsName() string {
	if x != nil {
		return x.OsName
	}
	return ""
}

func (x *RegisterHostMetadata) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *RegisterHostMetadata) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

type RegisterHostRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RegistrationToken string                 `protobuf:"bytes,1,opt,name=registration_token,json=registrationToken,proto3" json:"registration_token,omitempty"`
	Hostname          string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	MachineId         string                 `protobuf:"bytes,3,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	Metadata          *RegisterHostMetadata  `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterHostRequest) Reset() {
	*x = RegisterHostRequest{}
	mi := &file_patchbase_agent_host_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterHostRequest) ProtoMessage() {}

func (x *RegisterHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patchbase_agent_host_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterHostRequest.ProtoReflect.Descriptor instead.
func (*RegisterHostRequest) Descriptor() ([]byte, []int) {
	return file_patchbase_agent_host_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterHostRequest) GetRegistrationToken() string {
	if x != nil {
		return x.RegistrationToken
	}
	return ""
}

func (x *RegisterHostRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterHostRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *RegisterHostRequest) GetMetadata() *RegisterHostMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RegisterHostResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HostId          string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	HostAccessToken string                 `protobuf:"bytes,2,opt,name=host_access_token,json=hostAccessToken,proto3" json:"host_access_token,omitempty"`
	ApprovalStatus  string                 `protobuf:"bytes,3,opt,name=approval_status,json=approvalStatus,proto3" json:"approval_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterHostResponse) Reset() {
	*x = RegisterHostResponse{}
	mi := &file_patchbase_agent_host_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterHostResponse) ProtoMessage() {}

func (x *RegisterHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patchbase_agent_host_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterHostResponse.ProtoReflect.Descriptor instead.
func (*RegisterHostResponse) Descriptor() ([]byte, []int) {
	return file_patchbase_agent_host_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterHostResponse) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *RegisterHostResponse) GetHostAccessToken() string {
	if x != nil {
		return x.HostAccessToken
	}
	return ""
}

func (x *RegisterHostResponse) GetApprovalStatus() string {
	if x != nil {
		return x.ApprovalStatus
	}
	return ""
}

var File_patchbase_agent_host_proto protoreflect.FileDescriptor

const file_patchbase_agent_host_proto_rawDesc = "" +
	"\n" +
	"\x1apatchbase/agent/host.proto\x12\x0fpatchbase.agent\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cpatchbase/agent/common.proto\x1a\x17validate/validate.proto\"\xfd\x04\n" +
	"\x04Host\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x126\n" +
	"\tos_family\x18\x03 \x01(\x0e2\x19.patchbase.agent.OsFamilyR\bosFamily\x12\x17\n" +
	"\aos_name\x18\x04 \x01(\tR\x06osName\x12\x1d\n" +
	"\n" +
	"os_version\x18\x05 \x01(\tR\tosVersion\x12\x19\n" +
	"\bos_major\x18\x06 \x01(\x05R\aosMajor\x12A\n" +
	"\farchitecture\x18\a \x01(\x0e2\x1d.patchbase.agent.ArchitectureR\farchitecture\x12C\n" +
	"\x1eavailable_package_update_count\x18\b \x01(\x05R\x1bavailablePackageUpdateCount\x12#\n" +
	"\ragent_version\x18\t \x01(\tR\fagentVersion\x127\n" +
	"\tboot_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bbootTime\x12%\n" +
	"\x0euptime_seconds\x18\v \x01(\x03R\ruptimeSeconds\x12T\n" +
	"\x13virtualization_role\x18\f \x01(\x0e2#.patchbase.agent.VirtualizationRoleR\x12virtualizationRole\x12)\n" +
	"\x10environment_tags\x18\r \x03(\tR\x0fenvironmentTags\x12!\n" +
	"\fip_addresses\x18\x0e \x03(\tR\vipAddresses\"\x91\x01\n" +
	"\x14RegisterHostMetadata\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\x12\x17\n" +
	"\aos_name\x18\x02 \x01(\tR\x06osName\x12\x1d\n" +
	"\n" +
	"os_version\x18\x03 \x01(\tR\tosVersion\x12\"\n" +
	"\farchitecture\x18\x04 \x01(\tR\farchitecture\"\xf0\x01\n" +
	"\x13RegisterHostRequest\x129\n" +
	"\x12registration_token\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xff\x01R\x11registrationToken\x12&\n" +
	"\bhostname\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xff\x01R\bhostname\x12)\n" +
	"\n" +
	"machine_id\x18\x03 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x01R\tmachineId\x12K\n" +
	"\bmetadata\x18\x04 \x01(\v2%.patchbase.agent.RegisterHostMetadataB\b\xfaB\x05\x8a\x01\x02\x10\x01R\bmetadata\"\x84\x01\n" +
	"\x14RegisterHostResponse\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12*\n" +
	"\x11host_access_token\x18\x02 \x01(\tR\x0fhostAccessToken\x12'\n" +
	"\x0fapproval_status\x18\x03 \x01(\tR\x0eapprovalStatusB\x1eZ\x1cgo.patchbase.net/proto/agentb\x06proto3"

var (
	file_patchbase_agent_host_proto_rawDescOnce sync.Once
	file_patchbase_agent_host_proto_rawDescData []byte
)

func file_patchbase_agent_host_proto_rawDescGZIP() []byte {
	file_patchbase_agent_host_proto_rawDescOnce.Do(func() {
		file_patchbase_agent_host_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_patchbase_agent_host_proto_rawDesc), len(file_patchbase_agent_host_proto_rawDesc)))
	})
	return file_patchbase_agent_host_proto_rawDescData
}

var file_patchbase_agent_host_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_patchbase_agent_host_proto_goTypes = []any{
	(*Host)(nil),                  // 0: patchbase.agent.Host
	(*RegisterHostMetadata)(nil),  // 1: patchbase.agent.RegisterHostMetadata
	(*RegisterHostRequest)(nil),   // 2: patchbase.agent.RegisterHostRequest
	(*RegisterHostResponse)(nil),  // 3: patchbase.agent.RegisterHostResponse
	(OsFamily)(0),                 // 4: patchbase.agent.OsFamily
	(Architecture)(0),             // 5: patchbase.agent.Architecture
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(VirtualizationRole)(0),       // 7: patchbase.agent.VirtualizationRole
}
var file_patchbase_agent_host_proto_depIdxs = []int32{
	4, // 0: patchbase.agent.Host.os_family:type_name -> patchbase.agent.OsFamily
	5, // 1: patchbase.agent.Host.architecture:type_name -> patchbase.agent.Architecture
	6, // 2: patchbase.agent.Host.boot_time:type_name -> google.protobuf.Timestamp
	7, // 3: patchbase.agent.Host.virtualization_role:type_name -> patchbase.agent.VirtualizationRole
	1, // 4: patchbase.agent.RegisterHostRequest.metadata:type_name -> patchbase.agent.RegisterHostMetadata
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_patchbase_agent_host_proto_init() }
func file_patchbase_agent_host_proto_init() {
	if File_patchbase_agent_host_proto != nil {
		return
	}
	file_patchbase_agent_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_patchbase_agent_host_proto_rawDesc), len(file_patchbase_agent_host_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_patchbase_agent_host_proto_goTypes,
		DependencyIndexes: file_patchbase_agent_host_proto_depIdxs,
		MessageInfos:      file_patchbase_agent_host_proto_msgTypes,
	}.Build()
	File_patchbase_agent_host_proto = out.File
	file_patchbase_agent_host_proto_goTypes = nil
	file_patchbase_agent_host_proto_depIdxs = nil
}
