// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: patchbase/agent/package.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Package struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Epoch         int32                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Release       string                 `protobuf:"bytes,4,opt,name=release,proto3" json:"release,omitempty"`
	Arch          string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	SourceRpm     string                 `protobuf:"bytes,6,opt,name=source_rpm,json=sourceRpm,proto3" json:"source_rpm,omitempty"`
	Vendor        string                 `protobuf:"bytes,7,opt,name=vendor,proto3" json:"vendor,omitempty"`
	InstallTime   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=install_time,json=installTime,proto3" json:"install_time,omitempty"`
	RepoOrigin    string                 `protobuf:"bytes,9,opt,name=repo_origin,json=repoOrigin,proto3" json:"repo_origin,omitempty"`
	Nevra         string                 `protobuf:"bytes,10,opt,name=nevra,proto3" json:"nevra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Package) Reset() {
	*x = Package{}
	mi := &file_patchbase_agent_package_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_patchbase_agent_package_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_patchbase_agent_package_proto_rawDescGZIP(), []int{0}
}

func (x *Package) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Package) GetEpoch() int32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Package) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Package) GetRelease() string {
	if x != nil {
		return x.Release
	}
	return ""
}

func (x *Package) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Package) GetSourceRpm() string {
	if x != nil {
		return x.SourceRpm
	}
	return ""
}

func (x *Package) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *Package) GetInstallTime() *timestamppb.Timestamp {
	if x != nil {
		return x.InstallTime
	}
	return nil
}

func (x *Package) GetRepoOrigin() string {
	if x != nil {
		return x.RepoOrigin
	}
	return ""
}

func (x *Package) GetNevra() string {
	if x != nil {
		return x.Nevra
	}
	return ""
}

var File_patchbase_agent_package_proto protoreflect.FileDescriptor

const file_patchbase_agent_package_proto_rawDesc = "" +
	"\n" +
	"\x1dpatchbase/agent/package.proto\x12\x0fpatchbase.agent\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa8\x02\n" +
	"\aPackage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x05R\x05epoch\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x18\n" +
	"\arelease\x18\x04 \x01(\tR\arelease\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x12\x1d\n" +
	"\n" +
	"source_rpm\x18\x06 \x01(\tR\tsourceRpm\x12\x16\n" +
	"\x06vendor\x18\a \x01(\tR\x06vendor\x12=\n" +
	"\finstall_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vinstallTime\x12\x1f\n" +
	"\vrepo_origin\x18\t \x01(\tR\n" +
	"repoOrigin\x12\x14\n" +
	"\x05nevra\x18\n" +
	" \x01(\tR\x05nevraB\x1eZ\x1cgo.patchbase.net/proto/agentb\x06proto3"

var (
	file_patchbase_agent_package_proto_rawDescOnce sync.Once
	file_patchbase_agent_package_proto_rawDescData []byte
)

func file_patchbase_agent_package_proto_rawDescGZIP() []byte {
	file_patchbase_agent_package_proto_rawDescOnce.Do(func() {
		file_patchbase_agent_package_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_patchbase_agent_package_proto_rawDesc), len(file_patchbase_agent_package_proto_rawDesc)))
	})
	return file_patchbase_agent_package_proto_rawDescData
}

var file_patchbase_agent_package_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_patchbase_agent_package_proto_goTypes = []any{
	(*Package)(nil),               // 0: patchbase.agent.Package
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_patchbase_agent_package_proto_depIdxs = []int32{
	1, // 0: patchbase.agent.Package.install_time:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_patchbase_agent_package_proto_init() }
func file_patchbase_agent_package_proto_init() {
	if File_patchbase_agent_package_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_patchbase_agent_package_proto_rawDesc), len(file_patchbase_agent_package_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_patchbase_agent_package_proto_goTypes,
		DependencyIndexes: file_patchbase_agent_package_proto_depIdxs,
		MessageInfos:      file_patchbase_agent_package_proto_msgTypes,
	}.Build()
	File_patchbase_agent_package_proto = out.File
	file_patchbase_agent_package_proto_goTypes = nil
	file_patchbase_agent_package_proto_depIdxs = nil
}
