// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: patchbase/agent/repo.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Repo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoId        string                 `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	RepoLabel     string                 `protobuf:"bytes,3,opt,name=repo_label,json=repoLabel,proto3" json:"repo_label,omitempty"`
	Baseurl       string                 `protobuf:"bytes,4,opt,name=baseurl,proto3" json:"baseurl,omitempty"`
	Metalink      string                 `protobuf:"bytes,5,opt,name=metalink,proto3" json:"metalink,omitempty"`
	Mirrorlist    string                 `protobuf:"bytes,6,opt,name=mirrorlist,proto3" json:"mirrorlist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repo) Reset() {
	*x = Repo{}
	mi := &file_patchbase_agent_repo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repo) ProtoMessage() {}

func (x *Repo) ProtoReflect() protoreflect.Message {
	mi := &file_patchbase_agent_repo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repo.ProtoReflect.Descriptor instead.
func (*Repo) Descriptor() ([]byte, []int) {
	return file_patchbase_agent_repo_proto_rawDescGZIP(), []int{0}
}

func (x *Repo) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *Repo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Repo) GetRepoLabel() string {
	if x != nil {
		return x.RepoLabel
	}
	return ""
}

func (x *Repo) GetBaseurl() string {
	if x != nil {
		return x.Baseurl
	}
	return ""
}

func (x *Repo) GetMetalink() string {
	if x != nil {
		return x.Metalink
	}
	return ""
}

func (x *Repo) GetMirrorlist() string {
	if x != nil {
		return x.Mirrorlist
	}
	return ""
}

var File_patchbase_agent_repo_proto protoreflect.FileDescriptor

const file_patchbase_agent_repo_proto_rawDesc = "" +
	"\n" +
	"\x1apatchbase/agent/repo.proto\x12\x0fpatchbase.agent\"\xae\x01\n" +
	"\x04Repo\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"repo_label\x18\x03 \x01(\tR\trepoLabel\x12\x18\n" +
	"\abaseurl\x18\x04 \x01(\tR\abaseurl\x12\x1a\n" +
	"\bmetalink\x18\x05 \x01(\tR\bmetalink\x12\x1e\n" +
	"\n" +
	"mirrorlist\x18\x06 \x01(\tR\n" +
	"mirrorlistB\x1eZ\x1cgo.patchbase.net/proto/agentb\x06proto3"

var (
	file_patchbase_agent_repo_proto_rawDescOnce sync.Once
	file_patchbase_agent_repo_proto_rawDescData []byte
)

func file_patchbase_agent_repo_proto_rawDescGZIP() []byte {
	file_patchbase_agent_repo_proto_rawDescOnce.Do(func() {
		file_patchbase_agent_repo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_patchbase_agent_repo_proto_rawDesc), len(file_patchbase_agent_repo_proto_rawDesc)))
	})
	return file_patchbase_agent_repo_proto_rawDescData
}

var file_patchbase_agent_repo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_patchbase_agent_repo_proto_goTypes = []any{
	(*Repo)(nil), // 0: patchbase.agent.Repo
}
var file_patchbase_agent_repo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_patchbase_agent_repo_proto_init() }
func file_patchbase_agent_repo_proto_init() {
	if File_patchbase_agent_repo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_patchbase_agent_repo_proto_rawDesc), len(file_patchbase_agent_repo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_patchbase_agent_repo_proto_goTypes,
		DependencyIndexes: file_patchbase_agent_repo_proto_depIdxs,
		MessageInfos:      file_patchbase_agent_repo_proto_msgTypes,
	}.Build()
	File_patchbase_agent_repo_proto = out.File
	file_patchbase_agent_repo_proto_goTypes = nil
	file_patchbase_agent_repo_proto_depIdxs = nil
}
