// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: patchbase/agent/runtime.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Process struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Pid             int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	ProcessName     string                 `protobuf:"bytes,2,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	ServiceName     string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Exe             string                 `protobuf:"bytes,4,opt,name=exe,proto3" json:"exe,omitempty"`
	PackageNames    []string               `protobuf:"bytes,5,rep,name=package_names,json=packageNames,proto3" json:"package_names,omitempty"`
	LibraryPackages []string               `protobuf:"bytes,6,rep,name=library_packages,json=libraryPackages,proto3" json:"library_packages,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Process) Reset() {
	*x = Process{}
	mi := &file_patchbase_agent_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_patchbase_agent_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process.ProtoReflect.Descriptor instead.
func (*Process) Descriptor() ([]byte, []int) {
	return file_patchbase_agent_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *Process) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Process) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *Process) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Process) GetExe() string {
	if x != nil {
		return x.Exe
	}
	return ""
}

func (x *Process) GetPackageNames() []string {
	if x != nil {
		return x.PackageNames
	}
	return nil
}

func (x *Process) GetLibraryPackages() []string {
	if x != nil {
		return x.LibraryPackages
	}
	return nil
}

type Runtime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KernelRunning string                 `protobuf:"bytes,1,opt,name=kernel_running,json=kernelRunning,proto3" json:"kernel_running,omitempty"`
	Processes     []*Process             `protobuf:"bytes,2,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Runtime) Reset() {
	*x = Runtime{}
	mi := &file_patchbase_agent_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Runtime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Runtime) ProtoMessage() {}

func (x *Runtime) ProtoReflect() protoreflect.Message {
	mi := &file_patchbase_agent_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Runtime.ProtoReflect.Descriptor instead.
func (*Runtime) Descriptor() ([]byte, []int) {
	return file_patchbase_agent_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *Runtime) GetKernelRunning() string {
	if x != nil {
		return x.KernelRunning
	}
	return ""
}

func (x *Runtime) GetProcesses() []*Process {
	if x != nil {
		return x.Processes
	}
	return nil
}

var File_patchbase_agent_runtime_proto protoreflect.FileDescriptor

const file_patchbase_agent_runtime_proto_rawDesc = "" +
	"\n" +
	"\x1dpatchbase/agent/runtime.proto\x12\x0fpatchbase.agent\"\xc3\x01\n" +
	"\aProcess\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12!\n" +
	"\fprocess_name\x18\x02 \x01(\tR\vprocessName\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12\x10\n" +
	"\x03exe\x18\x04 \x01(\tR\x03exe\x12#\n" +
	"\rpackage_names\x18\x05 \x03(\tR\fpackageNames\x12)\n" +
	"\x10library_packages\x18\x06 \x03(\tR\x0flibraryPackages\"h\n" +
	"\aRuntime\x12%\n" +
	"\x0ekernel_running\x18\x01 \x01(\tR\rkernelRunning\x126\n" +
	"\tprocesses\x18\x02 \x03(\v2\x18.patchbase.agent.ProcessR\tprocessesB\x1eZ\x1cgo.patchbase.net/proto/agentb\x06proto3"

var (
	file_patchbase_agent_runtime_proto_rawDescOnce sync.Once
	file_patchbase_agent_runtime_proto_rawDescData []byte
)

func file_patchbase_agent_runtime_proto_rawDescGZIP() []byte {
	file_patchbase_agent_runtime_proto_rawDescOnce.Do(func() {
		file_patchbase_agent_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_patchbase_agent_runtime_proto_rawDesc), len(file_patchbase_agent_runtime_proto_rawDesc)))
	})
	return file_patchbase_agent_runtime_proto_rawDescData
}

var file_patchbase_agent_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_patchbase_agent_runtime_proto_goTypes = []any{
	(*Process)(nil), // 0: patchbase.agent.Process
	(*Runtime)(nil), // 1: patchbase.agent.Runtime
}
var file_patchbase_agent_runtime_proto_depIdxs = []int32{
	0, // 0: patchbase.agent.Runtime.processes:type_name -> patchbase.agent.Process
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_patchbase_agent_runtime_proto_init() }
func file_patchbase_agent_runtime_proto_init() {
	if File_patchbase_agent_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_patchbase_agent_runtime_proto_rawDesc), len(file_patchbase_agent_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_patchbase_agent_runtime_proto_goTypes,
		DependencyIndexes: file_patchbase_agent_runtime_proto_depIdxs,
		MessageInfos:      file_patchbase_agent_runtime_proto_msgTypes,
	}.Build()
	File_patchbase_agent_runtime_proto = out.File
	file_patchbase_agent_runtime_proto_goTypes = nil
	file_patchbase_agent_runtime_proto_depIdxs = nil
}
