// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: patchbase/agent/snapshot.proto

package agent

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AgentSnapshot with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AgentSnapshot) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AgentSnapshot with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AgentSnapshotMultiError, or
// nil if none found.
func (m *AgentSnapshot) ValidateAll() error {
	return m.validate(true)
}

func (m *AgentSnapshot) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetSchemaVersion()); l < 1 || l > 64 {
		err := AgentSnapshotValidationError{
			field:  "SchemaVersion",
			reason: "value length must be between 1 and 64 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetSentAt() == nil {
		err := AgentSnapshotValidationError{
			field:  "SentAt",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetHost() == nil {
		err := AgentSnapshotValidationError{
			field:  "Host",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetHost()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AgentSnapshotValidationError{
					field:  "Host",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AgentSnapshotValidationError{
					field:  "Host",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetHost()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AgentSnapshotValidationError{
				field:  "Host",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetRepos() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AgentSnapshotValidationError{
						field:  fmt.Sprintf("Repos[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AgentSnapshotValidationError{
						field:  fmt.Sprintf("Repos[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AgentSnapshotValidationError{
					field:  fmt.Sprintf("Repos[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetPackages() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AgentSnapshotValidationError{
						field:  fmt.Sprintf("Packages[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AgentSnapshotValidationError{
						field:  fmt.Sprintf("Packages[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AgentSnapshotValidationError{
					field:  fmt.Sprintf("Packages[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.GetRuntime() == nil {
		err := AgentSnapshotValidationError{
			field:  "Runtime",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetRuntime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AgentSnapshotValidationError{
					field:  "Runtime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AgentSnapshotValidationError{
					field:  "Runtime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRuntime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AgentSnapshotValidationError{
				field:  "Runtime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetUpgradablePackages() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AgentSnapshotValidationError{
						field:  fmt.Sprintf("UpgradablePackages[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AgentSnapshotValidationError{
						field:  fmt.Sprintf("UpgradablePackages[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AgentSnapshotValidationError{
					field:  fmt.Sprintf("UpgradablePackages[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return AgentSnapshotMultiError(errors)
	}

	return nil
}

// AgentSnapshotMultiError is an error wrapping multiple validation errors
// returned by AgentSnapshot.ValidateAll() if the designated constraints
// aren't met.
type AgentSnapshotMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AgentSnapshotMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AgentSnapshotMultiError) AllErrors() []error { return m }

// AgentSnapshotValidationError is the validation error returned by
// AgentSnapshot.Validate if the designated constraints aren't met.
type AgentSnapshotValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AgentSnapshotValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AgentSnapshotValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AgentSnapshotValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AgentSnapshotValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AgentSnapshotValidationError) ErrorName() string { return "AgentSnapshotValidationError" }

// Error satisfies the builtin error interface
func (e AgentSnapshotValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAgentSnapshot.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AgentSnapshotValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AgentSnapshotValidationError{}

// Validate checks the field values on SyncResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SyncResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SyncResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SyncResponseMultiError, or
// nil if none found.
func (m *SyncResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SyncResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Accepted

	// no validation rules for HostId

	// no validation rules for SnapshotId

	// no validation rules for NextCheckInSeconds

	if len(errors) > 0 {
		return SyncResponseMultiError(errors)
	}

	return nil
}

// SyncResponseMultiError is an error wrapping multiple validation errors
// returned by SyncResponse.ValidateAll() if the designated constraints aren't met.
type SyncResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SyncResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SyncResponseMultiError) AllErrors() []error { return m }

// SyncResponseValidationError is the validation error returned by
// SyncResponse.Validate if the designated constraints aren't met.
type SyncResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SyncResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SyncResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SyncResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SyncResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SyncResponseValidationError) ErrorName() string { return "SyncResponseValidationError" }

// Error satisfies the builtin error interface
func (e SyncResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSyncResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SyncResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SyncResponseValidationError{}
