// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: patchbase/agent/snapshot.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	Host          *Host                  `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Repos         []*Repo                `protobuf:"bytes,4,rep,name=repos,proto3" json:"repos,omitempty"`
	Packages      []*Package             `protobuf:"bytes,5,rep,name=packages,proto3" json:"packages,omitempty"`
	Runtime       *Runtime               `protobuf:"bytes,6,opt,name=runtime,proto3" json:"runtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSnapshot) Reset() {
	*x = AgentSnapshot{}
	mi := &file_patchbase_agent_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSnapshot) ProtoMessage() {}

func (x *AgentSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_patchbase_agent_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSnapshot.ProtoReflect.Descriptor instead.
func (*AgentSnapshot) Descriptor() ([]byte, []int) {
	return file_patchbase_agent_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *AgentSnapshot) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *AgentSnapshot) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *AgentSnapshot) GetHost() *Host {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *AgentSnapshot) GetRepos() []*Repo {
	if x != nil {
		return x.Repos
	}
	return nil
}

func (x *AgentSnapshot) GetPackages() []*Package {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *AgentSnapshot) GetRuntime() *Runtime {
	if x != nil {
		return x.Runtime
	}
	return nil
}

var File_patchbase_agent_snapshot_proto protoreflect.FileDescriptor

const file_patchbase_agent_snapshot_proto_rawDesc = "" +
	"\n" +
	"\x1epatchbase/agent/snapshot.proto\x12\x0fpatchbase.agent\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1apatchbase/agent/host.proto\x1a\x1dpatchbase/agent/package.proto\x1a\x1apatchbase/agent/repo.proto\x1a\x1dpatchbase/agent/runtime.proto\"\xad\x02\n" +
	"\rAgentSnapshot\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x123\n" +
	"\asent_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12)\n" +
	"\x04host\x18\x03 \x01(\v2\x15.patchbase.agent.HostR\x04host\x12+\n" +
	"\x05repos\x18\x04 \x03(\v2\x15.patchbase.agent.RepoR\x05repos\x124\n" +
	"\bpackages\x18\x05 \x03(\v2\x18.patchbase.agent.PackageR\bpackages\x122\n" +
	"\aruntime\x18\x06 \x01(\v2\x18.patchbase.agent.RuntimeR\aruntimeB\x1eZ\x1cgo.patchbase.net/proto/agentb\x06proto3"

var (
	file_patchbase_agent_snapshot_proto_rawDescOnce sync.Once
	file_patchbase_agent_snapshot_proto_rawDescData []byte
)

func file_patchbase_agent_snapshot_proto_rawDescGZIP() []byte {
	file_patchbase_agent_snapshot_proto_rawDescOnce.Do(func() {
		file_patchbase_agent_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_patchbase_agent_snapshot_proto_rawDesc), len(file_patchbase_agent_snapshot_proto_rawDesc)))
	})
	return file_patchbase_agent_snapshot_proto_rawDescData
}

var file_patchbase_agent_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_patchbase_agent_snapshot_proto_goTypes = []any{
	(*AgentSnapshot)(nil),         // 0: patchbase.agent.AgentSnapshot
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*Host)(nil),                  // 2: patchbase.agent.Host
	(*Repo)(nil),                  // 3: patchbase.agent.Repo
	(*Package)(nil),               // 4: patchbase.agent.Package
	(*Runtime)(nil),               // 5: patchbase.agent.Runtime
}
var file_patchbase_agent_snapshot_proto_depIdxs = []int32{
	1, // 0: patchbase.agent.AgentSnapshot.sent_at:type_name -> google.protobuf.Timestamp
	2, // 1: patchbase.agent.AgentSnapshot.host:type_name -> patchbase.agent.Host
	3, // 2: patchbase.agent.AgentSnapshot.repos:type_name -> patchbase.agent.Repo
	4, // 3: patchbase.agent.AgentSnapshot.packages:type_name -> patchbase.agent.Package
	5, // 4: patchbase.agent.AgentSnapshot.runtime:type_name -> patchbase.agent.Runtime
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_patchbase_agent_snapshot_proto_init() }
func file_patchbase_agent_snapshot_proto_init() {
	if File_patchbase_agent_snapshot_proto != nil {
		return
	}
	file_patchbase_agent_host_proto_init()
	file_patchbase_agent_package_proto_init()
	file_patchbase_agent_repo_proto_init()
	file_patchbase_agent_runtime_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_patchbase_agent_snapshot_proto_rawDesc), len(file_patchbase_agent_snapshot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_patchbase_agent_snapshot_proto_goTypes,
		DependencyIndexes: file_patchbase_agent_snapshot_proto_depIdxs,
		MessageInfos:      file_patchbase_agent_snapshot_proto_msgTypes,
	}.Build()
	File_patchbase_agent_snapshot_proto = out.File
	file_patchbase_agent_snapshot_proto_goTypes = nil
	file_patchbase_agent_snapshot_proto_depIdxs = nil
}
