// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sql

import (
	"database/sql"
)

type Advisory struct {
	ID           string
	SourceSystem string
	RawSourceID  string
	SourceUrl    sql.NullString
	Vendor       string
	AdvisoryType string
	Severity     sql.NullString
	Summary      sql.NullString
	Description  sql.NullString
	PublishedAt  sql.NullString
	UpdatedAt    sql.NullString
	EvidenceTier string
	IsSecurity   int64
}

type AdvisoryProductStream struct {
	AdvisoryID      string
	ProductStreamID string
}

type AdvisoryReference struct {
	ID             string
	AdvisoryID     string
	RefType        string
	RefValue       string
	SeverityVendor sql.NullString
	SeverityCvss   sql.NullFloat64
	Title          sql.NullString
	Url            sql.NullString
}

type AdvisorySourceSyncState struct {
	Source         string
	SyncedAt       string
	SourceCursorAt sql.NullString
}

type AffectedPackageRule struct {
	ID                string
	AdvisoryID        string
	ProductStreamID   string
	PackageName       string
	SourceRpm         sql.NullString
	Arch              sql.NullString
	EpochConstraint   sql.NullString
	VersionConstraint sql.NullString
	ReleaseConstraint sql.NullString
	RpmEvrRule        sql.NullString
	Context           string
	EvidenceTier      string
}

type FixedPackage struct {
	ID              string
	AdvisoryID      string
	ProductStreamID string
	PackageName     string
	Epoch           int64
	Version         string
	Release         string
	Arch            sql.NullString
	Nevra           string
	SourceRpm       sql.NullString
	RepoFamily      sql.NullString
	EvidenceTier    string
}

type ProductStream struct {
	ID            string
	Vendor        string
	DistroFamily  string
	DistroName    string
	MajorVersion  int64
	MinorVersion  sql.NullString
	Architecture  sql.NullString
	RepoFamily    string
	RepoIDPattern sql.NullString
	Cpe           sql.NullString
	Status        string
}
