// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sql

import (
	"context"
)

type Querier interface {
	ListAdvisoriesByProductStream(ctx context.Context, productStreamID string) ([]Advisory, error)
	ListAdvisoryReferences(ctx context.Context, advisoryID string) ([]AdvisoryReference, error)
	ListFixedPackagesByProductStream(ctx context.Context, productStreamID string) ([]FixedPackage, error)
	ListProductStreams(ctx context.Context) ([]ProductStream, error)
}

var _ Querier = (*Queries)(nil)
