// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sql

import (
	"context"
)

const listAdvisoriesByProductStream = `-- name: ListAdvisoriesByProductStream :many
SELECT a.id, a.source_system, a.raw_source_id, a.source_url, a.vendor, a.advisory_type, a.severity, a.summary, a.description, a.published_at, a.updated_at, a.evidence_tier, a.is_security
FROM advisories AS a
JOIN advisory_product_streams AS aps ON aps.advisory_id = a.id
WHERE aps.product_stream_id = ?
ORDER BY a.updated_at DESC, a.published_at DESC, a.id
`

func (q *Queries) ListAdvisoriesByProductStream(ctx context.Context, productStreamID string) ([]Advisory, error) {
	rows, err := q.db.QueryContext(ctx, listAdvisoriesByProductStream, productStreamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Advisory
	for rows.Next() {
		var i Advisory
		if err := rows.Scan(
			&i.ID,
			&i.SourceSystem,
			&i.RawSourceID,
			&i.SourceUrl,
			&i.Vendor,
			&i.AdvisoryType,
			&i.Severity,
			&i.Summary,
			&i.Description,
			&i.PublishedAt,
			&i.UpdatedAt,
			&i.EvidenceTier,
			&i.IsSecurity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdvisoryReferences = `-- name: ListAdvisoryReferences :many
SELECT id, advisory_id, ref_type, ref_value, severity_vendor, severity_cvss, title, url
FROM advisory_references
WHERE advisory_id = ?
ORDER BY ref_type, ref_value
`

func (q *Queries) ListAdvisoryReferences(ctx context.Context, advisoryID string) ([]AdvisoryReference, error) {
	rows, err := q.db.QueryContext(ctx, listAdvisoryReferences, advisoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdvisoryReference
	for rows.Next() {
		var i AdvisoryReference
		if err := rows.Scan(
			&i.ID,
			&i.AdvisoryID,
			&i.RefType,
			&i.RefValue,
			&i.SeverityVendor,
			&i.SeverityCvss,
			&i.Title,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFixedPackagesByProductStream = `-- name: ListFixedPackagesByProductStream :many
SELECT id, advisory_id, product_stream_id, package_name, epoch, version, "release", arch, nevra, source_rpm, repo_family, evidence_tier
FROM fixed_packages
WHERE product_stream_id = ?
ORDER BY package_name, epoch, version, release, arch
`

func (q *Queries) ListFixedPackagesByProductStream(ctx context.Context, productStreamID string) ([]FixedPackage, error) {
	rows, err := q.db.QueryContext(ctx, listFixedPackagesByProductStream, productStreamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FixedPackage
	for rows.Next() {
		var i FixedPackage
		if err := rows.Scan(
			&i.ID,
			&i.AdvisoryID,
			&i.ProductStreamID,
			&i.PackageName,
			&i.Epoch,
			&i.Version,
			&i.Release,
			&i.Arch,
			&i.Nevra,
			&i.SourceRpm,
			&i.RepoFamily,
			&i.EvidenceTier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductStreams = `-- name: ListProductStreams :many
SELECT id, vendor, distro_family, distro_name, major_version, minor_version, architecture, repo_family, repo_id_pattern, cpe, status
FROM product_streams
ORDER BY vendor, distro_name, major_version, minor_version, architecture
`

func (q *Queries) ListProductStreams(ctx context.Context) ([]ProductStream, error) {
	rows, err := q.db.QueryContext(ctx, listProductStreams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductStream
	for rows.Next() {
		var i ProductStream
		if err := rows.Scan(
			&i.ID,
			&i.Vendor,
			&i.DistroFamily,
			&i.DistroName,
			&i.MajorVersion,
			&i.MinorVersion,
			&i.Architecture,
			&i.RepoFamily,
			&i.RepoIDPattern,
			&i.Cpe,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
