// Code generated by MockGen. DO NOT EDIT.
// Source: bazel-out/k8-fastbuild/bin/internal/mock/gopath/src/go.patchbase.net/server/internal/sql/querier.go
//
// Generated by this command:
//
//	mockgen -source bazel-out/k8-fastbuild/bin/internal/mock/gopath/src/go.patchbase.net/server/internal/sql/querier.go -package mock -mock_names Querier=MockSQLQuerier
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	sql "go.patchbase.net/server/internal/sql"
	utils "go.patchbase.net/server/internal/utils"
	gomock "go.uber.org/mock/gomock"
)

// MockSQLQuerier is a mock of Querier interface.
type MockSQLQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockSQLQuerierMockRecorder
	isgomock struct{}
}

// MockSQLQuerierMockRecorder is the mock recorder for MockSQLQuerier.
type MockSQLQuerierMockRecorder struct {
	mock *MockSQLQuerier
}

// NewMockSQLQuerier creates a new mock instance.
func NewMockSQLQuerier(ctrl *gomock.Controller) *MockSQLQuerier {
	mock := &MockSQLQuerier{ctrl: ctrl}
	mock.recorder = &MockSQLQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQLQuerier) EXPECT() *MockSQLQuerierMockRecorder {
	return m.recorder
}

// ApproveHostByID mocks base method.
func (m *MockSQLQuerier) ApproveHostByID(ctx context.Context, id string) (sql.Host, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveHostByID", ctx, id)
	ret0, _ := ret[0].(sql.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApproveHostByID indicates an expected call of ApproveHostByID.
func (mr *MockSQLQuerierMockRecorder) ApproveHostByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveHostByID", reflect.TypeOf((*MockSQLQuerier)(nil).ApproveHostByID), ctx, id)
}

// ClearHostLastSnapshotByID mocks base method.
func (m *MockSQLQuerier) ClearHostLastSnapshotByID(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearHostLastSnapshotByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearHostLastSnapshotByID indicates an expected call of ClearHostLastSnapshotByID.
func (mr *MockSQLQuerierMockRecorder) ClearHostLastSnapshotByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearHostLastSnapshotByID", reflect.TypeOf((*MockSQLQuerier)(nil).ClearHostLastSnapshotByID), ctx, id)
}

// CompleteInitialSetupForUser mocks base method.
func (m *MockSQLQuerier) CompleteInitialSetupForUser(ctx context.Context, arg sql.CompleteInitialSetupForUserParams) (sql.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteInitialSetupForUser", ctx, arg)
	ret0, _ := ret[0].(sql.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteInitialSetupForUser indicates an expected call of CompleteInitialSetupForUser.
func (mr *MockSQLQuerierMockRecorder) CompleteInitialSetupForUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteInitialSetupForUser", reflect.TypeOf((*MockSQLQuerier)(nil).CompleteInitialSetupForUser), ctx, arg)
}

// CountAuditLogs mocks base method.
func (m *MockSQLQuerier) CountAuditLogs(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAuditLogs", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAuditLogs indicates an expected call of CountAuditLogs.
func (mr *MockSQLQuerierMockRecorder) CountAuditLogs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAuditLogs", reflect.TypeOf((*MockSQLQuerier)(nil).CountAuditLogs), ctx)
}

// CountAuditLogsFiltered mocks base method.
func (m *MockSQLQuerier) CountAuditLogsFiltered(ctx context.Context, arg sql.CountAuditLogsFilteredParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAuditLogsFiltered", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAuditLogsFiltered indicates an expected call of CountAuditLogsFiltered.
func (mr *MockSQLQuerierMockRecorder) CountAuditLogsFiltered(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAuditLogsFiltered", reflect.TypeOf((*MockSQLQuerier)(nil).CountAuditLogsFiltered), ctx, arg)
}

// CreateAdminUser mocks base method.
func (m *MockSQLQuerier) CreateAdminUser(ctx context.Context, arg sql.CreateAdminUserParams) (sql.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdminUser", ctx, arg)
	ret0, _ := ret[0].(sql.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAdminUser indicates an expected call of CreateAdminUser.
func (mr *MockSQLQuerierMockRecorder) CreateAdminUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdminUser", reflect.TypeOf((*MockSQLQuerier)(nil).CreateAdminUser), ctx, arg)
}

// CreateSetting mocks base method.
func (m *MockSQLQuerier) CreateSetting(ctx context.Context, arg sql.CreateSettingParams) (sql.Setting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSetting", ctx, arg)
	ret0, _ := ret[0].(sql.Setting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSetting indicates an expected call of CreateSetting.
func (mr *MockSQLQuerierMockRecorder) CreateSetting(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSetting", reflect.TypeOf((*MockSQLQuerier)(nil).CreateSetting), ctx, arg)
}

// CreateSettingIfAbsent mocks base method.
func (m *MockSQLQuerier) CreateSettingIfAbsent(ctx context.Context, arg sql.CreateSettingIfAbsentParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSettingIfAbsent", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSettingIfAbsent indicates an expected call of CreateSettingIfAbsent.
func (mr *MockSQLQuerierMockRecorder) CreateSettingIfAbsent(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSettingIfAbsent", reflect.TypeOf((*MockSQLQuerier)(nil).CreateSettingIfAbsent), ctx, arg)
}

// DeleteAdvisoriesWithoutStreams mocks base method.
func (m *MockSQLQuerier) DeleteAdvisoriesWithoutStreams(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAdvisoriesWithoutStreams", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAdvisoriesWithoutStreams indicates an expected call of DeleteAdvisoriesWithoutStreams.
func (mr *MockSQLQuerierMockRecorder) DeleteAdvisoriesWithoutStreams(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAdvisoriesWithoutStreams", reflect.TypeOf((*MockSQLQuerier)(nil).DeleteAdvisoriesWithoutStreams), ctx)
}

// DeleteAdvisoryProductStreamsByStreamIDs mocks base method.
func (m *MockSQLQuerier) DeleteAdvisoryProductStreamsByStreamIDs(ctx context.Context, dollar_1 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAdvisoryProductStreamsByStreamIDs", ctx, dollar_1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAdvisoryProductStreamsByStreamIDs indicates an expected call of DeleteAdvisoryProductStreamsByStreamIDs.
func (mr *MockSQLQuerierMockRecorder) DeleteAdvisoryProductStreamsByStreamIDs(ctx, dollar_1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAdvisoryProductStreamsByStreamIDs", reflect.TypeOf((*MockSQLQuerier)(nil).DeleteAdvisoryProductStreamsByStreamIDs), ctx, dollar_1)
}

// DeleteAdvisoryReferencesByStreamIDs mocks base method.
func (m *MockSQLQuerier) DeleteAdvisoryReferencesByStreamIDs(ctx context.Context, dollar_1 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAdvisoryReferencesByStreamIDs", ctx, dollar_1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAdvisoryReferencesByStreamIDs indicates an expected call of DeleteAdvisoryReferencesByStreamIDs.
func (mr *MockSQLQuerierMockRecorder) DeleteAdvisoryReferencesByStreamIDs(ctx, dollar_1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAdvisoryReferencesByStreamIDs", reflect.TypeOf((*MockSQLQuerier)(nil).DeleteAdvisoryReferencesByStreamIDs), ctx, dollar_1)
}

// DeleteAffectedPackageRulesByStreamIDs mocks base method.
func (m *MockSQLQuerier) DeleteAffectedPackageRulesByStreamIDs(ctx context.Context, dollar_1 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAffectedPackageRulesByStreamIDs", ctx, dollar_1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAffectedPackageRulesByStreamIDs indicates an expected call of DeleteAffectedPackageRulesByStreamIDs.
func (mr *MockSQLQuerierMockRecorder) DeleteAffectedPackageRulesByStreamIDs(ctx, dollar_1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAffectedPackageRulesByStreamIDs", reflect.TypeOf((*MockSQLQuerier)(nil).DeleteAffectedPackageRulesByStreamIDs), ctx, dollar_1)
}

// DeleteDecisionRecordsBySnapshot mocks base method.
func (m *MockSQLQuerier) DeleteDecisionRecordsBySnapshot(ctx context.Context, snapshotID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDecisionRecordsBySnapshot", ctx, snapshotID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDecisionRecordsBySnapshot indicates an expected call of DeleteDecisionRecordsBySnapshot.
func (mr *MockSQLQuerierMockRecorder) DeleteDecisionRecordsBySnapshot(ctx, snapshotID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDecisionRecordsBySnapshot", reflect.TypeOf((*MockSQLQuerier)(nil).DeleteDecisionRecordsBySnapshot), ctx, snapshotID)
}

// DeleteFixedPackagesByStreamIDs mocks base method.
func (m *MockSQLQuerier) DeleteFixedPackagesByStreamIDs(ctx context.Context, dollar_1 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFixedPackagesByStreamIDs", ctx, dollar_1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFixedPackagesByStreamIDs indicates an expected call of DeleteFixedPackagesByStreamIDs.
func (mr *MockSQLQuerierMockRecorder) DeleteFixedPackagesByStreamIDs(ctx, dollar_1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFixedPackagesByStreamIDs", reflect.TypeOf((*MockSQLQuerier)(nil).DeleteFixedPackagesByStreamIDs), ctx, dollar_1)
}

// DeleteHostAccessTokensByHostID mocks base method.
func (m *MockSQLQuerier) DeleteHostAccessTokensByHostID(ctx context.Context, hostID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHostAccessTokensByHostID", ctx, hostID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteHostAccessTokensByHostID indicates an expected call of DeleteHostAccessTokensByHostID.
func (mr *MockSQLQuerierMockRecorder) DeleteHostAccessTokensByHostID(ctx, hostID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHostAccessTokensByHostID", reflect.TypeOf((*MockSQLQuerier)(nil).DeleteHostAccessTokensByHostID), ctx, hostID)
}

// DeleteHostByID mocks base method.
func (m *MockSQLQuerier) DeleteHostByID(ctx context.Context, id string) (sql.Host, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHostByID", ctx, id)
	ret0, _ := ret[0].(sql.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteHostByID indicates an expected call of DeleteHostByID.
func (mr *MockSQLQuerierMockRecorder) DeleteHostByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHostByID", reflect.TypeOf((*MockSQLQuerier)(nil).DeleteHostByID), ctx, id)
}

// DeleteHostCurrentStateByHostID mocks base method.
func (m *MockSQLQuerier) DeleteHostCurrentStateByHostID(ctx context.Context, hostID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHostCurrentStateByHostID", ctx, hostID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteHostCurrentStateByHostID indicates an expected call of DeleteHostCurrentStateByHostID.
func (mr *MockSQLQuerierMockRecorder) DeleteHostCurrentStateByHostID(ctx, hostID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHostCurrentStateByHostID", reflect.TypeOf((*MockSQLQuerier)(nil).DeleteHostCurrentStateByHostID), ctx, hostID)
}

// DeleteHostSnapshotsByHostID mocks base method.
func (m *MockSQLQuerier) DeleteHostSnapshotsByHostID(ctx context.Context, hostID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHostSnapshotsByHostID", ctx, hostID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteHostSnapshotsByHostID indicates an expected call of DeleteHostSnapshotsByHostID.
func (mr *MockSQLQuerierMockRecorder) DeleteHostSnapshotsByHostID(ctx, hostID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHostSnapshotsByHostID", reflect.TypeOf((*MockSQLQuerier)(nil).DeleteHostSnapshotsByHostID), ctx, hostID)
}

// DeleteProductStreamsByIDs mocks base method.
func (m *MockSQLQuerier) DeleteProductStreamsByIDs(ctx context.Context, dollar_1 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProductStreamsByIDs", ctx, dollar_1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProductStreamsByIDs indicates an expected call of DeleteProductStreamsByIDs.
func (mr *MockSQLQuerierMockRecorder) DeleteProductStreamsByIDs(ctx, dollar_1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProductStreamsByIDs", reflect.TypeOf((*MockSQLQuerier)(nil).DeleteProductStreamsByIDs), ctx, dollar_1)
}

// GetActiveHostAccessTokenByHash mocks base method.
func (m *MockSQLQuerier) GetActiveHostAccessTokenByHash(ctx context.Context, tokenHash string) (sql.HostAccessToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveHostAccessTokenByHash", ctx, tokenHash)
	ret0, _ := ret[0].(sql.HostAccessToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveHostAccessTokenByHash indicates an expected call of GetActiveHostAccessTokenByHash.
func (mr *MockSQLQuerierMockRecorder) GetActiveHostAccessTokenByHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveHostAccessTokenByHash", reflect.TypeOf((*MockSQLQuerier)(nil).GetActiveHostAccessTokenByHash), ctx, tokenHash)
}

// GetActiveRegistrationTokenByHash mocks base method.
func (m *MockSQLQuerier) GetActiveRegistrationTokenByHash(ctx context.Context, tokenHash string) (sql.RegistrationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveRegistrationTokenByHash", ctx, tokenHash)
	ret0, _ := ret[0].(sql.RegistrationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveRegistrationTokenByHash indicates an expected call of GetActiveRegistrationTokenByHash.
func (mr *MockSQLQuerierMockRecorder) GetActiveRegistrationTokenByHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveRegistrationTokenByHash", reflect.TypeOf((*MockSQLQuerier)(nil).GetActiveRegistrationTokenByHash), ctx, tokenHash)
}

// GetAdminUser mocks base method.
func (m *MockSQLQuerier) GetAdminUser(ctx context.Context) (sql.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminUser", ctx)
	ret0, _ := ret[0].(sql.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdminUser indicates an expected call of GetAdminUser.
func (mr *MockSQLQuerierMockRecorder) GetAdminUser(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminUser", reflect.TypeOf((*MockSQLQuerier)(nil).GetAdminUser), ctx)
}

// GetAdvisory mocks base method.
func (m *MockSQLQuerier) GetAdvisory(ctx context.Context, id string) (sql.Advisory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdvisory", ctx, id)
	ret0, _ := ret[0].(sql.Advisory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdvisory indicates an expected call of GetAdvisory.
func (mr *MockSQLQuerierMockRecorder) GetAdvisory(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdvisory", reflect.TypeOf((*MockSQLQuerier)(nil).GetAdvisory), ctx, id)
}

// GetAdvisoryScope mocks base method.
func (m *MockSQLQuerier) GetAdvisoryScope(ctx context.Context, scopeKey string) (sql.AdvisoryScope, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdvisoryScope", ctx, scopeKey)
	ret0, _ := ret[0].(sql.AdvisoryScope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdvisoryScope indicates an expected call of GetAdvisoryScope.
func (mr *MockSQLQuerierMockRecorder) GetAdvisoryScope(ctx, scopeKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdvisoryScope", reflect.TypeOf((*MockSQLQuerier)(nil).GetAdvisoryScope), ctx, scopeKey)
}

// GetDashboardOverview mocks base method.
func (m *MockSQLQuerier) GetDashboardOverview(ctx context.Context) (sql.GetDashboardOverviewRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDashboardOverview", ctx)
	ret0, _ := ret[0].(sql.GetDashboardOverviewRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDashboardOverview indicates an expected call of GetDashboardOverview.
func (mr *MockSQLQuerierMockRecorder) GetDashboardOverview(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDashboardOverview", reflect.TypeOf((*MockSQLQuerier)(nil).GetDashboardOverview), ctx)
}

// GetHostByID mocks base method.
func (m *MockSQLQuerier) GetHostByID(ctx context.Context, id string) (sql.Host, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostByID", ctx, id)
	ret0, _ := ret[0].(sql.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHostByID indicates an expected call of GetHostByID.
func (mr *MockSQLQuerierMockRecorder) GetHostByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostByID", reflect.TypeOf((*MockSQLQuerier)(nil).GetHostByID), ctx, id)
}

// GetHostSnapshot mocks base method.
func (m *MockSQLQuerier) GetHostSnapshot(ctx context.Context, id string) (sql.HostSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostSnapshot", ctx, id)
	ret0, _ := ret[0].(sql.HostSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHostSnapshot indicates an expected call of GetHostSnapshot.
func (mr *MockSQLQuerierMockRecorder) GetHostSnapshot(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostSnapshot", reflect.TypeOf((*MockSQLQuerier)(nil).GetHostSnapshot), ctx, id)
}

// GetHostWithStateByID mocks base method.
func (m *MockSQLQuerier) GetHostWithStateByID(ctx context.Context, id string) (sql.GetHostWithStateByIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostWithStateByID", ctx, id)
	ret0, _ := ret[0].(sql.GetHostWithStateByIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHostWithStateByID indicates an expected call of GetHostWithStateByID.
func (mr *MockSQLQuerierMockRecorder) GetHostWithStateByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostWithStateByID", reflect.TypeOf((*MockSQLQuerier)(nil).GetHostWithStateByID), ctx, id)
}

// GetLatestHostSnapshotByHostID mocks base method.
func (m *MockSQLQuerier) GetLatestHostSnapshotByHostID(ctx context.Context, hostID string) (sql.HostSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestHostSnapshotByHostID", ctx, hostID)
	ret0, _ := ret[0].(sql.HostSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestHostSnapshotByHostID indicates an expected call of GetLatestHostSnapshotByHostID.
func (mr *MockSQLQuerierMockRecorder) GetLatestHostSnapshotByHostID(ctx, hostID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestHostSnapshotByHostID", reflect.TypeOf((*MockSQLQuerier)(nil).GetLatestHostSnapshotByHostID), ctx, hostID)
}

// GetSSHPullConfigByHostID mocks base method.
func (m *MockSQLQuerier) GetSSHPullConfigByHostID(ctx context.Context, hostID string) (sql.HostSshPull, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSSHPullConfigByHostID", ctx, hostID)
	ret0, _ := ret[0].(sql.HostSshPull)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSSHPullConfigByHostID indicates an expected call of GetSSHPullConfigByHostID.
func (mr *MockSQLQuerierMockRecorder) GetSSHPullConfigByHostID(ctx, hostID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSSHPullConfigByHostID", reflect.TypeOf((*MockSQLQuerier)(nil).GetSSHPullConfigByHostID), ctx, hostID)
}

// GetSetting mocks base method.
func (m *MockSQLQuerier) GetSetting(ctx context.Context, key string) (sql.Setting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetting", ctx, key)
	ret0, _ := ret[0].(sql.Setting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetting indicates an expected call of GetSetting.
func (mr *MockSQLQuerierMockRecorder) GetSetting(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetting", reflect.TypeOf((*MockSQLQuerier)(nil).GetSetting), ctx, key)
}

// GetUserByEmail mocks base method.
func (m *MockSQLQuerier) GetUserByEmail(ctx context.Context, email string) (sql.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(sql.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockSQLQuerierMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockSQLQuerier)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockSQLQuerier) GetUserByID(ctx context.Context, id string) (sql.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(sql.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockSQLQuerierMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockSQLQuerier)(nil).GetUserByID), ctx, id)
}

// InsertAdvisoryProductStream mocks base method.
func (m *MockSQLQuerier) InsertAdvisoryProductStream(ctx context.Context, arg sql.InsertAdvisoryProductStreamParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAdvisoryProductStream", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertAdvisoryProductStream indicates an expected call of InsertAdvisoryProductStream.
func (mr *MockSQLQuerierMockRecorder) InsertAdvisoryProductStream(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAdvisoryProductStream", reflect.TypeOf((*MockSQLQuerier)(nil).InsertAdvisoryProductStream), ctx, arg)
}

// InsertAdvisoryReference mocks base method.
func (m *MockSQLQuerier) InsertAdvisoryReference(ctx context.Context, arg sql.InsertAdvisoryReferenceParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAdvisoryReference", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertAdvisoryReference indicates an expected call of InsertAdvisoryReference.
func (mr *MockSQLQuerierMockRecorder) InsertAdvisoryReference(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAdvisoryReference", reflect.TypeOf((*MockSQLQuerier)(nil).InsertAdvisoryReference), ctx, arg)
}

// InsertAdvisoryScopeIfNotExists mocks base method.
func (m *MockSQLQuerier) InsertAdvisoryScopeIfNotExists(ctx context.Context, arg sql.InsertAdvisoryScopeIfNotExistsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAdvisoryScopeIfNotExists", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertAdvisoryScopeIfNotExists indicates an expected call of InsertAdvisoryScopeIfNotExists.
func (mr *MockSQLQuerierMockRecorder) InsertAdvisoryScopeIfNotExists(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAdvisoryScopeIfNotExists", reflect.TypeOf((*MockSQLQuerier)(nil).InsertAdvisoryScopeIfNotExists), ctx, arg)
}

// InsertAffectedPackageRule mocks base method.
func (m *MockSQLQuerier) InsertAffectedPackageRule(ctx context.Context, arg sql.InsertAffectedPackageRuleParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAffectedPackageRule", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertAffectedPackageRule indicates an expected call of InsertAffectedPackageRule.
func (mr *MockSQLQuerierMockRecorder) InsertAffectedPackageRule(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAffectedPackageRule", reflect.TypeOf((*MockSQLQuerier)(nil).InsertAffectedPackageRule), ctx, arg)
}

// InsertAgentHost mocks base method.
func (m *MockSQLQuerier) InsertAgentHost(ctx context.Context, arg sql.InsertAgentHostParams) (sql.Host, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAgentHost", ctx, arg)
	ret0, _ := ret[0].(sql.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertAgentHost indicates an expected call of InsertAgentHost.
func (mr *MockSQLQuerierMockRecorder) InsertAgentHost(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAgentHost", reflect.TypeOf((*MockSQLQuerier)(nil).InsertAgentHost), ctx, arg)
}

// InsertAuditLog mocks base method.
func (m *MockSQLQuerier) InsertAuditLog(ctx context.Context, arg sql.InsertAuditLogParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAuditLog", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertAuditLog indicates an expected call of InsertAuditLog.
func (mr *MockSQLQuerierMockRecorder) InsertAuditLog(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAuditLog", reflect.TypeOf((*MockSQLQuerier)(nil).InsertAuditLog), ctx, arg)
}

// InsertDecisionRecord mocks base method.
func (m *MockSQLQuerier) InsertDecisionRecord(ctx context.Context, arg sql.InsertDecisionRecordParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertDecisionRecord", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertDecisionRecord indicates an expected call of InsertDecisionRecord.
func (mr *MockSQLQuerierMockRecorder) InsertDecisionRecord(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertDecisionRecord", reflect.TypeOf((*MockSQLQuerier)(nil).InsertDecisionRecord), ctx, arg)
}

// InsertFixedPackage mocks base method.
func (m *MockSQLQuerier) InsertFixedPackage(ctx context.Context, arg sql.InsertFixedPackageParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertFixedPackage", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertFixedPackage indicates an expected call of InsertFixedPackage.
func (mr *MockSQLQuerierMockRecorder) InsertFixedPackage(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertFixedPackage", reflect.TypeOf((*MockSQLQuerier)(nil).InsertFixedPackage), ctx, arg)
}

// InsertHostAccessToken mocks base method.
func (m *MockSQLQuerier) InsertHostAccessToken(ctx context.Context, arg sql.InsertHostAccessTokenParams) (sql.HostAccessToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertHostAccessToken", ctx, arg)
	ret0, _ := ret[0].(sql.HostAccessToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertHostAccessToken indicates an expected call of InsertHostAccessToken.
func (mr *MockSQLQuerierMockRecorder) InsertHostAccessToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertHostAccessToken", reflect.TypeOf((*MockSQLQuerier)(nil).InsertHostAccessToken), ctx, arg)
}

// InsertHostSSHPullJob mocks base method.
func (m *MockSQLQuerier) InsertHostSSHPullJob(ctx context.Context, arg sql.InsertHostSSHPullJobParams) (sql.HostSshPullJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertHostSSHPullJob", ctx, arg)
	ret0, _ := ret[0].(sql.HostSshPullJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertHostSSHPullJob indicates an expected call of InsertHostSSHPullJob.
func (mr *MockSQLQuerierMockRecorder) InsertHostSSHPullJob(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertHostSSHPullJob", reflect.TypeOf((*MockSQLQuerier)(nil).InsertHostSSHPullJob), ctx, arg)
}

// InsertHostSnapshot mocks base method.
func (m *MockSQLQuerier) InsertHostSnapshot(ctx context.Context, arg sql.InsertHostSnapshotParams) (sql.HostSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertHostSnapshot", ctx, arg)
	ret0, _ := ret[0].(sql.HostSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertHostSnapshot indicates an expected call of InsertHostSnapshot.
func (mr *MockSQLQuerierMockRecorder) InsertHostSnapshot(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertHostSnapshot", reflect.TypeOf((*MockSQLQuerier)(nil).InsertHostSnapshot), ctx, arg)
}

// InsertManualHost mocks base method.
func (m *MockSQLQuerier) InsertManualHost(ctx context.Context, arg sql.InsertManualHostParams) (sql.Host, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertManualHost", ctx, arg)
	ret0, _ := ret[0].(sql.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertManualHost indicates an expected call of InsertManualHost.
func (mr *MockSQLQuerierMockRecorder) InsertManualHost(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertManualHost", reflect.TypeOf((*MockSQLQuerier)(nil).InsertManualHost), ctx, arg)
}

// InsertRegistrationToken mocks base method.
func (m *MockSQLQuerier) InsertRegistrationToken(ctx context.Context, arg sql.InsertRegistrationTokenParams) (sql.RegistrationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRegistrationToken", ctx, arg)
	ret0, _ := ret[0].(sql.RegistrationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertRegistrationToken indicates an expected call of InsertRegistrationToken.
func (mr *MockSQLQuerierMockRecorder) InsertRegistrationToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRegistrationToken", reflect.TypeOf((*MockSQLQuerier)(nil).InsertRegistrationToken), ctx, arg)
}

// InsertSSHHost mocks base method.
func (m *MockSQLQuerier) InsertSSHHost(ctx context.Context, arg sql.InsertSSHHostParams) (sql.InsertSSHHostRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSSHHost", ctx, arg)
	ret0, _ := ret[0].(sql.InsertSSHHostRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertSSHHost indicates an expected call of InsertSSHHost.
func (mr *MockSQLQuerierMockRecorder) InsertSSHHost(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSSHHost", reflect.TypeOf((*MockSQLQuerier)(nil).InsertSSHHost), ctx, arg)
}

// ListAdminUsers mocks base method.
func (m *MockSQLQuerier) ListAdminUsers(ctx context.Context) ([]sql.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAdminUsers", ctx)
	ret0, _ := ret[0].([]sql.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAdminUsers indicates an expected call of ListAdminUsers.
func (mr *MockSQLQuerierMockRecorder) ListAdminUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAdminUsers", reflect.TypeOf((*MockSQLQuerier)(nil).ListAdminUsers), ctx)
}

// ListAdvisoriesByStreamIDs mocks base method.
func (m *MockSQLQuerier) ListAdvisoriesByStreamIDs(ctx context.Context, dollar_1 []string) ([]sql.Advisory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAdvisoriesByStreamIDs", ctx, dollar_1)
	ret0, _ := ret[0].([]sql.Advisory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAdvisoriesByStreamIDs indicates an expected call of ListAdvisoriesByStreamIDs.
func (mr *MockSQLQuerierMockRecorder) ListAdvisoriesByStreamIDs(ctx, dollar_1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAdvisoriesByStreamIDs", reflect.TypeOf((*MockSQLQuerier)(nil).ListAdvisoriesByStreamIDs), ctx, dollar_1)
}

// ListAdvisoryProductStreamsByStreamIDs mocks base method.
func (m *MockSQLQuerier) ListAdvisoryProductStreamsByStreamIDs(ctx context.Context, dollar_1 []string) ([]sql.AdvisoryProductStream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAdvisoryProductStreamsByStreamIDs", ctx, dollar_1)
	ret0, _ := ret[0].([]sql.AdvisoryProductStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAdvisoryProductStreamsByStreamIDs indicates an expected call of ListAdvisoryProductStreamsByStreamIDs.
func (mr *MockSQLQuerierMockRecorder) ListAdvisoryProductStreamsByStreamIDs(ctx, dollar_1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAdvisoryProductStreamsByStreamIDs", reflect.TypeOf((*MockSQLQuerier)(nil).ListAdvisoryProductStreamsByStreamIDs), ctx, dollar_1)
}

// ListAdvisoryReferencesByStreamIDs mocks base method.
func (m *MockSQLQuerier) ListAdvisoryReferencesByStreamIDs(ctx context.Context, dollar_1 []string) ([]sql.AdvisoryReference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAdvisoryReferencesByStreamIDs", ctx, dollar_1)
	ret0, _ := ret[0].([]sql.AdvisoryReference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAdvisoryReferencesByStreamIDs indicates an expected call of ListAdvisoryReferencesByStreamIDs.
func (mr *MockSQLQuerierMockRecorder) ListAdvisoryReferencesByStreamIDs(ctx, dollar_1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAdvisoryReferencesByStreamIDs", reflect.TypeOf((*MockSQLQuerier)(nil).ListAdvisoryReferencesByStreamIDs), ctx, dollar_1)
}

// ListAdvisoryScopeStats mocks base method.
func (m *MockSQLQuerier) ListAdvisoryScopeStats(ctx context.Context) ([]sql.ListAdvisoryScopeStatsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAdvisoryScopeStats", ctx)
	ret0, _ := ret[0].([]sql.ListAdvisoryScopeStatsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAdvisoryScopeStats indicates an expected call of ListAdvisoryScopeStats.
func (mr *MockSQLQuerierMockRecorder) ListAdvisoryScopeStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAdvisoryScopeStats", reflect.TypeOf((*MockSQLQuerier)(nil).ListAdvisoryScopeStats), ctx)
}

// ListAdvisoryScopes mocks base method.
func (m *MockSQLQuerier) ListAdvisoryScopes(ctx context.Context) ([]sql.AdvisoryScope, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAdvisoryScopes", ctx)
	ret0, _ := ret[0].([]sql.AdvisoryScope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAdvisoryScopes indicates an expected call of ListAdvisoryScopes.
func (mr *MockSQLQuerierMockRecorder) ListAdvisoryScopes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAdvisoryScopes", reflect.TypeOf((*MockSQLQuerier)(nil).ListAdvisoryScopes), ctx)
}

// ListAffectedPackageRulesByStreamIDs mocks base method.
func (m *MockSQLQuerier) ListAffectedPackageRulesByStreamIDs(ctx context.Context, dollar_1 []string) ([]sql.AffectedPackageRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAffectedPackageRulesByStreamIDs", ctx, dollar_1)
	ret0, _ := ret[0].([]sql.AffectedPackageRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAffectedPackageRulesByStreamIDs indicates an expected call of ListAffectedPackageRulesByStreamIDs.
func (mr *MockSQLQuerierMockRecorder) ListAffectedPackageRulesByStreamIDs(ctx, dollar_1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAffectedPackageRulesByStreamIDs", reflect.TypeOf((*MockSQLQuerier)(nil).ListAffectedPackageRulesByStreamIDs), ctx, dollar_1)
}

// ListApprovedSSHHosts mocks base method.
func (m *MockSQLQuerier) ListApprovedSSHHosts(ctx context.Context) ([]sql.ListApprovedSSHHostsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListApprovedSSHHosts", ctx)
	ret0, _ := ret[0].([]sql.ListApprovedSSHHostsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListApprovedSSHHosts indicates an expected call of ListApprovedSSHHosts.
func (mr *MockSQLQuerierMockRecorder) ListApprovedSSHHosts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListApprovedSSHHosts", reflect.TypeOf((*MockSQLQuerier)(nil).ListApprovedSSHHosts), ctx)
}

// ListAuditLogs mocks base method.
func (m *MockSQLQuerier) ListAuditLogs(ctx context.Context, arg sql.ListAuditLogsParams) ([]sql.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAuditLogs", ctx, arg)
	ret0, _ := ret[0].([]sql.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAuditLogs indicates an expected call of ListAuditLogs.
func (mr *MockSQLQuerierMockRecorder) ListAuditLogs(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAuditLogs", reflect.TypeOf((*MockSQLQuerier)(nil).ListAuditLogs), ctx, arg)
}

// ListAuditLogsFiltered mocks base method.
func (m *MockSQLQuerier) ListAuditLogsFiltered(ctx context.Context, arg sql.ListAuditLogsFilteredParams) ([]sql.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAuditLogsFiltered", ctx, arg)
	ret0, _ := ret[0].([]sql.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAuditLogsFiltered indicates an expected call of ListAuditLogsFiltered.
func (mr *MockSQLQuerierMockRecorder) ListAuditLogsFiltered(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAuditLogsFiltered", reflect.TypeOf((*MockSQLQuerier)(nil).ListAuditLogsFiltered), ctx, arg)
}

// ListDecisionPageRowsBySnapshot mocks base method.
func (m *MockSQLQuerier) ListDecisionPageRowsBySnapshot(ctx context.Context, snapshotID string) ([]sql.ListDecisionPageRowsBySnapshotRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDecisionPageRowsBySnapshot", ctx, snapshotID)
	ret0, _ := ret[0].([]sql.ListDecisionPageRowsBySnapshotRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDecisionPageRowsBySnapshot indicates an expected call of ListDecisionPageRowsBySnapshot.
func (mr *MockSQLQuerierMockRecorder) ListDecisionPageRowsBySnapshot(ctx, snapshotID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDecisionPageRowsBySnapshot", reflect.TypeOf((*MockSQLQuerier)(nil).ListDecisionPageRowsBySnapshot), ctx, snapshotID)
}

// ListFixedPackagesByStreamIDs mocks base method.
func (m *MockSQLQuerier) ListFixedPackagesByStreamIDs(ctx context.Context, dollar_1 []string) ([]sql.FixedPackage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFixedPackagesByStreamIDs", ctx, dollar_1)
	ret0, _ := ret[0].([]sql.FixedPackage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFixedPackagesByStreamIDs indicates an expected call of ListFixedPackagesByStreamIDs.
func (mr *MockSQLQuerierMockRecorder) ListFixedPackagesByStreamIDs(ctx, dollar_1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFixedPackagesByStreamIDs", reflect.TypeOf((*MockSQLQuerier)(nil).ListFixedPackagesByStreamIDs), ctx, dollar_1)
}

// ListHostSSHPullJobsByHostID mocks base method.
func (m *MockSQLQuerier) ListHostSSHPullJobsByHostID(ctx context.Context, arg sql.ListHostSSHPullJobsByHostIDParams) ([]sql.HostSshPullJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHostSSHPullJobsByHostID", ctx, arg)
	ret0, _ := ret[0].([]sql.HostSshPullJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListHostSSHPullJobsByHostID indicates an expected call of ListHostSSHPullJobsByHostID.
func (mr *MockSQLQuerierMockRecorder) ListHostSSHPullJobsByHostID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHostSSHPullJobsByHostID", reflect.TypeOf((*MockSQLQuerier)(nil).ListHostSSHPullJobsByHostID), ctx, arg)
}

// ListHostsByAdvisoryScopeKey mocks base method.
func (m *MockSQLQuerier) ListHostsByAdvisoryScopeKey(ctx context.Context, advisoryScopeKey utils.Option[string]) ([]sql.Host, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHostsByAdvisoryScopeKey", ctx, advisoryScopeKey)
	ret0, _ := ret[0].([]sql.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListHostsByAdvisoryScopeKey indicates an expected call of ListHostsByAdvisoryScopeKey.
func (mr *MockSQLQuerierMockRecorder) ListHostsByAdvisoryScopeKey(ctx, advisoryScopeKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHostsByAdvisoryScopeKey", reflect.TypeOf((*MockSQLQuerier)(nil).ListHostsByAdvisoryScopeKey), ctx, advisoryScopeKey)
}

// ListHostsWithState mocks base method.
func (m *MockSQLQuerier) ListHostsWithState(ctx context.Context) ([]sql.ListHostsWithStateRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHostsWithState", ctx)
	ret0, _ := ret[0].([]sql.ListHostsWithStateRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListHostsWithState indicates an expected call of ListHostsWithState.
func (mr *MockSQLQuerierMockRecorder) ListHostsWithState(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHostsWithState", reflect.TypeOf((*MockSQLQuerier)(nil).ListHostsWithState), ctx)
}

// ListPendingHosts mocks base method.
func (m *MockSQLQuerier) ListPendingHosts(ctx context.Context) ([]sql.Host, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingHosts", ctx)
	ret0, _ := ret[0].([]sql.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPendingHosts indicates an expected call of ListPendingHosts.
func (mr *MockSQLQuerierMockRecorder) ListPendingHosts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingHosts", reflect.TypeOf((*MockSQLQuerier)(nil).ListPendingHosts), ctx)
}

// ListProductStreamIDsByVendorAndVersion mocks base method.
func (m *MockSQLQuerier) ListProductStreamIDsByVendorAndVersion(ctx context.Context, arg sql.ListProductStreamIDsByVendorAndVersionParams) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProductStreamIDsByVendorAndVersion", ctx, arg)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProductStreamIDsByVendorAndVersion indicates an expected call of ListProductStreamIDsByVendorAndVersion.
func (mr *MockSQLQuerierMockRecorder) ListProductStreamIDsByVendorAndVersion(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProductStreamIDsByVendorAndVersion", reflect.TypeOf((*MockSQLQuerier)(nil).ListProductStreamIDsByVendorAndVersion), ctx, arg)
}

// ListProductStreams mocks base method.
func (m *MockSQLQuerier) ListProductStreams(ctx context.Context) ([]sql.ProductStream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProductStreams", ctx)
	ret0, _ := ret[0].([]sql.ProductStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProductStreams indicates an expected call of ListProductStreams.
func (mr *MockSQLQuerierMockRecorder) ListProductStreams(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProductStreams", reflect.TypeOf((*MockSQLQuerier)(nil).ListProductStreams), ctx)
}

// ListRecentAdvisories mocks base method.
func (m *MockSQLQuerier) ListRecentAdvisories(ctx context.Context) ([]sql.Advisory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecentAdvisories", ctx)
	ret0, _ := ret[0].([]sql.Advisory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRecentAdvisories indicates an expected call of ListRecentAdvisories.
func (mr *MockSQLQuerierMockRecorder) ListRecentAdvisories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecentAdvisories", reflect.TypeOf((*MockSQLQuerier)(nil).ListRecentAdvisories), ctx)
}

// ListRegistrationTokens mocks base method.
func (m *MockSQLQuerier) ListRegistrationTokens(ctx context.Context) ([]sql.RegistrationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRegistrationTokens", ctx)
	ret0, _ := ret[0].([]sql.RegistrationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRegistrationTokens indicates an expected call of ListRegistrationTokens.
func (mr *MockSQLQuerierMockRecorder) ListRegistrationTokens(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRegistrationTokens", reflect.TypeOf((*MockSQLQuerier)(nil).ListRegistrationTokens), ctx)
}

// LockHost mocks base method.
func (m *MockSQLQuerier) LockHost(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockHost", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockHost indicates an expected call of LockHost.
func (mr *MockSQLQuerierMockRecorder) LockHost(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockHost", reflect.TypeOf((*MockSQLQuerier)(nil).LockHost), ctx, id)
}

// RevokeRegistrationToken mocks base method.
func (m *MockSQLQuerier) RevokeRegistrationToken(ctx context.Context, id string) (sql.RegistrationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeRegistrationToken", ctx, id)
	ret0, _ := ret[0].(sql.RegistrationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeRegistrationToken indicates an expected call of RevokeRegistrationToken.
func (mr *MockSQLQuerierMockRecorder) RevokeRegistrationToken(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRegistrationToken", reflect.TypeOf((*MockSQLQuerier)(nil).RevokeRegistrationToken), ctx, id)
}

// SetSSHPullOnboarded mocks base method.
func (m *MockSQLQuerier) SetSSHPullOnboarded(ctx context.Context, arg sql.SetSSHPullOnboardedParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSSHPullOnboarded", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSSHPullOnboarded indicates an expected call of SetSSHPullOnboarded.
func (mr *MockSQLQuerierMockRecorder) SetSSHPullOnboarded(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSSHPullOnboarded", reflect.TypeOf((*MockSQLQuerier)(nil).SetSSHPullOnboarded), ctx, arg)
}

// TouchHostAccessTokenLastUsed mocks base method.
func (m *MockSQLQuerier) TouchHostAccessTokenLastUsed(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchHostAccessTokenLastUsed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// TouchHostAccessTokenLastUsed indicates an expected call of TouchHostAccessTokenLastUsed.
func (mr *MockSQLQuerierMockRecorder) TouchHostAccessTokenLastUsed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchHostAccessTokenLastUsed", reflect.TypeOf((*MockSQLQuerier)(nil).TouchHostAccessTokenLastUsed), ctx, id)
}

// TouchRegistrationTokenLastUsed mocks base method.
func (m *MockSQLQuerier) TouchRegistrationTokenLastUsed(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchRegistrationTokenLastUsed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// TouchRegistrationTokenLastUsed indicates an expected call of TouchRegistrationTokenLastUsed.
func (mr *MockSQLQuerierMockRecorder) TouchRegistrationTokenLastUsed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchRegistrationTokenLastUsed", reflect.TypeOf((*MockSQLQuerier)(nil).TouchRegistrationTokenLastUsed), ctx, id)
}

// UpdateAdvisoryScopeStatus mocks base method.
func (m *MockSQLQuerier) UpdateAdvisoryScopeStatus(ctx context.Context, arg sql.UpdateAdvisoryScopeStatusParams) (sql.AdvisoryScope, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAdvisoryScopeStatus", ctx, arg)
	ret0, _ := ret[0].(sql.AdvisoryScope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAdvisoryScopeStatus indicates an expected call of UpdateAdvisoryScopeStatus.
func (mr *MockSQLQuerierMockRecorder) UpdateAdvisoryScopeStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAdvisoryScopeStatus", reflect.TypeOf((*MockSQLQuerier)(nil).UpdateAdvisoryScopeStatus), ctx, arg)
}

// UpdateHostAdvisoryScopeKey mocks base method.
func (m *MockSQLQuerier) UpdateHostAdvisoryScopeKey(ctx context.Context, arg sql.UpdateHostAdvisoryScopeKeyParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHostAdvisoryScopeKey", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateHostAdvisoryScopeKey indicates an expected call of UpdateHostAdvisoryScopeKey.
func (mr *MockSQLQuerierMockRecorder) UpdateHostAdvisoryScopeKey(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHostAdvisoryScopeKey", reflect.TypeOf((*MockSQLQuerier)(nil).UpdateHostAdvisoryScopeKey), ctx, arg)
}

// UpdateHostFromSnapshot mocks base method.
func (m *MockSQLQuerier) UpdateHostFromSnapshot(ctx context.Context, arg sql.UpdateHostFromSnapshotParams) (sql.Host, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHostFromSnapshot", ctx, arg)
	ret0, _ := ret[0].(sql.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateHostFromSnapshot indicates an expected call of UpdateHostFromSnapshot.
func (mr *MockSQLQuerierMockRecorder) UpdateHostFromSnapshot(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHostFromSnapshot", reflect.TypeOf((*MockSQLQuerier)(nil).UpdateHostFromSnapshot), ctx, arg)
}

// UpdateHostSSHPullJob mocks base method.
func (m *MockSQLQuerier) UpdateHostSSHPullJob(ctx context.Context, arg sql.UpdateHostSSHPullJobParams) (sql.HostSshPullJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHostSSHPullJob", ctx, arg)
	ret0, _ := ret[0].(sql.HostSshPullJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateHostSSHPullJob indicates an expected call of UpdateHostSSHPullJob.
func (mr *MockSQLQuerierMockRecorder) UpdateHostSSHPullJob(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHostSSHPullJob", reflect.TypeOf((*MockSQLQuerier)(nil).UpdateHostSSHPullJob), ctx, arg)
}

// UpdateSSHPullRun mocks base method.
func (m *MockSQLQuerier) UpdateSSHPullRun(ctx context.Context, arg sql.UpdateSSHPullRunParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSSHPullRun", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSSHPullRun indicates an expected call of UpdateSSHPullRun.
func (mr *MockSQLQuerierMockRecorder) UpdateSSHPullRun(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSSHPullRun", reflect.TypeOf((*MockSQLQuerier)(nil).UpdateSSHPullRun), ctx, arg)
}

// UpdateUserEmail mocks base method.
func (m *MockSQLQuerier) UpdateUserEmail(ctx context.Context, arg sql.UpdateUserEmailParams) (sql.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserEmail", ctx, arg)
	ret0, _ := ret[0].(sql.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserEmail indicates an expected call of UpdateUserEmail.
func (mr *MockSQLQuerierMockRecorder) UpdateUserEmail(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserEmail", reflect.TypeOf((*MockSQLQuerier)(nil).UpdateUserEmail), ctx, arg)
}

// UpdateUserPassword mocks base method.
func (m *MockSQLQuerier) UpdateUserPassword(ctx context.Context, arg sql.UpdateUserPasswordParams) (sql.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPassword", ctx, arg)
	ret0, _ := ret[0].(sql.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserPassword indicates an expected call of UpdateUserPassword.
func (mr *MockSQLQuerierMockRecorder) UpdateUserPassword(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPassword", reflect.TypeOf((*MockSQLQuerier)(nil).UpdateUserPassword), ctx, arg)
}

// UpsertAdvisory mocks base method.
func (m *MockSQLQuerier) UpsertAdvisory(ctx context.Context, arg sql.UpsertAdvisoryParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertAdvisory", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertAdvisory indicates an expected call of UpsertAdvisory.
func (mr *MockSQLQuerierMockRecorder) UpsertAdvisory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertAdvisory", reflect.TypeOf((*MockSQLQuerier)(nil).UpsertAdvisory), ctx, arg)
}

// UpsertAdvisoryScope mocks base method.
func (m *MockSQLQuerier) UpsertAdvisoryScope(ctx context.Context, arg sql.UpsertAdvisoryScopeParams) (sql.AdvisoryScope, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertAdvisoryScope", ctx, arg)
	ret0, _ := ret[0].(sql.AdvisoryScope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertAdvisoryScope indicates an expected call of UpsertAdvisoryScope.
func (mr *MockSQLQuerierMockRecorder) UpsertAdvisoryScope(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertAdvisoryScope", reflect.TypeOf((*MockSQLQuerier)(nil).UpsertAdvisoryScope), ctx, arg)
}

// UpsertAdvisoryScopeStatus mocks base method.
func (m *MockSQLQuerier) UpsertAdvisoryScopeStatus(ctx context.Context, arg sql.UpsertAdvisoryScopeStatusParams) (sql.AdvisoryScope, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertAdvisoryScopeStatus", ctx, arg)
	ret0, _ := ret[0].(sql.AdvisoryScope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertAdvisoryScopeStatus indicates an expected call of UpsertAdvisoryScopeStatus.
func (mr *MockSQLQuerierMockRecorder) UpsertAdvisoryScopeStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertAdvisoryScopeStatus", reflect.TypeOf((*MockSQLQuerier)(nil).UpsertAdvisoryScopeStatus), ctx, arg)
}

// UpsertHostCurrentState mocks base method.
func (m *MockSQLQuerier) UpsertHostCurrentState(ctx context.Context, arg sql.UpsertHostCurrentStateParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertHostCurrentState", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertHostCurrentState indicates an expected call of UpsertHostCurrentState.
func (mr *MockSQLQuerierMockRecorder) UpsertHostCurrentState(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertHostCurrentState", reflect.TypeOf((*MockSQLQuerier)(nil).UpsertHostCurrentState), ctx, arg)
}

// UpsertProductStream mocks base method.
func (m *MockSQLQuerier) UpsertProductStream(ctx context.Context, arg sql.UpsertProductStreamParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertProductStream", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertProductStream indicates an expected call of UpsertProductStream.
func (mr *MockSQLQuerierMockRecorder) UpsertProductStream(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertProductStream", reflect.TypeOf((*MockSQLQuerier)(nil).UpsertProductStream), ctx, arg)
}

// UpsertSetting mocks base method.
func (m *MockSQLQuerier) UpsertSetting(ctx context.Context, arg sql.UpsertSettingParams) (sql.Setting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertSetting", ctx, arg)
	ret0, _ := ret[0].(sql.Setting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertSetting indicates an expected call of UpsertSetting.
func (mr *MockSQLQuerierMockRecorder) UpsertSetting(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertSetting", reflect.TypeOf((*MockSQLQuerier)(nil).UpsertSetting), ctx, arg)
}
