// Code generated by MockGen. DO NOT EDIT.
// Source: bazel-out/k8-fastbuild/bin/internal/mock/gopath/src/go.patchbase.net/server/internal/services/advisory_sync.go
//
// Generated by this command:
//
//	mockgen -source bazel-out/k8-fastbuild/bin/internal/mock/gopath/src/go.patchbase.net/server/internal/services/advisory_sync.go -package mock -mock_names AdvisorySyncService=MockAdvisorySyncService
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	services "go.patchbase.net/server/internal/services"
	sql "go.patchbase.net/server/internal/sql"
	gomock "go.uber.org/mock/gomock"
)

// MockAdvisorySyncService is a mock of AdvisorySyncService interface.
type MockAdvisorySyncService struct {
	ctrl     *gomock.Controller
	recorder *MockAdvisorySyncServiceMockRecorder
	isgomock struct{}
}

// MockAdvisorySyncServiceMockRecorder is the mock recorder for MockAdvisorySyncService.
type MockAdvisorySyncServiceMockRecorder struct {
	mock *MockAdvisorySyncService
}

// NewMockAdvisorySyncService creates a new mock instance.
func NewMockAdvisorySyncService(ctrl *gomock.Controller) *MockAdvisorySyncService {
	mock := &MockAdvisorySyncService{ctrl: ctrl}
	mock.recorder = &MockAdvisorySyncServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdvisorySyncService) EXPECT() *MockAdvisorySyncServiceMockRecorder {
	return m.recorder
}

// GetAdvisory mocks base method.
func (m *MockAdvisorySyncService) GetAdvisory(ctx context.Context, id string) (sql.Advisory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdvisory", ctx, id)
	ret0, _ := ret[0].(sql.Advisory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdvisory indicates an expected call of GetAdvisory.
func (mr *MockAdvisorySyncServiceMockRecorder) GetAdvisory(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdvisory", reflect.TypeOf((*MockAdvisorySyncService)(nil).GetAdvisory), ctx, id)
}

// GetOverview mocks base method.
func (m *MockAdvisorySyncService) GetOverview(ctx context.Context) (services.AdvisoryOverview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOverview", ctx)
	ret0, _ := ret[0].(services.AdvisoryOverview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOverview indicates an expected call of GetOverview.
func (mr *MockAdvisorySyncServiceMockRecorder) GetOverview(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOverview", reflect.TypeOf((*MockAdvisorySyncService)(nil).GetOverview), ctx)
}

// GetScopeStatuses mocks base method.
func (m *MockAdvisorySyncService) GetScopeStatuses(ctx context.Context) ([]services.AdvisoryScopeStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScopeStatuses", ctx)
	ret0, _ := ret[0].([]services.AdvisoryScopeStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScopeStatuses indicates an expected call of GetScopeStatuses.
func (mr *MockAdvisorySyncServiceMockRecorder) GetScopeStatuses(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScopeStatuses", reflect.TypeOf((*MockAdvisorySyncService)(nil).GetScopeStatuses), ctx)
}

// RegisterScopeDemand mocks base method.
func (m *MockAdvisorySyncService) RegisterScopeDemand(ctx context.Context, scopeKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterScopeDemand", ctx, scopeKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterScopeDemand indicates an expected call of RegisterScopeDemand.
func (mr *MockAdvisorySyncServiceMockRecorder) RegisterScopeDemand(ctx, scopeKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterScopeDemand", reflect.TypeOf((*MockAdvisorySyncService)(nil).RegisterScopeDemand), ctx, scopeKey)
}

// ResolveScopeKey mocks base method.
func (m *MockAdvisorySyncService) ResolveScopeKey(ctx context.Context, osFamily, osName, osVersion string, osMajor int32, arch string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveScopeKey", ctx, osFamily, osName, osVersion, osMajor, arch)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveScopeKey indicates an expected call of ResolveScopeKey.
func (mr *MockAdvisorySyncServiceMockRecorder) ResolveScopeKey(ctx, osFamily, osName, osVersion, osMajor, arch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveScopeKey", reflect.TypeOf((*MockAdvisorySyncService)(nil).ResolveScopeKey), ctx, osFamily, osName, osVersion, osMajor, arch)
}

// SyncScope mocks base method.
func (m *MockAdvisorySyncService) SyncScope(ctx context.Context, scopeKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncScope", ctx, scopeKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncScope indicates an expected call of SyncScope.
func (mr *MockAdvisorySyncServiceMockRecorder) SyncScope(ctx, scopeKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncScope", reflect.TypeOf((*MockAdvisorySyncService)(nil).SyncScope), ctx, scopeKey)
}

// TriggerManualSync mocks base method.
func (m *MockAdvisorySyncService) TriggerManualSync(ctx context.Context, scopeKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerManualSync", ctx, scopeKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// TriggerManualSync indicates an expected call of TriggerManualSync.
func (mr *MockAdvisorySyncServiceMockRecorder) TriggerManualSync(ctx, scopeKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerManualSync", reflect.TypeOf((*MockAdvisorySyncService)(nil).TriggerManualSync), ctx, scopeKey)
}
