// Code generated by MockGen. DO NOT EDIT.
// Source: bazel-out/k8-fastbuild/bin/internal/mock/gopath/src/go.patchbase.net/server/internal/services/auth.go
//
// Generated by this command:
//
//	mockgen -source bazel-out/k8-fastbuild/bin/internal/mock/gopath/src/go.patchbase.net/server/internal/services/auth.go -package mock -mock_names Auth=MockAuth
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	services "go.patchbase.net/server/internal/services"
	sql "go.patchbase.net/server/internal/sql"
	gomock "go.uber.org/mock/gomock"
)

// MockAuth is a mock of Auth interface.
type MockAuth struct {
	ctrl     *gomock.Controller
	recorder *MockAuthMockRecorder
	isgomock struct{}
}

// MockAuthMockRecorder is the mock recorder for MockAuth.
type MockAuthMockRecorder struct {
	mock *MockAuth
}

// NewMockAuth creates a new mock instance.
func NewMockAuth(ctrl *gomock.Controller) *MockAuth {
	mock := &MockAuth{ctrl: ctrl}
	mock.recorder = &MockAuthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuth) EXPECT() *MockAuthMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockAuth) Authenticate(ctx context.Context, token string) (sql.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", ctx, token)
	ret0, _ := ret[0].(sql.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockAuthMockRecorder) Authenticate(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockAuth)(nil).Authenticate), ctx, token)
}

// IssueAccessToken mocks base method.
func (m *MockAuth) IssueAccessToken(ctx context.Context, userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueAccessToken", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueAccessToken indicates an expected call of IssueAccessToken.
func (mr *MockAuthMockRecorder) IssueAccessToken(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueAccessToken", reflect.TypeOf((*MockAuth)(nil).IssueAccessToken), ctx, userID)
}

// Login mocks base method.
func (m *MockAuth) Login(ctx context.Context, email, password, ipAddress, userAgent string) (services.LoginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password, ipAddress, userAgent)
	ret0, _ := ret[0].(services.LoginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthMockRecorder) Login(ctx, email, password, ipAddress, userAgent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuth)(nil).Login), ctx, email, password, ipAddress, userAgent)
}

// UpdateProfile mocks base method.
func (m *MockAuth) UpdateProfile(ctx context.Context, actor services.ActorRef, userID string, input services.UpdateProfileInput) (services.UpdateProfileResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, actor, userID, input)
	ret0, _ := ret[0].(services.UpdateProfileResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockAuthMockRecorder) UpdateProfile(ctx, actor, userID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockAuth)(nil).UpdateProfile), ctx, actor, userID, input)
}
