// Code generated by MockGen. DO NOT EDIT.
// Source: bazel-out/k8-fastbuild/bin/internal/mock/gopath/src/go.patchbase.net/server/internal/mailer/interface.go
//
// Generated by this command:
//
//	mockgen -source bazel-out/k8-fastbuild/bin/internal/mock/gopath/src/go.patchbase.net/server/internal/mailer/interface.go -package mock -mock_names Mailer=MockMailer
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	services "go.patchbase.net/server/internal/services"
	gomock "go.uber.org/mock/gomock"
)

// MockMailer is a mock of Mailer interface.
type MockMailer struct {
	ctrl     *gomock.Controller
	recorder *MockMailerMockRecorder
	isgomock struct{}
}

// MockMailerMockRecorder is the mock recorder for MockMailer.
type MockMailerMockRecorder struct {
	mock *MockMailer
}

// NewMockMailer creates a new mock instance.
func NewMockMailer(ctrl *gomock.Controller) *MockMailer {
	mock := &MockMailer{ctrl: ctrl}
	mock.recorder = &MockMailerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMailer) EXPECT() *MockMailerMockRecorder {
	return m.recorder
}

// SendReport mocks base method.
func (m *MockMailer) SendReport(ctx context.Context, to []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendReport", ctx, to)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendReport indicates an expected call of SendReport.
func (mr *MockMailerMockRecorder) SendReport(ctx, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendReport", reflect.TypeOf((*MockMailer)(nil).SendReport), ctx, to)
}

// TestConnection mocks base method.
func (m *MockMailer) TestConnection(ctx context.Context, s services.SMTPSettings, to string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestConnection", ctx, s, to)
	ret0, _ := ret[0].(error)
	return ret0
}

// TestConnection indicates an expected call of TestConnection.
func (mr *MockMailerMockRecorder) TestConnection(ctx, s, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestConnection", reflect.TypeOf((*MockMailer)(nil).TestConnection), ctx, s, to)
}
