// Code generated by MockGen. DO NOT EDIT.
// Source: bazel-out/k8-fastbuild/bin/internal/mock/gopath/src/go.patchbase.net/server/internal/services/hosts.go
//
// Generated by this command:
//
//	mockgen -source bazel-out/k8-fastbuild/bin/internal/mock/gopath/src/go.patchbase.net/server/internal/services/hosts.go -package mock -mock_names Hosts=MockHosts
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	agent "go.patchbase.net/proto/agent"
	services "go.patchbase.net/server/internal/services"
	utils "go.patchbase.net/server/internal/utils"
	gomock "go.uber.org/mock/gomock"
)

// MockHosts is a mock of Hosts interface.
type MockHosts struct {
	ctrl     *gomock.Controller
	recorder *MockHostsMockRecorder
	isgomock struct{}
}

// MockHostsMockRecorder is the mock recorder for MockHosts.
type MockHostsMockRecorder struct {
	mock *MockHosts
}

// NewMockHosts creates a new mock instance.
func NewMockHosts(ctrl *gomock.Controller) *MockHosts {
	mock := &MockHosts{ctrl: ctrl}
	mock.recorder = &MockHostsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHosts) EXPECT() *MockHostsMockRecorder {
	return m.recorder
}

// ApproveHost mocks base method.
func (m *MockHosts) ApproveHost(ctx context.Context, actor services.ActorRef, hostID string) (services.HostInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveHost", ctx, actor, hostID)
	ret0, _ := ret[0].(services.HostInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApproveHost indicates an expected call of ApproveHost.
func (mr *MockHostsMockRecorder) ApproveHost(ctx, actor, hostID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveHost", reflect.TypeOf((*MockHosts)(nil).ApproveHost), ctx, actor, hostID)
}

// CreateManualHost mocks base method.
func (m *MockHosts) CreateManualHost(ctx context.Context, actor services.ActorRef, displayName, hostname string) (services.HostInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateManualHost", ctx, actor, displayName, hostname)
	ret0, _ := ret[0].(services.HostInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateManualHost indicates an expected call of CreateManualHost.
func (mr *MockHostsMockRecorder) CreateManualHost(ctx, actor, displayName, hostname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateManualHost", reflect.TypeOf((*MockHosts)(nil).CreateManualHost), ctx, actor, displayName, hostname)
}

// CreateRegistrationToken mocks base method.
func (m *MockHosts) CreateRegistrationToken(ctx context.Context, actor services.ActorRef, userID, name string, autoApprove bool) (services.CreatedRegistrationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRegistrationToken", ctx, actor, userID, name, autoApprove)
	ret0, _ := ret[0].(services.CreatedRegistrationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRegistrationToken indicates an expected call of CreateRegistrationToken.
func (mr *MockHostsMockRecorder) CreateRegistrationToken(ctx, actor, userID, name, autoApprove any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRegistrationToken", reflect.TypeOf((*MockHosts)(nil).CreateRegistrationToken), ctx, actor, userID, name, autoApprove)
}

// CreateSSHHost mocks base method.
func (m *MockHosts) CreateSSHHost(ctx context.Context, actor services.ActorRef, input services.CreateSSHHostInput) (services.CreateSSHHostResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSSHHost", ctx, actor, input)
	ret0, _ := ret[0].(services.CreateSSHHostResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSSHHost indicates an expected call of CreateSSHHost.
func (mr *MockHostsMockRecorder) CreateSSHHost(ctx, actor, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSSHHost", reflect.TypeOf((*MockHosts)(nil).CreateSSHHost), ctx, actor, input)
}

// DeleteHost mocks base method.
func (m *MockHosts) DeleteHost(ctx context.Context, actor services.ActorRef, hostID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHost", ctx, actor, hostID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteHost indicates an expected call of DeleteHost.
func (mr *MockHostsMockRecorder) DeleteHost(ctx, actor, hostID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHost", reflect.TypeOf((*MockHosts)(nil).DeleteHost), ctx, actor, hostID)
}

// GetCollectorScript mocks base method.
func (m *MockHosts) GetCollectorScript(osFamily string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCollectorScript", osFamily)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCollectorScript indicates an expected call of GetCollectorScript.
func (mr *MockHostsMockRecorder) GetCollectorScript(osFamily any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollectorScript", reflect.TypeOf((*MockHosts)(nil).GetCollectorScript), osFamily)
}

// GetDashboardOverview mocks base method.
func (m *MockHosts) GetDashboardOverview(ctx context.Context) (services.DashboardOverview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDashboardOverview", ctx)
	ret0, _ := ret[0].(services.DashboardOverview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDashboardOverview indicates an expected call of GetDashboardOverview.
func (mr *MockHostsMockRecorder) GetDashboardOverview(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDashboardOverview", reflect.TypeOf((*MockHosts)(nil).GetDashboardOverview), ctx)
}

// GetHost mocks base method.
func (m *MockHosts) GetHost(ctx context.Context, hostID string) (services.HostInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHost", ctx, hostID)
	ret0, _ := ret[0].(services.HostInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHost indicates an expected call of GetHost.
func (mr *MockHostsMockRecorder) GetHost(ctx, hostID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHost", reflect.TypeOf((*MockHosts)(nil).GetHost), ctx, hostID)
}

// GetLatestSnapshot mocks base method.
func (m *MockHosts) GetLatestSnapshot(ctx context.Context, hostID string) (services.HostSnapshotInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestSnapshot", ctx, hostID)
	ret0, _ := ret[0].(services.HostSnapshotInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestSnapshot indicates an expected call of GetLatestSnapshot.
func (mr *MockHostsMockRecorder) GetLatestSnapshot(ctx, hostID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestSnapshot", reflect.TypeOf((*MockHosts)(nil).GetLatestSnapshot), ctx, hostID)
}

// IngestAgentSnapshot mocks base method.
func (m *MockHosts) IngestAgentSnapshot(ctx context.Context, hostAccessToken string, payload *agent.AgentSnapshot) (*agent.SyncResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IngestAgentSnapshot", ctx, hostAccessToken, payload)
	ret0, _ := ret[0].(*agent.SyncResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IngestAgentSnapshot indicates an expected call of IngestAgentSnapshot.
func (mr *MockHostsMockRecorder) IngestAgentSnapshot(ctx, hostAccessToken, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IngestAgentSnapshot", reflect.TypeOf((*MockHosts)(nil).IngestAgentSnapshot), ctx, hostAccessToken, payload)
}

// IngestManualReport mocks base method.
func (m *MockHosts) IngestManualReport(ctx context.Context, actor services.ActorRef, hostID string, reportContent []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IngestManualReport", ctx, actor, hostID, reportContent)
	ret0, _ := ret[0].(error)
	return ret0
}

// IngestManualReport indicates an expected call of IngestManualReport.
func (mr *MockHostsMockRecorder) IngestManualReport(ctx, actor, hostID, reportContent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IngestManualReport", reflect.TypeOf((*MockHosts)(nil).IngestManualReport), ctx, actor, hostID, reportContent)
}

// ListHosts mocks base method.
func (m *MockHosts) ListHosts(ctx context.Context) ([]services.HostInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHosts", ctx)
	ret0, _ := ret[0].([]services.HostInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListHosts indicates an expected call of ListHosts.
func (mr *MockHostsMockRecorder) ListHosts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHosts", reflect.TypeOf((*MockHosts)(nil).ListHosts), ctx)
}

// ListPendingHosts mocks base method.
func (m *MockHosts) ListPendingHosts(ctx context.Context) ([]services.HostInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingHosts", ctx)
	ret0, _ := ret[0].([]services.HostInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPendingHosts indicates an expected call of ListPendingHosts.
func (mr *MockHostsMockRecorder) ListPendingHosts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingHosts", reflect.TypeOf((*MockHosts)(nil).ListPendingHosts), ctx)
}

// ListRegistrationTokens mocks base method.
func (m *MockHosts) ListRegistrationTokens(ctx context.Context) ([]services.RegistrationTokenInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRegistrationTokens", ctx)
	ret0, _ := ret[0].([]services.RegistrationTokenInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRegistrationTokens indicates an expected call of ListRegistrationTokens.
func (mr *MockHostsMockRecorder) ListRegistrationTokens(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRegistrationTokens", reflect.TypeOf((*MockHosts)(nil).ListRegistrationTokens), ctx)
}

// ListSSHPullJobs mocks base method.
func (m *MockHosts) ListSSHPullJobs(ctx context.Context, hostID string) ([]services.HostSSHPullJobInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSSHPullJobs", ctx, hostID)
	ret0, _ := ret[0].([]services.HostSSHPullJobInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSSHPullJobs indicates an expected call of ListSSHPullJobs.
func (mr *MockHostsMockRecorder) ListSSHPullJobs(ctx, hostID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSSHPullJobs", reflect.TypeOf((*MockHosts)(nil).ListSSHPullJobs), ctx, hostID)
}

// OnboardSSHHost mocks base method.
func (m *MockHosts) OnboardSSHHost(ctx context.Context, actor services.ActorRef, hostID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnboardSSHHost", ctx, actor, hostID)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnboardSSHHost indicates an expected call of OnboardSSHHost.
func (mr *MockHostsMockRecorder) OnboardSSHHost(ctx, actor, hostID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnboardSSHHost", reflect.TypeOf((*MockHosts)(nil).OnboardSSHHost), ctx, actor, hostID)
}

// RegisterAgentHost mocks base method.
func (m *MockHosts) RegisterAgentHost(ctx context.Context, input *agent.RegisterHostRequest) (*agent.RegisterHostResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterAgentHost", ctx, input)
	ret0, _ := ret[0].(*agent.RegisterHostResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterAgentHost indicates an expected call of RegisterAgentHost.
func (mr *MockHostsMockRecorder) RegisterAgentHost(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterAgentHost", reflect.TypeOf((*MockHosts)(nil).RegisterAgentHost), ctx, input)
}

// RevokeRegistrationToken mocks base method.
func (m *MockHosts) RevokeRegistrationToken(ctx context.Context, actor services.ActorRef, tokenID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeRegistrationToken", ctx, actor, tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeRegistrationToken indicates an expected call of RevokeRegistrationToken.
func (mr *MockHostsMockRecorder) RevokeRegistrationToken(ctx, actor, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRegistrationToken", reflect.TypeOf((*MockHosts)(nil).RevokeRegistrationToken), ctx, actor, tokenID)
}

// RunSSHPull mocks base method.
func (m *MockHosts) RunSSHPull(ctx context.Context, actor services.ActorRef, hostID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunSSHPull", ctx, actor, hostID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunSSHPull indicates an expected call of RunSSHPull.
func (mr *MockHostsMockRecorder) RunSSHPull(ctx, actor, hostID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunSSHPull", reflect.TypeOf((*MockHosts)(nil).RunSSHPull), ctx, actor, hostID)
}

// UpdateHost mocks base method.
func (m *MockHosts) UpdateHost(ctx context.Context, actor services.ActorRef, hostID string, input services.UpdateHostInput) (services.HostInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHost", ctx, actor, hostID, input)
	ret0, _ := ret[0].(services.HostInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateHost indicates an expected call of UpdateHost.
func (mr *MockHostsMockRecorder) UpdateHost(ctx, actor, hostID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHost", reflect.TypeOf((*MockHosts)(nil).UpdateHost), ctx, actor, hostID, input)
}

// UpdateHostNotes mocks base method.
func (m *MockHosts) UpdateHostNotes(ctx context.Context, hostID string, notes utils.Option[string]) (services.HostInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHostNotes", ctx, hostID, notes)
	ret0, _ := ret[0].(services.HostInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateHostNotes indicates an expected call of UpdateHostNotes.
func (mr *MockHostsMockRecorder) UpdateHostNotes(ctx, hostID, notes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHostNotes", reflect.TypeOf((*MockHosts)(nil).UpdateHostNotes), ctx, hostID, notes)
}
