name: Tests

on: push
jobs:
  test:
    name: Bazel
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@c5acdfb288317d0b5c0bbd7a396a3dc868bb0f86 #0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: Start Test Database
        uses: hoverkraft-tech/compose-action@11beaa1c2dae4e8ed7b1665aa074723b6cecb0e4 # v3
        with:
          compose-file: "./compose.test.yaml"
      - name: Build Targets
        run: bazel build //...
      - name: Run Tests
        run: bazel test --test_output=errors //...

      - name: Cleanup Environment
        if: ${{ always() }}
        run: docker compose -f ./compose.test.yaml down --volumes --remove-orphans
